### ISSUE TITLE
tidy incorrectly warns when <script> tags have html inside

### ISSUE THREAD

**Issue by joeheyming** [htacg/tidy-html5#281] opened 2015-10-02 18:12 UTC
Some javascript libraries use script tags for templates:
&lt;script type="text/html" id="my-template"&gt;
&lt;h1&gt;hello world&lt;/h1&gt;
&lt;/script&gt;

When I put html with a script tag like this , tidy5 warns for me around any closing tag that is not a closing &lt;/script&gt; tag:
line 383 column 97 - Warning: '&lt;' + '/' + letter not allowed here

**Comment by geoffmcl** [comment] 2015-10-03 18:50
@joeheyming yes, that certainly seems an erroneous warning output...

Will look at it soonest, unless someone else beats me to it...

Thanks for reporting...

**Comment by geoffmcl** [comment] 2015-10-07 14:20
@joeheyming hmmmmm, that message usually warns that tidy has inserted an escape character into javascript...

But this conversion of `/` to `\/` only happens if the container has no attributes, like just `<script>`, or has a type or lang attribute declaring it as "javascript"...

In this sample you have used `type="text/html"`, so you see the warning but not the effect...

I guess this warning should be after the attribute check, and only issue it if tidy adds the escape character...

Since I am presently working in an experimental branch `issue-65`, have effected this change there for testing...

To get this version, please do

```
$ cd tidy-html5
$ git checkout issue-65
$ git pull
$ cd build/cmake
$ rm CMakeCache.txt [optional]
$ ./build-me.sh
$ ./tidy -v
$ HTML Tidy for <OS> version 5.1.14.EXP1
```

Hope you get a chance to re-test using verions 5.1.14.EXP1 and report... thanks...

**Comment by joeheyming** [comment] 2015-10-07 17:12
I just tested this out, thanks so much for looking at this.

I still am having the issue with my freshly built issue-65 branch.  I ran your instructions and am pointing to my local ./tidy5 under build/cmake:

line 383 column 97 - Warning: '<' + '/' + letter not allowed here
line 384 column 37 - Warning: '<' + '/' + letter not allowed here

Here is the offending html:
<script type="text/html" id="some-template">
  <i class="tiny some-icon" data-bind="css: 'some-css-class' + value.toLowerCase()"></i>
  <span data-bind="text: label"></span>
</script>

It doesn't like the closing </i> tag and the closing </span> tag.

**Comment by geoffmcl** [comment] 2015-10-07 17:36
@joeheyming, unfortunately can not duplicate a problem with the html sample you give...

Is that a typo `my local ./tidy5`? 

Tidy does NOT have a `5` appended since release 5.0.0 in June this year!

What do you get when you run `./tidy -v`? 

If you do not see 5.1.14.EXP1, especially the **EXP1**, then something is wrong in your checkout of `issue-65` branch?

What branch displays when you run `$ git status`?

Very puzzled...

**Comment by joeheyming** [comment] 2015-10-07 17:42
ahah, that was it.  Thanks, I've been using tidy5 since I wrote my html lint test back in June! :-P

Looks like it works!

**Comment by geoffmcl** [comment] 2015-10-31 13:18
@joeheyming have fully merged `issue-65` branch to `master` and will get around to deleting it...

If you get a chance to pull, build, install `master` version 5.1.17 plus, and confirm this remains fixed, maybe we can close this issue? Thanks...

**Comment by balthisar** [comment] 2015-11-05 02:12
@joeheyming indicates the issue is resolved, and testing master on my system indicates that too, so I'll close the issue.

**Closed by balthisar** 2015-11-05 02:12 UTC
Labels: Bug Confirmed

**Comment by joeheyming** [comment] 2015-12-08 00:21
If I install tidy with homebrew, will I be getting tidy with this issue resolved?
This is my version:

$$ tidy -v
HTML Tidy for Mac OS X version 5.0.0

**Comment by geoffmcl** [comment] 2015-12-10 14:23
@joeheyming no, I think not... my reading of http://braumeister.org/formula/tidy-html5 says that only has 5.0.0! This fix is only in 5.1.17++

You could add a [comment](https://github.com/Homebrew/homebrew/commit/74c2df7c6d57170ab6e277597f4da4a8d8103a40#Library/Formula/tidy-html5.rb) to this commit, asking @zmwangx, @mikemcquaid to add the [5.1.25](https://github.com/htacg/tidy-html5/releases/tag/5.1.25) release... it is a dropin replacement of 5.0.0... just change the url to  https://github.com/htacg/tidy-html5/archive/5.1.25.tar.gz...

But why use homebrew? I note they have a backlog of some 250 PR, and a similar number of issues, so it looks like the `homebrew` maintainers have some catching up to do...

Why not continue to build your tidy from source, like it seemed you were doing at the beginning, then you can use the latest, 5.1.32, or even participate in testing of developmental branches...

**Tidy needs your help!**

**Comment by zmwangx** [comment] 2015-12-10 14:46
Happy to oblige, submitted https://github.com/Homebrew/homebrew/pull/46874.

> But why use homebrew?

It's awesome. You'll know if you've used it.

> I note they have a backlog of some 250 PR, and a similar number of issues, so it looks like the homebrew maintainers have some catching up to do...

You'll know they're doing a good job if you also look at the number of issues/PRs closed... PR: 242 open, 30253 closed. Issues: 254 open, 16084 closed.

**Comment by mikemcquaid** [comment] 2015-12-10 14:50
> But why use homebrew? I note they have a backlog of some 250 PR, and a similar number of issues, so it looks like the homebrew maintainers have some catching up to do...

I think it's a bit rude to ping me by name and then say that, @geoffmcl. The reason we have a large backlog is because e.g. [we had 26 pull requests opened yesterday](repo:homebrew/homebrew created:2015-12-09 is:pr).

**Comment by joeheyming** [comment] 2015-12-10 16:28
Ok Ok. Thanks @all for all your help.  I really appreciate it.  @zmwangx Those stats are awesome, I wish I was able to make that big of an impact with open source. @geoffmcl Be careful what you wish for, maybe you'll get a pull request from me someday :-)

**Comment by geoffmcl** [comment] 2015-12-10 16:37
@joeheyming yes, the stats are **awesome**... sorry for the casual observation! And look forward to your PR so you **can** make an impact on open source ;=))

**Comment by joeheyming** [comment] 2015-12-10 18:50
@geoffmcl The reason I hesitate to build directly from the source is that I work with a team of other developers and they understand homebrew.  The barrier to entry increases as you require manual steps.  Basically I'm using tidy to block git pushes to my team's repository if any html is malformed.

**Comment by balthisar** [comment] 2015-12-11 01:00
@mikemcquaid, clearly @geoffmcl meant _your_ stats are awesome. Is there anything I can do to help ensure we keep up to date with homebrew? I'm _not_ the package manager for homebrew's tidy package, but as one of the Tidy team and a Mac user myself, I'll do what I can when I can.

**Comment by mikemcquaid** [comment] 2015-12-11 09:11
> @mikemcquaid, clearly @geoffmcl meant your stats are awesome. Is there anything I can do to help ensure we keep up to date with homebrew? I'm not the package manager for homebrew's tidy package, but as one of the Tidy team and a Mac user myself, I'll do what I can when I can.

@balthisar We sorted it out but thanks for clarifying. You could just submit new releases as formulae updates to Homebrew (if your buildsystem is the same it's just a URL and checksum change). Thanks!
