### ISSUE TITLE
beginner on windows -- tidy reports: document: "a0.htm" is not a file! -- But it is

### ISSUE THREAD

**Issue by d0ugm** [htacg/tidy-html5#918] opened 2020-12-29 15:35 UTC

**Comment by jmadiot** [comment] 2021-01-19 21:03
Is the file read-only? If yes, that is probably a duplicate of #681.

**Comment by geoffmcl** [comment] 2021-02-17 17:48
@d0ugm, you have not replied to @jmadiot suggestion that it may be a duplicate of #681, like #789 is...

But since #681 is still an open issue, a `BUG` waiting for a code fix, and there has been no further feedback here, assume this can be closed...

Please re-open, and explain, in more detail, if it is something different... thanks...

**Closed by geoffmcl** 2021-02-17 17:48 UTC
