### ISSUE TITLE
tidy-html5 has a little problem with this  <!--

### ISSUE THREAD

**Issue by maxfancourt** [htacg/tidy-html5#451] opened 2016-08-26 14:57 UTC
I have been trying out Balthisar Tidy which uses the Tidy-html5 and I have come across a little issue which is in this scenario

the example is this:

```
<!DOCTYPE HTML>
<html>
<head>
<meta charset="UTF-8">
<title>Untitled</title>
<meta name="viewport" content="width = 960, minimum-scale = 0.25, maximum-scale = 1.60">
<link rel=stylesheet href="css/index.css">
<link rel=stylesheet href="css/sheet1.css">
<!--[if lt IE 9]>
<script src="Resources/html5shiv.js"></script>
<![endif]-->
</head>
<body>
<div id="PageDiv">
</div>
</body>
</html>

```

when I use tidy I get this

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Untitled</title>
    <meta content="width = 960, minimum-scale = 0.25, maximum-scale = 1.60" name="viewport">
    <link href="css/index.css" rel="stylesheet">
    <link href="css/sheet1.css" rel="stylesheet"><!--[if lt IE 9]>
<script src="Resources/html5shiv.js"></script>
<![endif]-->
</head>
<body>
    <div id="PageDiv"></div>
</body>
</html>
```

and as you can see the **<!--** has moved up to sit next to:  **stylesheet">**

all the best
max

**Comment by geoffmcl** [comment] 2016-08-26 17:20
@maxfancourt thanks for the issue...

I will let @Balthisar answer for his Tidy, but can certainly confirm that not putting the comment on a new line is certainly the default action of the latest **libTidy** 5.3.9 in `master`...

I thought the option `--vertical-space yes` might do something, but found no option to change this behavior!

Certainly, aesthetically speaking, it would also be ok to start the comment on a new line, and going back to the old SF release, 25 March 2009, it did just that... so it got changed some time later, but earlier than tidy5-4.9.14, circa 2015-02-10...

But in reality, is there anything wrong with the current tidy action? It is the beginning of a comment after all...

Seek further comments... thanks...

**Comment by geoffmcl** [comment] 2016-08-26 18:03
@maxfancourt I think old tidy 2009 did this by always flushing that `<link ...` line, but that can add addition newlines, which some users did not like... so was removed...

But without getting into an option to control this behavior, the patch is relatively trivial -

````patch
diff --git a/src/pprint.c b/src/pprint.c
index a4f2aef..1d922c1 100644
--- a/src/pprint.c
+++ b/src/pprint.c
@@ -2194,6 +2194,7 @@ void TY_(PPrintTree)( TidyDocImpl* doc, uint mode, uint indent, Node *node )
     }
     else if ( node->type == CommentTag )
     {
+        PCondFlushLineSmart( doc, indent ); // #450 - start comment on new line
         PPrintComment( doc, indent, node );
     }
     else if ( node->type == RootNode )
````

Just a quick experiment... not fully tested...

### As stated, seek further comments... thanks...

**Comment by maxfancourt** [comment] 2016-08-26 22:05
Hi Geoff you are quite right there is nothing wrong with the comment being on the same line.. it was down to visual aesthetics.... so not a big issue  at all... just a little one

max

**Comment by balthisar** [comment] 2017-01-31 22:37
@maxfancourt, sorry, I've been away and missed this. The issue is still present in 5.3.14, which Balthisar Tidy was just updated to use.

Let me consider taking @geoffmcl's patch into an option, as I gently return to the coding world.

**Comment by balthisar** [comment] 2017-02-09 20:27
I will also close this in favor of #486. Don't worry, these close issues will still be referred to from the other issue, but this will help me consolidate a lot of these types of issues into a single issue, since they're related.

**Closed by balthisar** 2017-02-09 20:27 UTC
Labels: Feature Request, Help Needed, Pretty Print
