### ISSUE TITLE
Literal '<' characters don't yield errors or warnings

### ISSUE THREAD

**Issue by khink** [htacg/tidy-html5#88] opened 2013-05-16 11:22 UTC
My HTML has a bare '<' character in it, two in fact:

    <div class="running-text comment">
                    >>wenn das mit dem streng säkularen staat so wäre wie viele es hier sehen wollen, dann wäre die CDU/CSU schon wegen ihres C im Namen eine völlig illegitime Partei. <<
    Ich fürchte, die würden sich einfach umbenennen.
                  </div>

When i run ```tidy -utf8 kruzifix-im-muenchner-gericht.html 2>&1 | tee output.txt```, only warnings are shown but none pertains tot this flaw in the HTML. See gists https://gist.github.com/khink/5591067 (HTML) and https://gist.github.com/khink/5591077 (Tidy output).

I'm using Ubuntu 13.04 with Tidy installed as described here: http://therealmarv.blogspot.de/2012/12/installing-tidy-html5-on-ubuntu-first.html

**Comment by geoffmcl** [comment] 2015-01-31 16:39
As you may know the current development is in the develop-500 branch -
$ git checkout develop-500
and issues can only be tested against this branch at present...

1: First a simple sample, input5\in_88-2.html, input
````
<!DOCTYPE html>
<head>
<meta charset=utf-8>
<title>markup inside a code block should be ignored. #94</title>
</head>
<body>
<div class="running-text comment">
before >> between << after
</div>
</body>
</html>
````

2: After this is processed by the above dev5 Tidy, input5\in_88-3.html, output
````
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>markup inside a code block should be ignored. #94</title>
</head>
<body>
<div class="running-text comment">before &gt;&gt; between &lt;&lt;
after</div>
</body>
</html>
````

So note that Tidy5 has converted the ```<``` and ```>``` to ```&gt;``` and ```&lt;``` entities.

For sure the 1: will NOT pass the validator, but the 2: tidied version will!

This is part of the 'silent' fix-ups that tidy has always done for you, so this 
is NOT a bug, but a feature of Tidy ;=))

Your orignal sample contains invalid UTF-8 characters so Tidy does issue warnings for those...

If you get a chance to pull the latest dev5, build and test the latest, appreciate you closing this issue if all is corrent.

Note that the link to install Tidy5 no longer exists, but I hope we will soon get around to posting binaries somewhere so you can still test even if you are unable to build tidy5 yourself from source.

**Comment by balthisar** [comment] 2015-02-01 09:15
Current behavior is as expected. Will close.

**Closed by balthisar** 2015-02-01 09:15 UTC
Labels: Bug Report
