### ISSUE TITLE
Do not mess up Jinja templates

### ISSUE THREAD

**Issue by hermanbergwerf** [htacg/tidy-html5#310] opened 2015-11-18 22:08 UTC
`tidy` messes up Jinja templates. Would it be possible to add an option to format Jinja templates correctly?

**Comment by balthisar** [comment] 2015-11-19 08:12
Per our [FAQ](http://www.html-tidy.org/documentation/#part_faq), can you provide the following:

- A description of what you think went wrong.
- The HTML Tidy version (find it out by running tidy -v), and operating system you are running.
- The input that exposes the bug. A small HTML document that reproduces the problem is best.
- The configuration options you’ve used. Command line options like -asxml, configuration files, etc. - - You may use tidy -show-config to get an overview of the active Tidy settings.

Even if we try to figure out what a Jinja template is, there's no guarantee that we'll have anything go wrong, so a short, failing example posted here would be useful.

**Comment by hermanbergwerf** [comment] 2015-11-19 09:30
Ok, sorry, I like brief descriptions myself and I thought Jinja was kind of common knowledge (Jinja is the backbone of Sphinx, Jekyll, etc.). Also, could you put the contributing guidelines in CONTRIBUTING.md (https://github.com/blog/1184-contributing-guidelines) Jinja is a template engine written in Python. See http://jinja.pocoo.org/.

# What went wrong
Sphinx (and Jekyll) templates are written using Jinja. A template might look something like this:
```html
{% extends "layout.html" %}
{% block body %}
  <ul>
  {% for user in users %}
    <li><a href="{{ user.url }}">{{ user.username }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}
```
I created an auto-formatter for my project to prevent messed up indents etc. I picked `tidy-html5` as HTML formatter. When I formatted a repository that contained Sphinx templates (http://sphinx-doc.org/, this is a documentation generator written in Python that uses Jinja as template backend), it went wrong.

# Tidy version
5.0.0

# Reproduce
```
{% extends "layout.html" %}
{% block body %}
  <ul>
  {% for user in users %}
    <li><a href="{{ user.url }}">{{ user.username }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}
```
Tidy using standard configuration:
```
<!DOCTYPE html>
<html>
<head>
  <meta name="generator" content=
  "HTML Tidy for HTML5 for Linux version 5.0.0">
  <title></title>
</head>
<body>
  {% extends "layout.html" %} {% block body %}
  <ul>
    <li style="list-style: none">{% for user in users %}</li>
    <li>
      <a href="{{%20user.url%20}}">{{ user.username }}</a>
    </li>
    <li style="list-style: none">{% endfor %}</li>
  </ul>{% endblock %}
</body>
</html>
```
Obviously, the template itself is not valid HTML. And often, the template file only describes a fragment of the page like in this example. Note that this is also the case for web components (used by Polymer and very popular right now, you can find more about this by Googling it). Do you think you could add options to `tidy-html5` that allows me to format a Jinja template? (and html imports, which will have similar problems).

**Comment by balthisar** [comment] 2015-11-19 09:40
I see. I'll make the change to the `contributing` file, too.

Do you get results expected when you try the `show-body-only` option?

If Tidy understood {% %} tags there would still remain the problem that Tidy doesn't understand the content of the tags.

**Comment by hermanbergwerf** [comment] 2015-11-19 10:33
The `show-body-only` option generates the following output for the same HTML fragment.
```
{% extends "layout.html" %} {% block body %}
<ul>
  <li style="list-style: none">{% for user in users %}</li>
  <li>
    <a href="{{%20user.url%20}}">{{ user.username }}</a>
  </li>
  <li style="list-style: none">{% endfor %}</li>
</ul>{% endblock %}
```
This is still not entirely correct though although it seems sufficient for html imports (!, it would be great if tidy could auto detect this, I can also try to build that into my auto formatter, e.g. only if the document contains an `<html>` tag `show-body-only` is false)

Jinja syntax: http://jinja.pocoo.org/docs/dev/templates/
I think it would be a huge improvement if `{% %}`, `{{ }}`, `{# #}` got it's own line like html tags when they are not used as attributes (like `{{ }}` in the example, which should also not be URI encoded). I think it's too hard to support the `# ##` line statements (http://jinja.pocoo.org/docs/dev/templates/#line-statements). There are also some more complex multi-line cases (http://jinja.pocoo.org/docs/dev/templates/#comments).

**Comment by geoffmcl** [comment] 2015-11-19 17:36
@hermanbergwerf thanks for filling out the issue... a feature request to support [jinja](http://jinja.pocoo.org/) syntax.

One quick thing, like `--show-body-only yes`, there is another option, `--fix-uri no`, you can try, which will at least stop tidy messing up the URI.

One minor improvement in the message output only. I guess if a user has added `--fix-uri no` then tidy should **not** output the big blurb "URIs must be properly escaped, ...". The user has already said "no uri fix needed", but is quite minor...

As for putting `{% %}`, etc on a new line, I was hoping `--vertical-space yes` might help. Internally this is called `classic` tidy mode, and increases the vertical spaces. Well, while it did push `{% endblock %}` to a newline, but it left most the others as is, and added some more blank newlines...

And just experimented on running tidy on some of our site yaml templates, see `gh-pages` branch, with quite **poor** results, even using the above options. For sure one main thing is not putting `{% %}`, etc on a new line, but their were lots of other re-lining problems, issues! Tidy is not Python based!

So the question seems to be **"Should HTML Tidy become a HTML/yaml/jinja/... aware tidy?"**

My first instinct is why not? And would certainly consider a PR or patch, provided it/they did not displace one hair of standard HTML parsing and output, so that would probably mean another option, options, or something... 

OTOH are these `templates` really HTML? They can be after the `engine` has run, but before that they are more like a script to be passed to the correct parser, and maybe that is not Tidy! I guess I did not fully understand your use case involving [sphinx-doc](http://sphinx-doc.org/)?

What do others think?

**Comment by benkasminbullock** [comment] 2015-11-19 23:31
Just to generalise this, I think having a way to operate on HTML fragments would be a good addition to tidy. In other words, for example if a user has a table and they just want to check if the table has errors or problems like unclosed tags, or an inconsistent number of columns, or something, without worrying about the entire document, it would be a good idea to be able to check just the table. A lot of people are using some form or another of HTML generators. For example a `--fragment` option, which would bypass the checks for the `<head>` element.

**Comment by geoffmcl** [comment] 2015-11-20 13:23
@benkasminbullock well is that not what the **`--show-body-only yes`** does? Allows tidy to operate on a HTML fragment, and suppresses warnings about say a missing doctype, head or title...

So, for example, in what way would a say `--fragment yes/no` option be different?

And there is no way a parser can `bypass` checking something. Tidy has to parse the complete data stream, as html... Once the data stream is in a tidy node tree, only then can it skip to the body node, and ouput that alone... 

Another app, different to tidy.c, using **`libtidy`** API could choose any criteria it wanted... the API allows that app to iterate over the node tree, and output what it wanted... See the [Document Tree](http://api.html-tidy.org/tidy/tidylib_api_5.0.0/group__Tree.html) group, and others... For instance I have played with a `html2json` output, which of course does not use the `pprint` in tidy...

So even if you wanted to word say a `--fragment` option different to the current wording of [TidyBodyOnly](http://api.html-tidy.org/tidy/quickref_5.0.0.html#show-body-only) it seems to me it amounts to the same thing! 

And of course we would always entertain suggested improvements to the API documentation. Do you have a specific suggestion here?

**Comment by hermanbergwerf** [comment] 2015-11-20 17:20
I thing the `show-body-only` is sufficient, at least it worked for me. I think the question if Jinja syntax support is relevant depends on the target audience. If you want tidy to be a universal html formatter you should add optional Jinja support IMHO, if you want it to be a formatter for real html only, you should not add support for this.

The case is that in the end I want a formatter for my html files that contain Jinja syntax. As for Jekyll and Sphinx doc, the templates are processed to valid html but that's not where a formatter is relevant (I would rather compact the production version as much as possible using `vulcanize`, a tool that mangles all your resources into one file until HTTP 2.0 can 'stream' all resources). I want a formatter because I want the files in my repository to be consistent. So if we decide tidy can't do this, I would go looking for another formatter that can. This is because I was recently completely convinced that auto-formatters are THE way out of religious wars and uncountable pull requests about inconsistent code formatting.

**Comment by balthisar** [comment] 2016-01-15 08:55
I'll close this at it looks like the show-body-only option was successful. **If** anyone disagrees, please feel free to re-open with new information.

**Comment by hermanbergwerf** [comment] 2016-01-15 09:27
Not really. I added an exclude flag to my formatting program so I can
ignore jinja templates. Anyway, it's up to you guys to add jinja
compability or stick with pure html.

**Comment by balthisar** [comment] 2016-01-18 01:47
Ok, I'll keep it open with an indefinite future milestone. PR's are welcome.

**Comment by zanona** [comment] 2016-03-30 17:52
Hey guys, 
In terms of validation, not only for Jinja but many other template engines where it's common to have an example like:

```html
<ul>
  {{~it.array :value}}
    <li>{{=value}}</li>
  {{~}}
</ul>
```
This would, of course, cause tidy to warn about the line after and before the opening and closing `<ul>` tags of not being an `<li>` tag. So I was wondering that it would be quite handy to have an option to perhaps ignore validation on lines by providing a string or regex? So when that regular expression matches, it would skip that line?

Or perhaps there's already a solution for that which I am not aware of at the moment?

thanks

**Comment by geoffmcl** [comment] 2016-04-06 19:22
@hermanbergwerf, @benkasminbullock, @zanona, well a **solution** popped up when researching a fix #396 ... simply put, HTML5 a `<ul>` is allowed to have **0 or more li**, so needed to fix some things when still in hmlt5 mode... and that seems to have **helped** here... 

That 5.1.52-test1 outputs seems to matches some expectations of, **to format Jinja templates correctly**? 

In fact, I think we may be **there** ;=)) the first time since Tidy-2000!

As previously expressed, the first must set option `--fix-uri no`, but the second needs no special config, except if you want to avoid the html noise, then set `--show-body-only yes`...

Input 1:

````html
<title>Issue #310 - needs cfg --fix-uri no</title>
{% extends "layout.html" %}
{% block body %}
  <ul>
  {% for user in users %}
    <li><a href="{{ user.url }}">{{ user.username }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}
````


Output 1:

````html
<!DOCTYPE html>
<html>
<head>
  <meta name="generator" content=
  "HTML Tidy for HTML5 for Windows version 5.1.52-test1">
  <title>Issue #310 - needs cfg --fix-uri no</title>
</head>
<body>
  {% extends "layout.html" %} {% block body %}
  <ul>
    {% for user in users %}
    <li>
      <a href="{{ user.url }}">{{ user.username }}</a>
    </li>{% endfor %}
  </ul>{% endblock %}
</body>
</html>
````

Input 2:

````html
<title>Issue #310-1 cfg --show-body-only yes</title>
<ul>
  {{~it.array :value}}
    <li>{{=value}}</li>
  {{~}}
</ul>
````

Ouput 2:

````html
<ul>
  {{~it.array :value}}
  <li>{{=value}}</li>{{~}}
</ul>
````

I can see a few **relining** and/or **indenting** issues, but this should be the subject of a **new** issue... that is `Pretty Printing`...

Bug #396 is in parsing the stream, and is a **prerequisite** to get the above output...

But it seems a start of maybe closing this issue...

So, it is a question of when will that **`issue-396`** branch be available, even for testing... I will try to submit my test code within a week, but that will shortly be interrupted by beginning the process of a 5.2 release... it will certainly be there in 5.3.0, hopefully some time soon... maybe @rtack is working on it too..

Accordingly, adjusting this milestone to 5.3... look forward to comments, feedback, ideas on closing this... thanks...

**Comment by zanona** [comment] 2016-04-09 12:52
Hi @geoffmcl, thanks a lot for your reply on this.
I'm afraid I perhaps didn't explain my case very well, but my concern is only regarding validation where by adding:

```html
<ul>
  {{~it.array :value}}
  <li>{{=value}}</li>{{~}}
</ul>
```

and then `tidy template.html` present a few validation errors such as:

`line 19 column 9 - Warning: missing <li>`

So my intent was to ignore lines that match a specific pattern so the validation still passes under those lines as if they didn't exist.

I have tried with all options you suggested such as `tidy --show-body-only yes template.html` and `tidy --fix-uri no template.html` but I do still receive the warnings about those lines which are not really html?

Thanks again and have a great weekend.

**Comment by geoffmcl** [comment] 2016-04-09 14:37
@zanona seems I did **not** explain well that a **fix** for this only exists in a **test** fork/branch of tidy at the moment... version 5.1.52-test1... @rtack is working on providing a PR for this... @rtack, as @balthisar requested, could you add a normal PR, and I will deal with it...

@zanona you need to wait for that... **or** you could build that **test1** version, by applying the patch shown in #396, **or** clone the [issue-396](https://github.com/rtack/tidy-html5/tree/issue-396) branch from the @rtack fork...

This patch is **nothing** to do with a Jinja template! 

It is merely a patch to allow a `<ul>` element to have 0 or more li children, plus other children... that's all... but this leaves the Jinga template sample code un-touched... well some re-lining and maybe some indenting slightly differently... the important thing is **no warning** about a missing `<li>`, and more importantly, no addition of an implicit `<li>`... in the output...

If the Jinga engine does have problems with the **re-lining and/or indenting**, then this should be another `Pretty Print` issues... and if Jinga has problems with other than the `<ul>` elements, then these should be a new issue...

But if the Jinga engine has no problem with this, then with this **patch**, maybe this issue is, by consequence, closed... we have to wait and see... thanks...

**Comment by rtack** [comment] 2016-04-10 14:58
@geoffmcl pull request is already there https://github.com/htacg/tidy-html5/pull/398

**Comment by geoffmcl** [comment] 2016-04-16 18:29
@zanona that above PR has now been merged to `master`... pull the latest 5.3.1 and give it a try...

As explained, maybe this unrelated `<li>` patch has done something for this issue...

Please check and advise... thanks...

**Comment by zanona** [comment] 2016-04-18 08:42
Thanks a lot @rtack @geoffmcl,
I will test it and let you know in case something unexpected happens.

It looks great though.
One alternative way I found to play nicely with template engines is changing their markers to HTML comments for these sections instead so the below would also be valid without conflicting with the markup:

```html
<ul>
  <!--{{~it.array :value}}-->
  <li>{{=value}}</li>
  <!--{{~}}-->
</ul>
```

**Comment by geoffmcl** [comment] 2017-02-04 16:24
On re-testing this this seems closed in master 5.3.15, so closing this...

Please feel free to re-open, or present a new issue... thanks...

**Closed by geoffmcl** 2017-02-04 16:24 UTC
Labels: Bug, Feature Request

**Comment by slavafomin** [comment] 2017-06-03 17:08
Hello!

Thank you for this great library!

I'm using `gulp-tidy` in order to tidy my HTML templates written in Twig (Jinja2).

However, it messes up URLs with placeholders: `<a href="{{%20confirmationUrl%20}}">`.

The `fixUri: false` options helps.

I'm using `htmltidy 5.2.0`.

**Comment by geoffmcl** [comment] 2017-06-03 18:29
@slavafomin hello back, and thanks for the `thanks`... always appreciated...

I know **nothing** about `gulp-tidy` nor `Twig (Jinja2)`, and in re-reading **all** the above **closed** issue, HTML Tidy is primarily intended for **[X]HTML**... and can **not** get into `Jinja templates` parsing... sorry...

Further, if you are using Tidy `5.2.0`, then it seems some changes that may **assist** in this issue only occurred in `5.3.15`, and later, so perhaps you will get better results using release Tidy `5.4.0`, or **later**...  the latest `next` branch is at `5.5.31`...

So again thanks for your comment, but it is **unclear** what you want Tidy to do **more**... please explain... thanks...
