### ISSUE TITLE
Any Windows Binaries for 5.7.28, just like 5.6?

### ISSUE THREAD

**Issue by kiravi** [htacg/tidy-html5#947] opened 2021-05-11 16:08 UTC
Windows binaries for these would be helpful.

**Comment by balthisar** [comment] 2021-05-12 13:31
We _usually_ only publish binaries for the **master** branch, which is "stable"; and don't even usually publish "releases" of odd minor versions. For example, 5.6 is a release, even minor version, master branch, and 5.7.x isn't stable, off minor version, "next" branch.

I see that 5.7.x was recently released as stable, though, so we probably should put up a Windows binary. @geoffmcl is on sick leave, and I have no idea how to produce a cryptographically signed and verified Windows binary, but I'd welcome someone to produce it for release. I could probably just zip a Windows binary and publish the sha, but doesn't Windows require some sort of valid signature these days?

(FWIW, 5.7.x still isn't stable in the normal sense of the word. It _runs_ in a stable fashion, but what we normally mean is that its API isn't yet stable. Things like enum order can change, etc., and aren't really frozen until locked as a 5.8 release.)

**Comment by tobiastromm** [comment] 2021-05-20 01:56
+1

**Comment by balthisar** [comment] 2021-07-09 16:10
Closing as duplicate of a couple of others. I will commit to automated building of minor releases after 5.8 goes live.

**Closed by balthisar** 2021-07-09 16:10 UTC

**Comment by balthisar** [comment] 2021-07-30 13:43
And, automated builds are now available for `next` branch, as well.

These are Github "pre-release", so you have to look at "Releases" to find them.

Currently whenever the version is bumped, one of the maintainers still has to create the pre-release manually, but when this is done, the builds will attach automatically.
