### ISSUE TITLE
Pushing for full HTML5 support

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#122] opened 2014-08-04 16:10 UTC
Removed this rather broken orignal post, but still 'Pushing for full HTML5 support.

Regards,
Geoff.

**Comment by balthisar** [comment] 2015-01-12 02:34
@geoffmcl, I can't do a PR to your fork, but perhaps you'll take a look at this:

- https://github.com/balthisar/tidy-html5/tree/geoffmcl-restart

It's your fork as ca. November, with several of the PR's in this branch manually merged in, primarily support for all of the vast array of attributes (plus my own PR for a secondary messages callback filter that I need for language localization).

Because so many of the existing PRs are based on the master branch, there were tons and tons of conflicts I had to handle manually.

It's a shame this branch isn't maintained, but as far as I can tell from activity, your fork is a lot more canonical than mine, and it would be good to have many of these PR's merged into a fork with visibility.

**Comment by geoffmcl** [comment] 2015-01-16 19:24
Hi balthisar,

Sorry for the delayed reply but still busy with
some other things for a little longer... but time
for a brief reply...

Wow, it is great to read LOTS of 'tidy' activity ;=))

Yes, after forking and adding what I wanted I did NOT
set up PR's because, quite frankly, nobody seemed
interested ;=(( There were already several outstanding
PR's and issues that did not seem to be getting any
attention...

As soon as I get a chance I will look at your -
   https://github.com/balthisar/tidy-html5/tree/geoffmcl-restart

Now also watching htacg/tidy-html5...

And joined the HTML Tidy Advocacy Community Group right
after I 'joined' W3C, as 'geoffmcl' ;=))

Anyway, great to read lots... be back soonest... obviously
am still very interested in tidy's future...

Regards,
Geoff.

**Comment by balthisar** [comment] 2015-01-19 07:22
Geoff, we all understand time commitments! I'm hopeful that we won't let get things to backlogged anymore. We're still trying to figure out a proper strategy for the outstanding PRs.

Have you run through the regression tests with my fork? It's on my very long to-do list. Given that it includes a good number of the PR's, it would be convenient if we could verify its trustworthiness. (Note, have to remove my private project branding, though!).

**Comment by geoffmcl** [comment] 2015-01-19 13:56
Hi Jim,

My other projects have quietened down so found
some time to devote to tidy ;=))

===
1) Cloned your fork - geoffmcl-restart branch

One item needed was to add a va_copy(a,b) to
compile in windows... in include\platform.h
added in the windows section -

#ifndef va_copy
#define va_copy(dest, src) (dest = src)
#endif

===
2) Merged yours with my tidy-fork... quite a
number of conflicts but ALL easily resolved ;=))

(i) The biggest one was src/attrdict.c - not
sure why really but git merge always gets broken
up over lots of space changes...

You had carefully moved every existing definition
out 4 spaces to match the new largest attribute
TidyAttr_ARIA_ACTIVEDESCENDANT, lot of good work,
but git gets confused... and say both modified:

On carefully checking this was NOT true, and
I was able to just copy yours over mine, and
all is happy.

(ii) The only other conflicts were all in the
'build' files.

I have decided to go 100% CMake since it generates
native make files for just about any desired
system, so had DELETED ALL the old make, starting
with the root Makefile, then in build directory,
deleted dirs gmake, gnuauto, msvc2010, rpm...

And fixed the README.md and README.html to match...

When I deleted all these same things in your
clone, the merge went very smoothly, except for
(i) above, but that is just a copy.

===
3) After a windows compile check, and ran a few
tests, mainly on ARIA, but included other things,
did a push to my fork... to course to a
geoffmcl-restart branch at this time...

And did a compile check in my Ubuntu 14.04 linux...
NO PROBLEMS ;=))

===
4) Began to attack the issues open against my
fork, and was able to close a number (3 or 4) with
mostly simple fixes...

The most difficult is one concerning treating
ids as case sensitive, since we have to retain
the warnings/errors for html4 while removing
them if html5...

But have a good trace on this, and should be
able to close it soon also...

Also picked up one issue from htacg/tidy-html5
which was able to close changing just one word ;=))

For <script src="..." async>, change CH_PCDATA
to CH_BOOL for TidyAttr_ASYNC...

Started to look at some others... there are 64...

And looking at the 14 PRs, but most of which would
NOT be needed by my current tidy_fork/geoffmcl-restart
branch...

===
5) Regression test

I certainly agree this is becoming IMPORTANT ;=()

To me it is important that tidy5 can do ALL that
the previous tidy did without problems, while
still being able to handle all the new and changed
stuff from HTML5...

I have had it as a note to myself, as Issue #1,
opened 6 Aug 2014, so it is about time I got
around to it ;=))

Will certainly try to deal with that during this
week, or soonest...

===
6) Where to next?

(a) At this time htacg/tidy-html5 now seems so far
behind ;=(( and no cmake!

(b) I could easily bring your balthisar/tidy-html5 up
to mine, and maybe we could continue to keep them
in sync...

Of course until I see a direction emerging I will
continue to 'fix', 'update', 'test' my tidy-fork...

What is your idea?

Regards,
Geoff.

**Comment by balthisar** [comment] 2015-01-20 02:41
@geoffmcl, direction should be coming soon. Don't despair again.

**Comment by geoffmcl** [comment] 2015-01-24 17:06
So have pushed develop-500 branch to this repo, and would really appreciate any testing and reviewing of this branch. $ git checkout develop-500

This should make my tidy-fork redundant...

Will try to add the infrastructure label to this, since it contains a lot of discussion... and have also posted a message to -
https://lists.w3.org/Archives/Public/public-htacg/2015Jan/thread.html
where some of this dicussion could continue...

And hope any, all of you can help testing this latest... Thanks...

**Comment by skynet** [comment] 2015-01-24 18:18
:+1:

**Comment by balthisar** [comment] 2015-02-01 07:59
I will close this issue as "overly broad." :-)

**Closed by balthisar** 2015-02-01 07:59 UTC
Labels: Infrastructure
