### ISSUE TITLE
Inconsistent stripping of white space at the start of the value of href attribute?

### ISSUE THREAD

**Issue by CMB** [htacg/tidy-html5#345] opened 2016-01-08 23:34 UTC
Sometimes Tidy strips all the leading whitespace from the value of
href, and other times, it URL encodes it.
Here's a test case, a result, and an expected output:
http://the-brannons.com/test.html
http://the-brannons.com/result.html
http://the-brannons.com/expected.html

**Comment by geoffmcl** [comment] 2016-01-09 18:28
@CMB yes, I can see the problem... thanks...

Will look at a fix soonest...

**Comment by geoffmcl** [comment] 2016-01-11 20:03
@CMD wow, this problem dates back to the first Tidy... in other words it is not a new **`bug`** that has crept in... although there has been a small change over time...

For the inputs -

```
<a href=" https://netflix.com/">Netflix</a>
```

Previous Tidy would output -

```
<a href=" https://netflix.com/">Netflix</a>
```

That is an unencoded space, and it seems the browsers I tried have no problem with this... they remove the space, and understand, action, this href...

But somewhere along the road, Tidy started escaping the space! New output -

```
<a href="%20https://netflix.com/">Netflix</a>
```

The problem is that seems to really mess up a browser, and leads to a 404. The browser tries to load a local file...

So this is definitely a **`bug`** that needs to be squashed, but since it has existed for a long time may take some time to find and fix.

And then there is the question, what should the fix be? 

It seem the simplest hack would be to avoid encoding any leading space in a href value. That would get us back to what all previous tidys did. Will try to track back to when that encoding happened, and why...

But is that a complete fix? Would there **ever** be any case for maintaining this leading space at all? Could it **always** just be dropped? It seems to me the answer is **yes**!

As always, look forward to ideas, comments, patches or a PR...

**Comment by CMB** [comment] 2016-01-13 13:13
@geoffmcl It's a hard call.  I don't see why you'd ever want leading
space in an href value, so stripping it sounds good.  But on the other
hand, aren't values of attributes generally supposed to be treated as
opaque?  I.E., pass them through without modification?  Both approaches
sound fine, but I'm not sure which is the correct one.

**Comment by zcorpan** [comment] 2016-01-21 08:25
Leading and trailing [space characters](https://html.spec.whatwg.org/multipage/infrastructure.html#space-character) are allowed around URLs and will be trimmed by the browser. So leaving it alone is OK. But trimming in Tidy seems OK also.

**Comment by geoffmcl** [comment] 2016-01-24 16:17
@CMB, @zcorpan thanks for your further comments...

In researching what are valid HREF characters, see #352, also saw several times that leading/trailing spaces are ok, so for the moment will search for a hack to at least **not** escape them...

**Comment by geoffmcl** [comment] 2016-02-01 19:15
@CMB, @zcorpan in searching for a fix for this it turned out just as easy to discard the leading space as to not escape it...

Please pull master 5.1.36 or plus and test if you get a chance... thanks...

**Comment by zcorpan** [comment] 2016-02-02 00:16
Commented on the diff at https://github.com/htacg/tidy-html5/commit/7d0d8a853a01004572d27e47b5c1146361816271#commitcomment-15815434

**Comment by geoffmcl** [comment] 2016-02-02 01:30
@zcorpan see [comment](https://github.com/htacg/tidy-html5/commit/7d0d8a853a01004572d27e47b5c1146361816271#commitcomment-15816559) on commit...

**Comment by CMB** [comment] 2016-02-04 22:28
@geoffmcl Pulled and tested.  This looks good to me.  I'm fine with
closing this issue if you like.

Thank you!

**Comment by geoffmcl** [comment] 2016-02-13 16:52
No further comment for over a week so closing this for now...

Please feel free to re-open or post another issue... thanks...

**Closed by geoffmcl** 2016-02-13 16:52 UTC
Labels: Bug
