### ISSUE TITLE
Man page has repeated sections

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#469] opened 2016-12-04 18:48 UTC
```
$ man tidy|col -b|perl -we '
while (<>) {
    next unless /^[[:upper:]]/;
    $h{$_}++;
}

for ( keys %h ) { print "$h{$_} $_" if $h{$_} > 1 }
'
2 OPTIONS
2 DESCRIPTION
2 SYNOPSIS
```

**Comment by geoffmcl** [comment] 2016-12-05 18:45
@jidanni thanks for your issue...

Now I know very little about what is supposed to be in the tidy.1 man page, its format, but those headers also appear twice in the `man/tidy1.xsl.in` in the source, used to generate the man page, using `xsltproc` ... 

In other words, it does appear quite **deliberate** repetition! Is there something wrong with this?

Will leave it to others, who know about man page generation and format to comment... thanks...

**Comment by jidanni** [comment] 2016-12-08 08:29
Find me one other man page in the world with repeated sections.

And how, when they are converted to HTML, are they supposed to link
to a unique href="#synopsis" ?

And if your professor asks you for a synopsis, do you give him two?

He asked you for a synopsis, i.e., nutshell.

**Comment by eric-brechemier** [comment] 2016-12-08 09:23
For comparison, the issue is not present in the Mac version of tidy:

```
$ tidy --version
HTML Tidy for Mac OS X released on 31 October 2006 - Apple Inc. build 15.17

$ man tidy | grep '^[A-Z]'
TIDY(1)                                                                TIDY(1)
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
USAGE
ENVIRONMENT
EXIT STATUS
SEE ALSO
AUTHORS
```

**Comment by jidanni** [comment] 2016-12-08 09:37
OK must be a Debian bug.
Created http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847439 .

**Comment by eric-brechemier** [comment] 2016-12-08 09:49
@jidanni That's not what I meant. Apple has forked the [legacy version of Tidy](http://tidy.sourceforge.net/). And the issue is not present in [their version](https://opensource.apple.com/source/tidy/).

Reference:
https://www.apple.com/opensource/

Now, I wonder what causes this behavior.

Here is the `tidy1.xsl` file in the Apple version that I ran:
https://opensource.apple.com/source/tidy/tidy-15.17/tidy/htmldoc/tidy1.xsl

The version of `tidy1.xsl` in this project:
https://raw.githubusercontent.com/htacg/tidy-html5/master/man/tidy1.xsl.in

**Comment by jidanni** [comment] 2016-12-08 09:53
OK I'll let you guys take care of it.

**Comment by eric-brechemier** [comment] 2016-12-08 11:24
The end of the man page of the Mac version (`SEE ALSO` and `AUTHORS`) does not match the source code in the style sheet. It must have been post-processed, removing the extra sections (`DETAILED CONFIGURATION OPTIONS`, `SYNOPSIS`, `WARNING`, `DESCRIPTION`).

As seen [in this HTML version of the legacy documentation](http://tidy.sourceforge.net/docs/tidy%5Fman.html) the extra sections were already present.

**Comment by geoffmcl** [comment] 2016-12-10 17:50
@jidanni, yes, as indicated by @eric-brechemier, these `duplicated` **sections** have been there for a long, **long**, time... since circa May 2005... and are thus also present in most `Apple` forked sources... including the build 15.17 mentioned... thus if **not** in any particular generated tidy.1 doc, must be due to some additional post processing, not passed back to us...

Of course, `time` does **not** necessarily make them right, but for what ever reason, the file was split into two parts with this Mon May 2 16:12:52 2005 UTC commit, in the historic cvs repo - http://tidy.cvs.sourceforge.net/viewvc/tidy/tidy/htmldoc/tidy1.xsl?annotate=1.2 - and has basically remained that way over the 11 years since... to the current, active source - https://github.com/htacg/tidy-html5/blob/master/man/tidy1.xsl.in - in the github repo...

It does seem they wanted to separately list command line options that begin with a single `-`, from those that begin with `--`, which can also be placed in a **config** file... So it is **not** a simple matter to just delete one or the other... both `option types` **must** be there...

And if I read @eric-brechemier correctly, and he has found a tidy.1 doc without `duplicates` may mean that particular tidy.1 doc only gives information about one or the other type of options, which would also be very **bad**...

So we need help from someone who understands the tidy.1 doc generation from the `.xsl` file, using tidy's own xml outputs, and `xsltproc`, to potentially **fix** the situation, and still keep **all** the information... 

I can see the two forms of `SYNOPSIS` could be combined, and the seconds type, the `--` config options, be called say `OPTIONS2`, and `DESCRIPTION2`... or something... thanks...

**Comment by eric-brechemier** [comment] 2016-12-13 10:03
> And if I read @eric-brechemier correctly, and he has found a tidy.1 doc without duplicates may mean that particular tidy.1 doc only gives information about one or the other type of options, which would also be very bad...

Correct. Only the single `-` options are described, not the `--` dash options, in the version advertised as:

```
$ tidy --version
HTML Tidy for Mac OS X released on 31 October 2006 - Apple Inc. build 15.17
```

> So we need help from someone who understands the tidy.1 doc generation from the .xsl file, using tidy's own xml outputs, and xsltproc, to potentially fix the situation, and still keep all the information...

@geoffmcl I can help with that. Merging the description of both types of options seems the way to go. I'll make a first pass by the end of the week with some kind of diff to visualize the changes in generated man pages.

**Comment by geoffmcl** [comment] 2016-12-16 19:00
@eric-brechemier look forward to what you can do to **fix** this situation... thanks...

**Comment by eric-brechemier** [comment] 2016-12-18 22:22
@geoffmcl I have opened a pull request for preliminary review: https://github.com/htacg/tidy-html5/pull/473.
Can you take a look and confirm whether I am headed in the right direction?

**Comment by geoffmcl** [comment] 2016-12-20 19:11
@jidanni @eric-brechemier - see #473 for further comments on this, and a WIP PR... thanks...

**Comment by balthisar** [comment] 2017-02-09 13:58
Given that this is in master now, I'll close this issue. Feel free to reopen this is I've missed something.

**Closed by balthisar** 2017-02-09 13:58 UTC
Labels: Docs, Help Needed, Technical Support
