### ISSUE TITLE
Text within div which was not bold is bold after parsing.

### ISSUE THREAD

**Issue by NaziaMuhaimuna** [htacg/tidy-html5#397] opened 2016-04-07 13:37 UTC
I have an issue when span element has a div within and trying to parse it using tidy.
• Tidy is trying to wrap the elements by closing the span before start of the div and creating a new span inside div. 
• Before tidy fix , div style is applied to the text inside it. 
• But tidy creates a span along with the inline styles and if any bold, italic or underline tags exist inside the div.
• This being the reason all the text is bold which is not what is expected.

Sample html and tidy parsed html are as below:

Sample Html :

```
<span>
<b>Test Tidy
<div style='font-weight: normal'>Do something</div>
</b>
</span>
```

Tidy parsed html

```
<body>
  <span><b>Test Tidy</b></span>
  <div style='font-weight: normal'>
    <span><b>Do something</b></span>
  </div>
</body>
```

**Comment by geoffmcl** [comment] 2016-04-08 13:19
@NaziaMuhaimuna tidy has been doing this `propagation` of certain `representational` elements since the beginning of time! From the first release, tidy-2000; through the last cvs release, tidy-2009; right up to now, tidy-5.3.0 2016... it still does it...

Now the fact that tidy has been doing this for over 16+ years does **not** make it totally right, but to **fix** it requires quite a fundamental change in the current tidy parsing...

It is agreed, the current tidied version will appear different in a browser, and this is certainly one of the things tidy tries to avoid... that is the tidied document should appear the **same** as the input in cross-browser testing...

Clearly your sample shows this visual difference, but I wonder how many other cases there are where this propagation has helped... need to do some testing on this...

You can see the process in the tidy node tree after parsing... indent is significant...

````
   StartTag span
    StartTag b
     Text   (9) 'Test Tidy'
   StartTag div   style="font-weight: normal"
    StartTag span implicit
     StartTag b implicit
      Text   (12) 'Do something'
````

So you can see the problem is already there... on getting the `<div...>`, tidy closes the `<b>` and the `<span>`, but stores them in a stack, then implicitly re-opens them inside the div...

If you extend your sample, and add another p after the div, you would see the same propagation of span and b -

Input: 

````html
<span>
<b>Test Tidy
<div style='font-weight: normal'>Do something</div>
<p>Para 2</p>
</b>
</span>
````

Output:

````html
<span><b>Test Tidy</b></span>
<div style='font-weight: normal'><span><b>Do
something</b></span></div>
<p><span><b>Para 2</b></span></p>
````

The Tree:

````
   StartTag span
    StartTag b
     Text   (9) 'Test Tidy'
   StartTag div   style="font-weight: normal"
    StartTag span implicit
     StartTag b implicit
      Text   (12) 'Do something'
   StartTag p
    StartTag span implicit
     StartTag b implicit
      Text   (6) 'Para 2'
````

Here the propagation into the p correctly shows bold **Para 2**, as it does in a browser... so it is necessary and correct...

As stated, in this div case, it would be better if tidy did **not** pull the span and b into the div, but as indicated need to do some more tests, maybe even experimenting with disabling this stack propagation, at least for a div that has style... or for other criteria...

Is there something special about a div with **style**? Or some other reason to not do it in this case...

At this time I am treating this as a feature request, rather than a bug, since it is what tidy is presently coded to do...

Comments, ideas, even a PR would be tested, so help would be **much** appreciated... thanks

**Comment by NaziaMuhaimuna** [comment] 2016-04-11 17:21
Thank you for detailed explanation of the current behavior of tidy !!!
I have a few queries:
- We have a large amount of legacy HTML that we would like to run HTML Tidy against to identify examples that fit similar patterns.Can you assist us in modifying tidy to generate an error when this pattern is found? 
- Do you have any test automation used to validate the HTML and the rendering of the HTML?
- Is there any plug-in or extension architectures in HTML Tidy that we could leverage to address this issue ?
- I have looked through all the config options provided @ http://tidy.sourceforge.net/docs/quickref.html. Is there any other specific documentation on the HTML Tidy implementation so that we can better understand how it works?

Thank you for your support and waiting for reply.

**Comment by geoffmcl** [comment] 2016-04-11 19:15
@NaziaMuhaimuna concerning your questions...

 - legacy HTML - modify console/tidy.c, and the output buffer can be scanned for anything...
 - test Tidy - see https://github.com/htacg/tidy-html5-tests - a WIP - automated yes/no - 
 - libTidy is a plug-in, like plugs into Notepad++ say, see API http://api.html-tidy.org/
 - config options and API docs aside, there are no `special` documents... do not understand this...
 
The power, versitility of this library can be a plus to any project dealing with html...

PS: We keep that tidy.sf legacy site, but maybe need to update some more links - https://github.com/htacg/tidy.sf.net.legacy -  but the main site is for sure http://www.html-tidy.org/

**Comment by geoffmcl** [comment] 2017-02-28 18:02
As we are about to release **5.4**, and there has been no work done to date on this issue, or comments, in nearly a year, am closing this.

Another option would be keep it open, but to move it to `next` **5.5**, but...

Please feel free to re-open, or file a new issue... thanks...

**Closed by geoffmcl** 2017-02-28 18:02 UTC
Labels: Feature Request
