### ISSUE TITLE
Incorrect indentation for script tag

### ISSUE THREAD

**Issue by sjmulder** [htacg/tidy-html5#56] opened 2012-07-12 10:18 UTC
Input:

    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <title></title>
        </head>
        <body>
            <p>Paragraph 1</p>
            <p>Paragraph 2</p>
            <script>
                function() {
                    return 'Hello, World!';
                }
            </script>
            <script src="foo.js"></script>
        </body>
    </html>

Command (no config file):

    tidy --indent 1 --indent-spaces 4 input.html

Output:

    <!DOCTYPE html>
    <html>
        <head>
            <meta name="generator" content=
            "HTML Tidy for HTML5 (experimental) for Mac OS X https://github.com/w3c/tidy-html5/tree/68a9e74">
            <meta charset="utf-8">
            <title></title>
        </head>
        <body>
            <p>
                Paragraph 1
            </p>
            <p>
                Paragraph 2
            </p><script>
        function() {
                    return 'Hello, World!';
                }
            </script> <script src="foo.js">
    </script>
        </body>
    </html>

Issues:
* There is no newline between the closing tag for paragraph 2 and the opening script tag
* The script tag is closed on the wrong line

**Comment by geoffmcl** [comment] 2015-01-25 18:58
Just for information the latest development code is in branch develop-500. You should do -
$ git checkout develop-500
and test that...

BUT, as indicated this is a known issue from the last 2009 Tidy release, AND still exists in the current code... That is Tidy has always placed the openning script tag almost immediately following the last closing tag... 

Thank you for reminding me of this, and I will keep it in mind while squashing more pressing bugs... And will look at some of the fixes suggested... You never know... maybe one day ;=))

**Comment by geoffmcl** [comment] 2015-01-25 20:08
Well, looking at a potential fix by clarkewd gave me a quick idea - thanks...
Please checkout develop-500 and check, especially for any other regressions...
Look forward to your furhter reports, or this closed if good ;=))

**Comment by geoffmcl** [comment] 2015-01-26 14:44
Found a small regression, but moving my patch down seems to have fixed that...
Hope you get a chance to checkout develop-500, build, test and report... thanks...

**Comment by balthisar** [comment] 2015-02-01 09:50
Fixed in develop-500. Please feel free to re-open this if you still have a problem. Thanks!

**Closed by balthisar** 2015-02-01 09:50 UTC
Labels: Feature

**Comment by burtonsys** [comment] 2016-01-07 13:17
Any idea where to find a windows binary for this?  Or, better yet, a DLL build, for Notepad++?

`C:\Program Files (x86)\Notepad++\plugins\Tidy2.dll`

**Comment by balthisar** [comment] 2016-01-07 13:53
Windows binaries are on http://binaries.html-tidy.org.
You'll have to contact the author of the Notepad++ plugin for that plugin support, I'm afraid.

**Comment by geoffmcl** [comment] 2016-01-07 14:06
Since the x86 indicates 32-bit, then download the win32 zip... it contains the DLL...

I guess you could just copy and rename it... When I click `TextFX HTML Tidy -> About Tidy` in my v5.9 (UNICODE) npp, it says can not find `PF32\plugins\Config\tidy\libTidy.dll`, but I have never tried to fix it, or use the html functions, so not sure...

As suggested Notepad++ plugin support could give you more...

**Comment by burtonsys** [comment] 2016-01-07 14:34
Thank you!

I tried replacing the Tidy2.dll with a renamed Tidy.dll from the 32-bit Windows binary, `tidy-5.1.25-win32.zip`. But when I started Notepad++ it reported:

<pre>
---------------------------
C:\Program Files (x86)\Notepad++\plugins\Tidy2.dll
---------------------------
This ANSI plugin is not compatible with your Unicode Notepad++.

This plugin is not compatible with current version of Notepad++.

Do you want to remove this plugin from plugins directory to prevent this message from the next launch time?
---------------------------
Yes   No   
---------------------------`
</pre>

Oh, well. The command-line version works, and it is much improved over the version which is integrated into the Notepad++ Tidy2 PlugIn.

The command-line version is still not perfect, IMO, because it always puts the `</script>` tag on a line by itself, even when it immediately follows a `<script...>` tag that pulls in javascript from a separate file. But it ii certainly much better than the version which is integrated into the NPP Tidy2 PlugIn.

**Comment by geoffmcl** [comment] 2016-01-07 14:51
Hmmm, I wonder what `compatible` means here? Maybe it needs a UNICODE version of the library??

At present the strings in tidy are not set up for a UNICODE compile... IIRC they must be all put in a `_T("Hello")` macro, or something like that... and the compile does the converion... The tidy strings are getting attention in #336, and maybe a unicode version would be possible with that...

But maybe UNICODE is not the `compatibility` problem... need to ask Notepad++...

And yes, there are always so many preferences for `Pretty Printing` ... but if you have the time, fork, build, modify, and present your suggestions... they are always welcome... thanks...
