### ISSUE TITLE
Tidy does not support partial files

### ISSUE THREAD

**Issue by MarkLodato** [htacg/tidy-html5#72] opened 2012-11-09 14:54 UTC
Tidy currently has no way of supporting partials HTML files, as a so often used with templating systems.    For example, if I have a perfectly valid snippet of  HTML, "tidy -e" returns the following:

    line 4 column 1 - Warning: missing <!DOCTYPE> declaration
    line 4 column 1 - Warning: inserting implicit <body>
    line 4 column 1 - Warning: inserting missing 'title' element

Could you add an option to allow parsing (or at least linting) of partial HTML files?

**Comment by balthisar** [comment] 2015-02-01 09:31
>You can use tidy --show-body-only 1 file.html to disable the full document outline but there seems to be a bug at the moment causing it to show the warnings even when they're not relevant.

Confirmed. Will have a look.

**Comment by balthisar** [comment] 2015-02-01 13:17
Fixed in develop-500.

Although I'm closing the issue, I would appreciate someone more familiar with Tidy's guts to review the implementation of the bug fix.

**Closed by balthisar** 2015-02-01 13:17 UTC
Labels: Bug Confirmed

**Comment by geoffmcl** [comment] 2015-02-05 20:36
Have been reviewing the test list of tidy, and find this fix now causes a FAIL in alltest.cmd for test 795643-1, and maybe others...

In the test list, testcases.txt, is listed as -
795643-1 1
That means one expects tidy to exit with a warning, but with the current fix it now exits 0!

The test is on a fragment, input\in_795643-1.html
````
<p>Hi</p>
````

And the config is given as, input\cfg_795643-1.txt -
show-body-only: auto

The history of this option is given in -
https://sourceforge.net/p/tidy/feature-requests/184/
Arnaud added this case -
in_795643-1.html 1.1 7 years arnaud02 http://tidy.sf.net/issue/795643 - show-body-only as AutoBool

Thus this test suggests a warning SHOULD be issue for 'auto'.

The present patch only issues a warning if --show-body-only no

I now think the macro should be -
#define showingBodyOnly(doc) \
 (cfgAutoBool(doc,TidyBodyOnly) == TidyYesState) ? yes : no
 
Suggested patch :-
````
diff --git a/src/parser.c b/src/parser.c
index 32dfaaa..ec0a950 100644
--- a/src/parser.c
+++ b/src/parser.c
@@ -4504,27 +4504,9 @@ static void AttributeChecks(TidyDocImpl* doc, Node* node)
 }
 
 /*
-  Need to know to avoid error-reporting
+  Issue #72 - Need to know to avoid error-reporting - no warning only if --show-body-only yes
  */
-Bool showingBodyOnly( TidyDocImpl* doc)
-{
-    Node* node;
-
-    TidyTriState bodyOnly = doc->config.value[TidyBodyOnly].v;
-
-    switch( bodyOnly )
-    {
-        case TidyNoState:
-            return no;
-        case TidyYesState:
-            return yes;
-        default:
-            node = TY_(FindBody)( doc );
-            if (node && node->implicit )
-                return yes;
-    }
-    return yes;
-}
+#define showingBodyOnly(doc) (cfgAutoBool(doc,TidyBodyOnly) == TidyYesState) ? yes : no
 
 /*
   HTML is the top level element
````

Can I push this? 

After which tidy passes test 795643-1, and still issues no warning if --show-body-only yes, which seems to be the essence of this issue... so it remains closed...
