### ISSUE TITLE
space stripping between tags

### ISSUE THREAD

**Issue by dynamicplus** [htacg/tidy-html5#102] opened 2013-08-27 13:12 UTC
This should be legal:
hello<a href="#"> my</a> world!

but produces
hello<a href="#">my</a> world!

removing space
after anchor opening tag

**Comment by geoffmcl** [comment] 2015-01-29 17:28
Thanks for your post...

As you may know the current development branch is develop-500
$ git checkout develop-500
Issues can ONLY be tested against this dev5 branch...

But to confirm this was certainly a regression BUG ;=((

Tidy 'knew' to move a leading space from the a text, if any, and 
add it as a trailing space to the previous text, if none... quite a neat 
trick to preserve the browser view, while still removing spaces 
from text in general...

It was caused when the 'parser' for a TidyTag_A tag was changed from 
TY_(ParseInline) to TY_(ParseBlock). I have now changed it back to 
TY_(ParseInline), and the problem is FIXED.

This change was inherited during the merge of tidy-fork, thus occurred 
sometime deep in the tidy-fork history, but was unable to track down WHO or 
WHY this was changed, even after reviewing the full history log, except to 
know that I did not change it...

As always, one hopes it does not have other consequences, but that is 
what all this testing, testing, testing is about... 

Have bump the version to 4.9.2 for this important change. And moved this 
version out to a version.txt file... for easy incrementing...

If you get a chance hope you can pull this develop-500 branch, and test 
again, and if ok, close this issue.

Thanks again...

**Comment by balthisar** [comment] 2015-02-01 08:46
Will close. Fixed on current develop-500.

**Closed by balthisar** 2015-02-01 08:46 UTC
Labels: Bug Confirmed
