### ISSUE TITLE
Tidy reading default configuration file even if different config file specified in command line

### ISSUE THREAD

**Issue by AnrDaemon** [htacg/tidy-html5#555] opened 2017-05-14 00:36 UTC
I just stumbled upon this highly undesirable and unexpected behavior.
Normally, when application have a switch to explicitly specify a configuration file to read from, it will ONLY read configuration from that file and from environment (commandline/envvars).
Contrary to this, Tidy will always read default configuration file specified in `$HTML_TIDY`, and even complain loudly if it is missing.

**Comment by geoffmcl** [comment] 2017-05-14 01:55
@AnrDaemon thank you for your issue...

> I just stumbled upon this highly undesirable and unexpected behavior.

Not sure I agree with your assessment here!

If **you** go to the trouble of setting the unique ENV variable `$HTML_TIDY`, do you not want to know that this **FAILED**? I would... You will note it does **not** effect what tidy later does...

Tidy, like several other projects I work with, tests and reads `$HTML_TIDY`, or their equivalent ENV `rc` type file, if they have one and if given, **before** the command line is read, so that any command line options, and/or `-config <file>` option, can override it...

So to me this seems **normal**... very reasonable...

Just remove the ENV `$HTML_TIDY` if you do **not** want this noise... or do just `$ touch $HTML_TIDY`... or something...

My first assessment here is `Won't fix`, but would listen to reasonable feedback otherwise... thanks...

**Comment by AnrDaemon** [comment] 2017-05-14 21:19
> If you go to the trouble of setting the unique ENV variable  $HTML_TIDY , do you not want to know that this FAILED?

Only if that's the only place it is trying to look for configuration file.

> Tidy, like several other projects I work with, tests and reads  $HTML_TIDY , or their equivalent ENV  rc  type file, if they have one and if given, before the command line is read

I've never seen such project. Name me a few.
All programs I've worked with, if supports configuration file specified in command line, will not try to override it.

**Comment by balthisar** [comment] 2017-05-14 22:47
If I'm understanding the issue clearly, @AnrDaemon expects specifying a `--config` on the command line to override the rc file (which by default isn't supported without a build switch) _and_ to override any config file pointed to by `$HTML_TIDY` in the environment.

If that's my understanding, then this seems reasonable. In fact, I'll have to jump through the code to see what happens here. If there's a config file (from any source), are `--` parameters honored? I think they should be, to supplement/override the config file. If there's an rc or `$HTML_TIDY` path set, then I agree that specifying a config file should override the pre-set file.

If, though, you _do_ specify `$HTML_TIDY` without a `--config` file, then I agree that Tidy should complain loudly.

I don't plan any action yet, but would like to understand if I understand the issue correctly, and then collect consensus of whether Tidy _should_ behave differently or not. What would a reasonable man on the street expect?

**Comment by AnrDaemon** [comment] 2017-05-15 02:36
> specifying a  `--config`  on the command line

It's `-config` but othervise correct.

> the rc file (which by default isn't supported without a build switch)

Didn't know there's such a switch. Was always my presumption that it is controlled by `$HTML_TIDY` env. var.

**Comment by geoffmcl** [comment] 2017-05-15 14:23
@AnrDaemon, @balthisar well tidy's order of reading configuration, in the [code](https://github.com/htacg/tidy-html5/blob/next/console/tidy.c#L1938) is -

 1. TIDY_CONFIG_FILE, if defined during the compile.
 2. ENV HTML_TIDY, if exists, **OR**
 3. TIDY_USER_CONFIG_FILE, if defined during the compile.
 4. Command line options, including `-config <file>`
 
See the file [tidyplatform.h](https://github.com/htacg/tidy-html5/blob/next/include/tidyplatform.h#L20) for sample suggestions. So 1 and 3 can be defined in there by uncommenting appropriately, **or** by adding such a definition to **cmake**, like `-DTIDY_CONFIG_FILE=/path/to/file`.

In each case 1..3, if the reading of the specified file fails, then a `TC_MAIN_ERROR_LOAD_CONFIG` message will be sent directly to `errout`. Note this failure is **not** added to `warning` or `error` count... it is informational only...

So **for sure** a `-config <file>`, on the command line, or any other options like `--show-info no` **will** override anything read from 1, 2 or 3, if specificied/defined... and again tidy will report `Config: Can't open "notexist.txt"`, but this will **not** be added to the `warning` or `error` count shown...

Although I do remember some projects that use ENV variables, like say OSG library, to control various things, not exactly a `config` type file, but projects like FlightGear.org/fgfs read a `$HOME/.fgfs.rc` or the like, before they parse the command line... and in the number of `.dirs` in `$HOME` I am sure there are some others...

Likewise for Tidy, command line options, and indeed a `-config <file>`, overrides anything read from 1..3, if given, if they exist, and contain valid options... 

I regularly use the ENV `HTML_TIDY=def.conf`, containing some of my `favorite` options, knowing that I can override these later on the command line, or in another `-config <file>`...

So what exactly is the issue? Maybe I do **not** understand something? Is it just the `errout` warnings, even if later options and/or a `-config <file>` given? Thanks...

**Comment by AnrDaemon** [comment] 2017-05-15 16:07
The exact issue is that tidy reads ALL config files. Which is, for me, unexpected.
I don't know what "fgfs" is, but postfix, nginx, apache, dovecot, mysql - all honor config file given in commandline options and don't try to steer away from it to other places.
In case you need to only override SOME of the configuration options, there's f.e. --defaults-extra-file= (for mysql), which explicitly allows for reading of default configuration files before parsing "extra" options.

**Comment by geoffmcl** [comment] 2017-05-15 18:16
@AnrDaemon thanks for the further explanation... 

> The exact issue is that tidy reads ALL config files.

Well, to be fair, Tidy only reads **config** files it is **given** ;=)) Not exactly **ALL**...

As enumerated, 1. and 3. need to be compiled in! If you want you can build a custom version of tidy to always get the **config** from a specific file you name, and tidy will warn you if it can not be found... 

Likewise for 2. ENV `HTML_TIDY`. And note it will override 3.! Tidy can **not** read it if the environment variable does **not** exist... just remove it... or create a blank file...

Tidy is a command line app, so to simplify life, and not having to always type in a **big** command line, it provides a **few** ways config information can be given...

First tidy has a **default** for every config item. To **see** the default, use `-show-config`. It will output a complete list, adding type and current value. This is helpful, in that you **only** need to specify those that you want to **change**...

And the option `-xml-confg` will output a fuller XML version, including default, description, etc... if fact this output is used to generate the `man tidy` pages...

> ... all honor config file given in commandline options

So does tidy! It 100% honors options given on the command line, and that includes a `-config <file>` option... What suggests otherwise?

> and don't try to steer away from it to other places.

Now maybe our documentation does **not** fully, clearly spell out, that the configs given are read in the order 1,2,3,4, with the command line overriding **all** others, if any given... but the `man tidy` does seem quite clear -

```
ENVIRONMENT
       HTML_TIDY
              Name of the default configuration file.  This should be an absolute path, since you will
              probably invoke tidy from different directories.  The value of HTML_TIDY will be parsed after
              the compiled-in default (defined with -DTIDY_CONFIG_FILE), but before any of the files
              specified using -config.
```

I am sure we would accept some improvement in the wording... maybe it should make it clear that tidy will warn if it fails to find such a declared file... but it can be a blank file... and maybe **add** after `using -config`, "which will **override** any and all previous"... 

Since Tidy accepts multiple input files on the command line, as the `SYNOPSIS` indicates, you can have -

```
$ tidy -config conf1.txt in1.html -config conf2.txt in2.html etc etc...
```

So while I read, this seems **unexpected**, for you, it is entirely **expected** by me... 

In Windows, where I work mostly, we do not have a `tradition` for this `rc` type file, but it is common to have the ability to use what is sometimes called a `response` file... and tidy's config file system is exactly like that... **very useful**...

So my question remains, what exactly do you see as a problem here?

If you are sort of suggesting, if the user sets a **bad** ENV `HTML_TIDY=missing.txt`, tidy should hold off on a warning until it has fully checked the command line, or something... that seems very cumbersome... what about if there is no specific `-config file` given, the user chooses all the `--option yes/no` form, or even **accepts** all the defaults and has no options on the command line...

Further we could have a special message for `HTML_TIDY` like `Config: Can't open 'missing.txt', given in HTML_TIDY, but do not be concerned! Tidy has an internal default configuration that will be used, **and** you can specify a valid **-config file** later on the command line`. Would this get over the idea the user is being **steered** away? or something...

One idea I have had for a long time, and that is tidy should abort in this case. My general idea is that if a config item **fails** in some way, tidy should not continue with possibly an unintended configuration... but have always held off on this `Feature Request`...

Maybe we should add a compile option, to compile out support for `HTML_TIDY`, if desired... but as far as I can see it has been part of tidy for the last 17 years, including the `Can't open <file>` message...

So, again, just trying very hard to understand what do you **expect** ;=)) thanks...

At this stage, other than the above message enhancements, always an ongoing WIP, I see no problem in tidy code, and do **not** think it should be changed...

**Comment by AnrDaemon** [comment] 2017-05-16 11:44
Ok, you don't want to understand. Got it.

**Comment by balthisar** [comment] 2017-05-16 11:47
@AnrDaemon, we're trying to understand it, but can you please leave more than one-sentence replies? Can you give a very specific example? We think things are working properly, and you're _not_ helping us understand what, exactly, the issue is. Pretend we're stupid, write more than one sentence, and help us understand, m'kay?

**Comment by AnrDaemon** [comment] 2017-05-16 20:32
Very specific example?
Define a server in default nginx config then feed it a different config with a different server definition via commandline option.
Following Tidy logic, both configs have to be merged, exposing both servers.

**Comment by geoffmcl** [comment] 2017-05-17 02:04
@AnrDaemon, not sure why I bother since you suggest I **don't want to understand**... but stupid me!, I really do **try**... with every, and **all** issues raised... thanks @balthisar for your comments...

First Tidy is **not** a `sever`, running **all** the time, and it has absolutely **no** default configuration file, like `/etc/nginx/nginx.conf`, unless you choose to compile in one, or define one in ENV `HTML_TIDY`... ie by the methods 1..3 enumerated... 

Simply **NO DEFAULT** configuration file...

Second, if a configuration file **is** defined by one of the methods 1..3 enumerated, then that `config` is fully overridden by the command line... and I **still** think tidy should **complain** that such a **defined by user** file is **not** found... 

You, the **user** defined it - there is **no** default - so you deserve to know what you deliberately **set**, suggested, defined, is **not** found... or even has problems...

Yes, you can use the idea **merged**, but there is **no** `exposing both servers`! Not a `server`, and later configs overrule any earlier...

What is given on the command line finally **rules the day**... and will be applied to the next input file on the command line... and as stated a second `-config in2.conf in2.html` can overrule that... and so on...

Really, I very gently ask again, **where is the problem in this?**... thanks...

**Comment by AnrDaemon** [comment] 2017-05-17 12:22
It doesn't matter if it a server or not. It was just an example.
If you want to restrict it to Tidy, I have a preferred set of default options (`$HTML_TIDY`, yes), but every time I want to use a different set of defaults, I'll have to, either
1. Unset `$HTML_TIDY` for a time.
2. Change `$HTML_TIDY` to point to a custom set.
3. Specify all possible options each time and fervently watch if no new options appear in my defaults that would alter the behavior of a custom set.
4. Always use `-config file` and forget that `$HTML_TIDY` exists altogether.

**Comment by balthisar** [comment] 2017-05-18 12:01
@AnrDaemon, I see your point, but Tidy is acting as designed. If we changed Tidy's behavior such that it _ignored_ `$HTML_TIDY` when specifying a `-config` or using configuration options, it would break other people's existing workflows that depend on this behavior.

Conceivably we could add a new switch `-ignore-env` and/or `-ignore-rc` to prevent Tidy from processing these files before handling `-config` or `--options`, but then you'd still be specifying _something_ on the command line, and so I'd suggest always using a `-config` file.

If you'd like to open another issue request for that particular behavior, we can move the discussion there.

If you'd simply like to achieve the behavior that you want (understanding that we can't achieve it without breaking things for current users), it's trivial to fork the project and make the change in the console application `tidy.c` right around line 1946.

In the mean time, I'll close this issue, and if you think `-ignore-env` or some other switch is something that you want, please don't hesitate to open a feature request issue for that.

Thanks.

**Closed by balthisar** 2017-05-18 12:01 UTC
Labels: Won't Fix
