### ISSUE TITLE
Tidy output clutter

### ISSUE THREAD

**Issue by Yves4** [htacg/tidy-html5#857] opened 2020-01-31 14:01 UTC
Hi,
It would be nice to maintain the standard UNIX approach, which is no unnecessary output. So basically make the -q flag default and put the text in the help text or something. This disturbs the casual user and is less polite. 

I'm referring to this text:

"About HTML Tidy: https://github.com/htacg/tidy-html5
Bug reports and comments: https://github.com/htacg/tidy-html5/issues
Official mailing list: https://lists.w3.org/Archives/Public/public-htacg/
Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
Validate your HTML documents: http://validator.w3.org/nu/
Lobby your company to join the W3C: http://www.w3.org/Consortium

Would you like to see Tidy in proper, British English? Please consider
helping us to localise HTML Tidy. For details please see
https://github.com/htacg/tidy-html5/blob/master/README/LOCALIZE.md"

**Comment by geoffmcl** [comment] 2020-02-09 20:31
@Yves4 thanks for your comment...

Well, I did not know there is a `standard UNIX approach`... that includes `no unnecessary output`... refs for that... ;=))

But even if there is, with a `less-is-better` philosophy, the creators of `tidy`, who were unix based, seemed to include a html **educational** approach, to the `errout` output...

And I guess that it is aimed primarily at the `casual user`... since it repeats things a dev would know... and certainly did not intend it to be `less polite`... lol...

Since from their first `tidy --help`, they can read how to quieten, `-q`, or redirect, `-f tidyout.txt`, etc, etc...

So is it the time, to invert the **verbal** default, by the founders... maybe... but... 

Maybe I have gotten used to adding `-q`, just about every time... yes, it probably really annoys the developer... ;=))

But can maybe be persuaded... look forward to further feedback... thanks...

**Comment by balthisar** [comment] 2021-07-09 15:55
I'm going to close this as a duplicate of #607, which is even more encompassing than this request.

**Closed by balthisar** 2021-07-09 15:55 UTC
Labels: Technical Discussion
