### ISSUE TITLE
list markup with missign tags

### ISSUE THREAD

**Issue by thorade** [htacg/tidy-html5#521] opened 2017-03-30 09:22 UTC
On the Tidy homepage missing closing list item tags are given as an example of what tidy can fix:
http://www.html-tidy.org/documentation/
Now, when my HTML code has exactly that problem (closing `</li>` is missing), I do not get any error.
Do I have to enable that as an option?
http://api.html-tidy.org/tidy/quickref_5.4.0.html
Or does tidy fix that silently, without reporting it?

Once that works, should that also report unclosed paragraphs?

**Comment by geoffmcl** [comment] 2017-03-30 13:59
@thorade thanks for the issue... sort of cross linked to another repo...

Well the issue is a little complicated by the fact that some tags have an `optional` end tags, in the html spec... 

Hence we have the option [omit-optional-tags](http://api.html-tidy.org/tidy/quickref_5.4.0.html#omit-optional-tags)... you can see that `<li>` is one of those...

So, as your [Issue 52](https://github.com/lbl-srg/BuildingsPy/issues/52#issuecomment-73225266) points out, Tidy will silently **fix** the following -

```html
<ul>
<li>the function is defined and monotone increasing for all <i>x</i>.
<li><i>dy/dx</i> is bounded and continuous everywhere (for <i>n &lt; 1</i>).
</ul>
```

with a config of `--show-body-only yes --show-info no -w 0` will give an **output** of -

```html
No warnings or errors were found.

<ul>
<li>the function is defined and monotone increasing for all <i>x</i>.</li>
<li><i>dy/dx</i> is bounded and continuous everywhere (for <i>n &lt; 1</i>).</li>
</ul>
```

So you are right, Tidy stays silent on missing **optional** end tags... Maybe it shouldn't? What do you, or others, think?

You can add the config option `--omit-optional-tags yes`, and the closing `</li>` will be dropped... and then for sure there should be no warning...

Now Tidy **will** bark if you omit the non-optional end tag `</ul>`...

So given a sample, similar to the documentation page - which perhaps needs some fixing, like adding the `<ul>` tag - like -

```html
<ul>
<li>1st list item
<li>2nd list item
```

For sure you get -

```html
line 1 column 1 - Warning: missing </ul>
Tidy found 1 warning and 0 errors!

<ul>
<li>1st list item</li>
<li>2nd list item</li>
</ul>
```

Does this fully answer your question? Look forward to further feedback... thanks...

**Comment by geoffmcl** [comment] 2017-03-30 14:48
@thorade, have added a small note to the [documentation](http://www.html-tidy.org/documentation/#documentation20000201part_what)... scroll to `List markup with missing tags`... just to make it clearer... thanks...

**Comment by thorade** [comment] 2017-03-30 19:10
Thanks for that note. If that is the inteded behavior, I am fine with it as it is.

My opinion is probably not representative here. 
How do you treat other cases where the output differs from the input?

**Comment by thorade** [comment] 2017-05-04 11:05
After thinking about it again, I believe a clean soultion could be to leave the default behavior as it is,
and add a new config option `--warn-optional-tags yes` for those who want to see a warning for every fixed optional tag.
Would that be hard to implement?

**Comment by thorade** [comment] 2017-07-31 11:32
One more note: I do not use the cleaned document at all, I just use (via pytidylib) the list of warnings that tidy is returning.

**Comment by geoffmcl** [comment] 2017-08-02 18:05
@thorade thanks for clarifying your use case...

You say via `pytidylib`? Is this a python libtidy port, or what? Where can I find it?

But concerning **`libtidy`**, at this time no one has stepped up to add/code a new option like say `--warn-optional-tags yes`, for those that want to see **every** fixed optional tag tidy makes, or at least more of them...

It would probably **not** be too difficult to implement, but you have to first find the person interested to add such code... 

If someone was to start something here, say in their own fork/branch, I would certainly help guide them where I can...

**Comment by thorade** [comment] 2017-08-19 07:18
pytidylib is just a thin wrapper that calls the tidy.dll from python
https://github.com/countergram/pytidylib
https://pypi.python.org/pypi/pytidylib

**Comment by balthisar** [comment] 2017-09-29 19:04
@thorade, @geoffmcl, I've added candidate #619 that will add a mutable (via show-info) message when a closing tag is missing and `omit-optional-tags` is not yes.

**Comment by balthisar** [comment] 2017-10-02 17:30
Merged, and closed.

**Closed by balthisar** 2017-10-02 17:30 UTC
Labels: Technical Support
