### ISSUE TITLE
Feature request: add an option to allow inline elements inside a span

### ISSUE THREAD

**Issue by jznf** [htacg/tidy-html5#461] opened 2016-10-22 15:18 UTC
current behaviour is that:

```
<span><button>OK</button></span>
```

throws:

```
Warning: inserting implicit <span>
Warning: replacing unexpected button with </button>
Warning: missing </button>
```

and the final result is:

```
<span><button><span>OK</span></button></span>
```

It might be handy to have an option to prevent this behaviour and let the original markup unchanged as it is valid and it's a part of quite common pattern.

**Comment by geoffmcl** [comment] 2016-10-31 00:32
@jznf, thank you for bringing this here...

As discussed, off list, this has been the behavior of tidy for a long time, thus any change should be subject to a new option, to `suspend` this action... probably not too difficult... 

Very much **welcome** any thoughts on this... thanks...

**Comment by geoffmcl** [comment] 2017-03-01 13:16
As we are about to `release` **5.4**, and there has been no progress on this `Feature Request`, moving it to `next`, **5.5** milestone...

I have constructed a sample [in_461.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_461.html) which passes W3C validation, so certainly think this feature should be added, even as the default...

**As always further comments, patches or a PR very welcome**... thanks...

**Comment by lhchavez** [comment] 2017-04-15 00:20
Ah this is just a difference in the HTML5 spec. Previously `<button>..</button>` was allowed to contain [flow](https://www.w3.org/TR/html4/interact/forms.html#edef-BUTTON) as children (which includes blocks and inlines). In HTML 5, that is restricted to [phrasing elements](https://www.w3.org/TR/2012/WD-html-markup-20120320/button.button.html#button.button).

I'll send a PR for this.

**Comment by geoffmcl** [comment] 2017-05-05 18:35
@lhchavez as stated. thank you for your PR #531... While this **works** fine, I have now proposed an alternative **fix**, PR #540, that not only addresses this `<button>` issue, but tidies up some other code... including an important fix for the `TY_(IsHTML5Mode)(doc )` service...

I have been delaying merging #540 hoping you would get a chance to pull and test the `issue-461` branch, and confirm. @balthisar has already tested, and confirmed... 

And now there is also a branch `issue-461` in the [tidy-tests](https://github.com/htacg/tidy-html5-tests/tree/issue-461) repo, which should match this change, and should pass 100% - stage 1 - exit codes, and 2 - diff results vs expects...

I understand RL must come first, but you say closing your #531, and/or adding a `+1` here, or something, would indicate for me to move forward... 

I am also holding off on a few other PRs to get #540 in place first... which will bump us to 5.5.15... thanks...

**Comment by lhchavez** [comment] 2017-05-05 18:37
oh, sorry i've been in the critical path. please go ahead and merge that other change since it's clearly better for everyone!

if i end up seeing other issues, i'll send further PRs. i'll close this one.

**Comment by lhchavez** [comment] 2017-05-05 18:37
(and by "this one" i mean the one i sent)

**Comment by geoffmcl** [comment] 2017-05-05 18:42
@lhchavez thanks for the quick reply... sorry to push when there may be other critical RL items...no apology needed...

It's a bit late in my working day today, to get into merges, etc, but will get to it tomorrow, or soonest... thanks...

**Comment by balthisar** [comment] 2017-05-05 18:53
Should I merge everything we've both okayed? I'm still GMT-5, so might be able to get to it tonight.

**Closed** 2017-05-06 12:22 UTC
Labels: Feature Request

**Comment by jznf** [comment] 2017-05-06 13:17
THANK YOU!!!
