### ISSUE TITLE
HTML5: "Warning: '<' + '/' + letter not allowed here" in javascript script tag

### ISSUE THREAD

**Issue by pmorch** [htacg/tidy-html5#475] opened 2016-12-23 08:32 UTC
Given:
```
<!DOCTYPE HTML>
<html>
<head>
    <title>tag demo</title>
    <script type="text/javascript">
        var endtag = "</a>";
    </script>
</head>
<body></body>
```
tidy reports:
```
> tidy -q -o /dev/null tag.html 
line 6 column 24 - Warning: '<' + '/' + letter not allowed here
```
But isn't `var endtag = "</a>";` valid in script tags in [HTML5](https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements)?

#281 reports a similar problem for `type="text/html"` script tags, and it is fixed, so they are related, but not the same.

```
> tidy -v
HTML Tidy for Linux version 5.2.0
```

**Comment by jry2** [comment] 2017-01-12 13:43
I can reproduce this problem with version 5.3.14. Please notice escaped </div> -> <\/div> in Tidy output.

```html
<!DOCTYPE HTML>
<html>
<head><title>demo</title></head>
<body>
<script type="text/javascript">document.body.innerHTML+='<div>text</div>';</script>
</body>
```

```
tidy -q tidy_err.html
line 5 column 70 - Warning: '<' + '/' + letter not allowed here
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Linux version 5.3.14">
<title>demo</title>
</head>
<body>
<script type="text/javascript">
document.body.innerHTML+='<div>text<\/div>';
</script>
</body>
</html>
```

**Comment by geoffmcl** [comment] 2017-01-16 19:51
@pmorch, as @jry2 points out this is an **ongoing** feature of tidy! That is, it remains in the current version 5.3.14...

Just reading here - http://stackoverflow.com/questions/6117886/javascript-and-forward-slashes-in-strings - suggests this may be another html4 versus html5 change that tidy should catch up on, if there is a change in the `<script>` specs... any links to the appropriate REC doc appreciated...

But as you can read there - "As far as JS is concerned `/` and `\/` are identical inside a string. As far as HTML is concerned `</` starts an end tag but `<\/` does not."... Hence tidy presently adds the escape, and issues a warning...

No #281 is a different problem, which has been solved. Change your javascript to `type="text/html"`, and maybe add a template `id=...`, and tidy will not issue this warning...

Now whether tidy needs to conform to a later spec just depends on the documentation... any help finding, understanding that would help greatly... thanks...

**Comment by pmorch** [comment] 2017-01-17 08:46
I can see that the [HTML spec from my link](https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements) is a little unclear. From my reading it I do conclude that the HTML in my OP is valid, but I would understand if purists were to question my basis for claiming that. [W3C's HTML5 Differences from HTML4](https://www.w3.org/TR/html5-diff/) document doesn't mention anything about changes to the `<script>` element which doesn't point in my favour.

If we assume that the HTML in the OP is indeed valid, then I argue that the warning and adding of the escape should not take place and is a bug, since there is nothing wrong with the input; the warning message: `letter not allowed here` is false and misleading.

@geoffmcl, am I correct in assuming that the "Feature Request" tag indicates that you assume the HTML in the OP is invalid? Because if one assumes it is valid HTML, then how can removal of a warning being generated because of valid input be a "Feature Request" and not a "Bug"?

So the fundemental question is whether the HTML in the OP is valid.

**Comment by geoffmcl** [comment] 2017-01-18 01:00
@pmorch ok, you are starting to convince me this is a html4 vs a html5 thing...

I can still find references to this `escaped`, sort of end tag, in the html4 REC - https://www.w3.org/TR/html401/interact/scripts.html#h-18.2.4 - shows a clear example: 

```html
<TITLE>Test Document</TITLE>
 <SCRIPT type="text/javascript">
     document.write("<p><b>Hello World!<\/b>")
 </SCRIPT>
 ```

And of course, I can **not** yet find the equivalent reference in the html5 REC - https://www.w3.org/TR/html5/scripting-1.html#script - they removed the example ...

Is that sufficient to raise this to a **bug** status... maybe...

And of course, I can read copious javascript references to `</` and `<\/` are essentially **equivalent**, even `===`, as far as javascipt goes...

So maybe tidy, in html5 mode, errors on the **safe** side, issuing a warning, and adds the `escape`...

The fundamental question remains, is it time tidy stopped doing this, if still in html5 mode? 

Should this be an **option**, or should tidy behavior change, without an option? 

And that is why it remains a `Feature Request`, rather than an outright **Bug**, at this time!

Look forward to more thoughtful, fruitful comments...

**Comment by geoffmcl** [comment] 2017-01-28 19:07
@pmorch, wow, shame on me for not **remembering** we already have this option! 

Try `--escape-scripts no`, and tidy will **not** issue the warning, and **not** escape `</b>`... see [escape-scripts](http://api.html-tidy.org/tidy/quickref_5.2.0.html#escape-scripts) documentation...

And shame on you guys for **not** reminding forgetful me that we already have this `feature`... see #348, Jan 16, 2016, v.5.1.47 onward... and in fact was discussed back as far as 2006-11-22 in the [sf803](https://sourceforge.net/p/tidy/bugs/803/) bugs! All worth reading...

In fact it was the re-compiling [edbrowse](http://edbrowse.org/), with msvc140, that brought me back to this option... I had a compile error if I used an **old** version of `tidy`, since it uses this `feature` in its code...

**So it is there already!** Please test and advise on this `option`...

It seems the single remaining question is whether it is time to change the `default` to **no**?

But that is a different issue, and if someone is interested in arguing this case, they should open another issue, referencing all the previous conversations, and present specific  reasoning... 

Meantime, am closing this here... thanks...

**Closed by geoffmcl** 2017-01-28 19:07 UTC
Labels: Feature Request, Help Needed

**Comment by jry2** [comment] 2017-01-28 20:00
Thank you, it works fine!

**Comment by pmorch** [comment] 2017-01-31 08:10
I concur - `--escape-scripts no` works great! Thanks!
