### ISSUE TITLE
Trailing slash "/" in a self-closing div is removed for xml-output = true

### ISSUE THREAD

**Issue by richardnielwilson** [htacg/tidy-html5#110] opened 2013-12-16 22:35 UTC
![tidyerror](https://f.cloud.github.com/assets/3442795/1760044/0e468956-66a8-11e3-9f89-660e7dc19f30.jpg)

**Comment by geoffmcl** [comment] 2015-01-24 17:54
The latest development is branch develop-500
$ git chechout develop-500
It would be appreciated if you would pull, build and test this branch...

I just did a quick test using your input, and a config of
merge-divs: no
input-xml: no
output-xml: yes
tidy-mark: no

And I certainly got -
<div data-book='test1'>
<div data-book='test2' />
</div>
which seems correct...

Can you check and confirm if you get the time... Thanks...

**Comment by balthisar** [comment] 2015-02-01 08:17
Looks like a duplicate of #111. Will close, as it looks like you addressed it.

**Closed by balthisar** 2015-02-01 08:17 UTC
Labels: Bug Report
