### ISSUE TITLE
Doctype removal on otherwise clean input

### ISSUE THREAD

**Issue by martinthomson** [htacg/tidy-html5#273] opened 2015-09-23 18:32 UTC
Running tidy multiple times causes the doctype to be alternately added and removed from an otherwise clean file.  This means that some runs generate errors, complaining about the absence of a doctype.

```
$ tidy -config tidyconf -modify index.html && echo OK
OK
$ tidy -config tidyconf -modify index.html && echo OK
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
$ tidy -config tidyconf -modify index.html && echo OK
OK
$ tidy -config tidyconf -modify index.html && echo OK
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
```

**Comment by geoffmcl** [comment] 2015-09-25 11:46
@martinthomson I ran this test **many** times, in linux and windows, with tidy versions 4.9.36, 5.0.0, 5.1.8, 5.1.12, and can **not** repeat the problem ;=()

My simple temp1.html input was -
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Issue #273 - Doctype removal on otherwise clean
input</title>
</head>
<body>
<p>para 1</p>
</body>
</html>
```

Command: `$ tidy -q --show-info no -modify temp1.html`

The first modified output, with just with a tidy-mark added -

```
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.1.12">
<meta charset="utf-8">
<title>Issue #273 - Doctype removal on otherwise clean
input</title>
</head>
<body>
<p>para 1</p>
</body>
</html>
```

And repeating that command over and over does not have a problem!

What version of tidy are you using? What is in the tidyconf file? 

Do you have a $HOME/.tidyrc in use? What is its contents, if yes? What is the content of index.html?

Have I missed something here?

**Comment by martinthomson** [comment] 2015-09-25 16:41
Hmm, I tried this many time with the following config:

```
char-encoding: utf8
indent: yes
wrap: 100
tidy-mark: no
```

You can see this in action here: https://github.com/w3c/mediacapture-fromelement/tree/tidy

Run `make tidy` a few times.  n.b., If you run this without a tidy installation on your path, it will build and install tidy from trunk; the intent is to use this with C-I.

**Comment by martinthomson** [comment] 2015-09-25 16:43
Oh, whoops, you might have to modify some files there; I built in a hack that works around this specific issue already.  If you delete the contents of `fixup.sed`, you should be able to reproduce the problem.

**Comment by geoffmcl** [comment] 2015-09-25 19:11
@keithmendozasr again sorry, but I do not have time to debug all scripts that use tidy...

However I did read through some of the stuff... the only suspect lines seen were -

```
support_dir ?= $(CURDIR)/.support
tidy ?= $(shell which tidy 2>/dev/null)
ifeq (,$(tidy))
tidy := $(support_dir)/bin/tidy
endif
```

Later you do build and install tidy from source, and install into `$(support_dir)`, but to me it is not clear which tidy is being used in `$(tidy)`...

But ok, you have tidied tidy's output with fixup.sed, which gets you over the problem, but does **not** explain what is really going wrong...

As indicated I do **not** think there is a **bug** in tidy! I can not produce this!

Can you reproduce this problem either running tidy from its installed location, like `/usr/bin/tidy`, or `/usr/local/bin/tidy`, or running the newly built and installed version in `$(support_dir)/bin/tidy`?

Pointing me to a repo does not prove anything... maybe someone else can see the fault, and offer some help...

**Comment by martinthomson** [comment] 2015-09-25 21:04
I'm sorry, I didn't want to make this harder for you.  Here's what I've got.  I've built this directly from a github clone:

```
$ which tidy
/usr/local/bin/tidy
$ tidy -version
HTML Tidy for Linux version 5.1.9
$ tidy -q --show-info no -modify index.html 
$ head -1 index.html 
<html lang="en-us" xmlns="http://www.w3.org/1999/xhtml" xml:lang=
$ tidy -q --show-info no -modify index.html 
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
$ head -1 index.html 
<!DOCTYPE html>
```

That's with no config file.  The HTML is the one that you see in the repo I linked to.  And you are right, the test file you created doesn't do the same thing.  I can't explain it.  I was really hoping it would be something trivial.

**Comment by geoffmcl** [comment] 2015-09-26 12:47
@keithmendozasr WOW, this is a really weird bug... thanks for persisting, and finding a repeatable scenario, namely tidying https://github.com/w3c/mediacapture-fromelement/blob/tidy/index.html

The first time tidy parses this document, it shows quite a number of warnings, and declares it as `Info: Document content looks like HTML Proprietary`, and in the output, say `temp1.html`, refuses to add a DOCTYPE!!!

Then when you re-run tidy on the `temp1.html` output, and output it to `temp2.html`, it only warns about the missing doctype, but says it looks like XHTML5 -

```
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
Info: Document content looks like XHTML5
1 warning, 0 errors were found!
```

Then when you re-run tidy on the `temp2.html` output, and output it to `temp3.html`, you get a clean report -

```
Info: Document content looks like XHTML5
No warnings or errors were found.
```

But now `temp3.html` will not have a DOCTYPE... and is exactly equal to `temp1.html`... and the cycle continues... forever!

So this shows it is nothing to do with the `-modify` option used. This flip/flop happens even when outputting to a new file each time, and then using that new file as the next input... and each alternate outputs are exactly equal...

Now this ONLY happens with the full contents like `index.html`. If I use a simpler XHTML input like the following there is no problem -

```
<!DOCTYPE html>
<html lang="en-us" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-us">
<head>
  <link href="fromelement.css" rel="stylesheet" type="text/css" />
  <title>Test 2 - #273</title>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
</head>
<body>
<p>Para 1</p>
</body>
</html>
```

This will output as -
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en-us" xmlns="http://www.w3.org/1999/xhtml" xml:lang=
"en-us">
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.1.13" />
<link href="fromelement.css" rel="stylesheet" type="text/css" />
<title>Test 2 - #273</title>
<meta content="text/html; charset=utf-8" http-equiv=
"Content-Type" />
</head>
<body>
<p>Para 1</p>
</body>
</html>
```

And this output can be re-run through tidy forever with no change...

Now to dive into the code and try to discover why tidy, given your `index.html` content, removes the doctype on the first run, and adds a doctype on the next - flip/flopping ;=((

**Comment by geoffmcl** [comment] 2015-09-26 13:25
Zeek! The first debug run, using `temp2.html` as the input reveals where it happens... I am using `temp2.html` (actually input5\in_273-4.html in my test cases archive) because it is the cleaned `index.html` that has a doctype...

The following is an extract from my extra debug output. Unfortunately at present this EXTRA debug output is only available in the Windows MSVC Debug version. ie not available in linux at this time -

Here I interate through all the nodes in the internal tree just before `clean and repair` is done, and then after the `clean and repair`, and there is a big difference...

```
All nodes BEFORE clean and repair
Root  
 DocType  
 StartTag html   lang="en-us" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-us"
  StartTag head  
... etc ... then -
All nodes AFTER clean and repair
Root  
 StartTag html   lang="en-us" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-us"
  StartTag head  
... etc
```

Why is tidy **removing** the internal `DocTYpe` node in `clean and repair`????

The saga continues ;=))

**Comment by geoffmcl** [comment] 2015-09-26 23:10
@keithmendozasr think I have found, and fixed it...

It happens in Bool TY_(SetXHTMLDocType)( TidyDocImpl* doc )... Called from `int tidyDocCleanAndRepair( TidyDocImpl* doc )`, `if (xhtmlOut && !htmlOut)`...

At this time the TidyDoctypeModes dtmode == TidyDoctypeAuto, after testing the lexer->versions contains certain flags (val == 0x0004e000), and not finding any it wants, like VERS_FRAMESET, VERS_LOOSE, VERS_HTML40_STRICT, etc. in `else` it will discard the DocType node... WHAT! discard doctype??????

Note that 0x0004e000 corresponds to `(VER_SUN | VERS_NETSCAPE | VERS_MICROSOFT)`, which combined are `VERS_PROPRIETARY`, **and** the `XH50` bit... I am immediatley tempted to make this an exception in this last else case, and that is to NOT delete the DocType node, IFF...

Wait, there is a meta `VER_HTML5` defined... so if this is still possible, ie not all the html5 bits have been eliminate during the parsing, then true to html5 pragma, do not leave a document without a DocType! Do **not** delete this node... try that!

Wow, this seems to remove the **bug**! A diff -

```
diff --git a/src/lexer.c b/src/lexer.c
index 638f72f..8cc2b0d 100644
--- a/src/lexer.c
+++ b/src/lexer.c
@@ -1771,6 +1771,16 @@ Bool TY_(SetXHTMLDocType)( TidyDocImpl* doc )
             TY_(RepairAttrValue)(doc, doctype, sys, GetSIFromVers(X10T));
             lexer->versionEmitted = X10T;
         }
+        else if (lexer->versions & VERS_HTML5)
+        {
+            /*\
+             *  Issue #273 - If still a html5/xhtml5 bit
+             *  existing, that is the 'ConstrainVersion' has
+             *  not eliminated all HTML5, then nothing to do here.
+             *  Certainly do **not** delete the DocType node!
+             *  see: http://www.w3.org/QA/Tips/Doctype
+            \*/
+        }
         else
         {
             if (doctype)
```

Will do some more testing, and if you get a chance to apply this diff, and test again, and comment, will push this **fix** to `master`...

Again, thank you for finding the repeatable sample... this is **so** important in chasing this type of bug...

Hope this fix tests positive ;=))

**Comment by martinthomson** [comment] 2015-09-27 03:00
Thanks for digging in and persisting.  The fix works for me.

**Comment by geoffmcl** [comment] 2015-09-27 15:55
@keithmendozasr thanks for testing and reporting...

I have also now done the 228 regression tests with no problem...

So have now pushed this change to `master`, and bumped the version to 5.1.14

Perhaps after some more testing you can close this? And interesting bug...

**Comment by keithmendozasr** [comment] 2015-09-27 18:37
@geoffmcl I think you're tagging the wrong person for this issue. I didn't file this issue; in fact, I've only started using tidy last week. The one issue I filed, I closed because I couldn't replicate it anymore.

**Comment by geoffmcl** [comment] 2015-09-27 18:54
@keithmendozasr yes got my tags in a mess ;=() sorry...

Was meant for @martinthomson ;=))

**Comment by geoffmcl** [comment] 2015-10-31 17:26
No more comments for over a month, so I guess we can close this...

Please re-open, or open another issue if required... thanks...

**Closed by geoffmcl** 2015-10-31 17:26 UTC
Labels: Bug Confirmed
