### ISSUE TITLE
Infinite loop parsing in tidy

### ISSUE THREAD

**Issue by rstrauss** [htacg/tidy-html5#393] opened 2016-04-03 01:47 UTC
I saw the other issue of the same name, but don't know if it's the same.
This is also in 5.1.25
I get an infinite loop with what seems to be fine html.
So I just wanted to attach the html so someone could try it on the latest.
I just installed tidy-html5 on my Mac using homebrew...

````
Error:
line 19 column 17 - Warning: missing </li> before <a>
line 19 column 21 - Warning: missing <li>
line 19 column 21 - Warning: missing </li> before <a>
Then the last 2 repeat

The html is a bit weird_ it has nested <a> elements...

<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-primary navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="index.html">
          <img src="img/people-count-logo.png" class="img-responsive" />
        </a>
        <ul class="nav navbar-nav navbar-right pull-right">                   
          <li class="dropdown" valign="middle">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="float: right">
              <span class="icon-bar"></span>
              <ul class="dropdown-menu">
                <li><a href="http://PeopleCount.org/about.htm">About</a></li>
                <li><a href="http://PeopleCount.org/how.htm">How it Works</a></li>
	      </ul>
	    </a>
	  </li>
	</ul>
      </div>
    </div>
  </nav>
</body>
</html>
````

Edit: Added tick marks to see html

**Comment by geoffmcl** [comment] 2016-04-03 12:17
@rstrauss yes, this is a **repeat** of issue #321, and is a **known** problem with version 5.1.25, but has been fixed by version 5.1.27, and later...

Now I looked at the `homebrew/Library/Formula/tidy-html5.rb`, and unfortunately it downloads and uses the `5.1.25.tar.gz` source, so can do **nothing** about that... This shows the same at http://braumeister.org/search/tidy...

It would be good if `homebrew` offered a formula to use the latest `master` git source, but note that site has over 200 pull requests, so even if I, or someone, offered say a `tidy-latest.rb` it might be a long time before it got into distribution for you to use...

But building and installing the latest 5.1.51 plus tidy is **not** difficult... I do not use a MAC, but open a terminal and enter the following commands should do it, assuming you have git, cmake and build-essentials installed -

````
$ git clone --depth 1 https://github.com/htacg/tidy-html5.git
$ cd tidy-html5/build/cmake
$ cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
$ make
$ sudo make install
````

This will install tidy in `/usr/bin`, so you should be able to run `$ tidy -v`, and see version 5.1.51...

We are in the process of considering a tidy 5.2.0 release shortly, but again it might be some time before that would be available in homebrew...

Really, the best solution seems to be **build it yourself**... just follow the above steps... maybe other MAC OX X users can offer more...

**Comment by rstrauss** [comment] 2016-04-04 21:51
I had to download cmake for the mac
and it gives a gui instead of installing it in /usr/local, so the command-line you gave didn’t work,
but it only took a couple of tries to work.

Thanks much!
-r
PS:  Please add your email to our announcement list:
http://PeopleCount.org/tohelp.htm
For more info:  http://PeopleCount.org/how.htm

**Comment by geoffmcl** [comment] 2016-04-05 12:50
@rstrauss hmmmm, reading around I think you could install the `cmake` command line tool using your `homebrew`

```
$ brew install cmake
```

But using the cmake-gui is also quite easy. It would just replace the 3rd line with some GUI steps, and generate the makefile system of your choice, on configure... 

I wonder whether it was the simple **curses** gui, `ccmake`, or the full **Qt** based `cmake-gui`? Just curious...

Anyway, glad you got current **tidy** built and installed... You can now always keep up with the **latest** by -

```
$ cd tidy-html5
$ git pull
$ then cmake configure and build
```

Have you had a chance to test out the latest **tidy** on your sample html?

If the problem is **fixed** appreciate you closing this issue... thanks...

**Comment by balthisar** [comment] 2016-04-09 07:03
@rstrauss, latest signed Mac binary for 5.2.0 is out, too: http://binaries.html-tidy.org

**Closed** 2016-04-09 07:04 UTC
Labels: Technical Support

**Comment by rstrauss** [comment] 2016-04-09 07:30
Sorry, I just saw this- it’s been a hell of a week.

Yes, this worked.
Then moments after cmake was installed, 
I got an email that someone else created 5.2.0 for the mac.
So I installed that.
Both 5.1.25 and 5.2.0 have one weirdness, FYI

On the attached file, they produce:

line 71 column 7 - Warning: missing </div>

This seems to be an error to me...

    63      <header id="myCarousel" class="carousel slide">
    64        
    65        <ol class="carousel-indicators">
    66          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    67          <li data-target="#myCarousel" data-slide-to="1"></li>
    68          <li data-target="#myCarousel" data-slide-to="2"></li>
    69        </ol>
    70        
    71        <div class="carousel-inner">
    72          <div class="item active">
    73            <div class="fill" style="background-image:url('img/header-img.jpg');">

Weird: I tried adding the </div> that it said was missing and I get:

line 71 column 7 - Warning: discarding unexpected </div>
line 71 column 13 - Warning: missing </div>



If you’d prefer that I log it, I can.
Thanks,
-Rand
