### ISSUE TITLE
ins element gets double inserted

### ISSUE THREAD

**Issue by marcoscaceres** [htacg/tidy-html5#92] opened 2013-06-09 18:16 UTC
Given: 
```html
<ins><p>hi</p></ins>
```

Tidy produces:
```
<ins><p><ins>hi</ins></p></ins>
```

And if run again, Tidy produces:
```
<ins><p><ins><ins>hi</ins></ins></p></ins>
```

Expected tidy only pretty print ins and not add other ones (as wrapping block level elements is valid HTML5 according to validator.nu):
```
<ins><p>hi</p></ins>
```

Sad :panda_face:

**Comment by geoffmcl** [comment] 2015-01-27 18:31
Yes, it is SAD ;=))

Can confirm it is the same for del, and has been like that in Tidy since probably long before the last 2009 release...

I note that in Dict tag_defs[] that they are marked as CM_INLINE|CM_BLOCK|CM_MIXED, thus when a p is encountered, marked as CM_BLOCK|CM_OPT, the ins will get copied to inside the block... and will repeat that process each time tidy is run... not good... 

Normaly these elements should be only inside the block, not surrounding it... but will see what can be done...

**Comment by geoffmcl** [comment] 2015-01-28 11:02
Fixed! Although marked as CM_INLINE, also marked CM_BLOCK, should not be stacked for later insertion. Added nodeIsINS(n) and nodeIsDEL(n) macros, and in IsNodePushable(n) returns no 
if either of these... This could possibly apply to others... And left remnants of my first fix, as a point where to avoid insertions...

This is only in develop-500 branch -
$ git checkout develop-500

Also on the march to release 5.0.0, have reset the version to 4.9.1, intending to bump the point for each fix along this road so issues can address a specific version.

After testing, If found fixed, appreciate if this LONG STANDING bug could be closed... phew!

**Comment by balthisar** [comment] 2015-02-01 09:09
Confirmed fixed.

**Closed by balthisar** 2015-02-01 09:09 UTC
Labels: Bug Report
