### ISSUE TITLE
Crash tests

### ISSUE THREAD

**Issue by pedromorgan** [htacg/tidy-html5#172] opened 2015-03-05 02:11 UTC
Can i make a suggestion..

Please setup a seperate repos.. for tests..

eg
htacg/tidy-html5-crashme-tests

And we put all html in there..
Also we ranme stuff to..
malformed-head.html
and
malformed-meta.html

and alike as snippets..

This means people can have rea fun forking it..
making some evil change.. probably c+p from realworls
and test it ;-)

Tests within this repos.. I would remove asap. .to avoid a load of crap.. imho..

pete

**Comment by pedromorgan** [comment] 2015-03-05 02:58
Here's the idea..
https://github.com/pedromorgan/html5-crash-tests

Even down to snippets
eg
head.title-strange.html
head.title-silly.html

p.style.silly1.html

and have everyone make their own snippet...
eg
<h1><p>this <i><b>iZ&amp;</font></i>Sill<h3>Y</h3></h1><h1></h1></h6>

**Comment by balthisar** [comment] 2015-03-05 12:10
Add indefinite future because there has been talk about refactoring the testing.

**Comment by geoffmcl** [comment] 2015-06-22 14:08
Have added a README.md to the test directory with some some explanations... and have added a testbase directory... but this is not easy!

It is really only a sort of regression test, and as can be read requires manual human viewing and interpretation, so is **NOT** promoted as something every new user needs to try.

Anyway, am closing this for now since no new comments for many weeks, but feel free to re-open, or post a new issue.

**Closed by geoffmcl** 2015-06-22 14:08 UTC
Labels: Infrastructure
