### ISSUE TITLE
Tidy omits closing tag for self closing div when doing HTML5 output

### ISSUE THREAD

**Issue by ermshiperete** [htacg/tidy-html5#111] opened 2014-01-09 14:35 UTC
```
cat test.html
<html><body><div a='b'/></body></html>
```

Running `tidy test.html` produces the following incorrect HTML5 code where the closing div tag is missing:

```
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 (experimental) for Linux https://github.com/w3c/tidy-html5/tree/c63cc39">
<title></title>
</head>
<body>
<div a='b'>
</body>
</html>
```

**Comment by geoffmcl** [comment] 2015-01-24 17:34
The latest development branch, develop-500 is now on the repo...
$ git checkout develop-500
Does this branch correctly handle this closing tag?
If not could you provide a simple sample, if different to the above, together with the configuration used...
If yes, can we close this issue?

**Comment by balthisar** [comment] 2015-02-01 08:15
It works, and no response from @ermshiperete. I will close this, but @ermshiperete please feel free to open it again if the problem isn't solved.

**Closed by balthisar** 2015-02-01 08:15 UTC
Labels: Bug Report
