### ISSUE TITLE
Remove injecting meta generator tag

### ISSUE THREAD

**Issue by bruceburge** [htacg/tidy-html5#558] opened 2017-05-16 15:26 UTC
Your application cleans up existing HTML documents, it is also pretty shady to inject an advert for your product in this manner. 

please remove the injection of 
`    <meta name="generator"
    content="HTML Tidy for HTML5 (experimental) for Windows https://github.com/w3c/tidy-html5/tree/c63cc39" />`

**Comment by geoffmcl** [comment] 2017-05-17 14:01
@bruceburge thanks for the issue...

I am not sure I would characterize it as **shady** ;=))

But, yes, unless configured otherwise, tidy, by default, will create such a meta tidy mark...

There are various ways you can configure tidy to **not** do this -

 1. On command line - add option `--tidy-mark no`.
 2. Put the option in a file, say `tidy.conf`, as `tidy-mark: no`, and add `-config tidy.conf` on the command line.
 3. And once you have this option in a file, you can tell tidy via the environment - `set HTML_TIDY=D:\path\to\tidy.conf`

And I am also not sure **advert** applies to free, open source software, and it is only put in the `<head>` of the document, not normally seen unless you inspect the html in an editor...

Also it is **good** to tell the age of your version of tidy. A commit of c63cc39 is from about 5 years ago, circa 2012. We have subsequently dropped the `(experimental)` moniker, and have a web site http://www.html-tidy.org/

You can get much later version from http://binaries.html-tidy.org/...

And if you are able to compile tidy from source, then the [latest](https://github.com/htacg/tidy-html5) would `inject` -

```
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.5.24">
```

Notice we have switched to using a version number, rather than the git commit hash...

Hope this helps... thanks...

**Comment by bruceburge** [comment] 2017-05-17 14:33
I'm actually using the tidy plugin for notepad++ which I don't believes ready allows for the use of flags. And I the plugin is saying it's the latest version, so that sounds like it could use updating. 

As for as injecting generator tag. From the HTML5 spec. 

generator
The value must be a free-form string that identifies one of the software packages used to generate the document. This value must not be used on pages whose markup is not generated by software, e.g. pages whose markup was written by a user in a text editor. https://www.w3.org/TR/html5/document-metadata.html#standard-metadata-names

Suppose it's debatable if you could consider formatting  preexisting documents, generating them. 

Regardless, it's your application, and a handy one at that. So I'll continue to use it either way, and thanks all the efforts to make it available.

**Comment by geoffmcl** [comment] 2017-05-17 17:20
@bruceburge well I use Notepad++ (NPP) **all** the time, just not the Tidy plug-in that often. But my NPP v5.9 (UNICODE) does support using config files with Tidy, so could certainly add `tidy-mark: no` to those...

And searching more now, it seems I **forked** the `bruderstein` [NppTidy2](https://github.com/bruderstein/NppTidy2) repo some time back, and built myself a [Release](https://github.com/geoffmcl/NppTidy2/releases) plug-in, using Tidy 5.3.1... circa June 2016... 

I should try to find time to **update** that... I just tried a quick re-build, but it **failed**... but do not have time now to look into it... any help **much** appreciated... thanks...

On the matter of the meta `generator`, I probably agree it is debatable if **fixing** and **pretty printing** constitutes actually **generating**, but now you should have a way to tell tidy to omit adding it, it seems a mute point...

And I just modified my NPP `tidy1.cfg`, actually `C:\Users\<user>\AppData\Roaming\Notepad++\plugins\config\tidy1.cfg`, to include `tidy-mark: no` and it worked... give it a try... thanks...

**Comment by geoffmcl** [comment] 2017-05-18 01:59
@bruceburge ok, I found the little problem in compiling my [NppTidy2](https://github.com/geoffmcl/NppTidy2) fork, and have managed to update my own NPP installation to use a Tidy2.dll, version 5.5.24, but will continue to **hack** at it as time permits...

Now my NPP `Plugins ->  Tidy2 -> About` reports `Uses 5.5.24...`, but my attempts to make this dialog string from a `version.txt` file failed - see [Issue 2](https://github.com/geoffmcl/NppTidy2/issues/2) ... as stated there will work on this as time permits, and try to publish a **new** `NppTidy2` DLL soonest...

While this is **not** specifically `HTML Tidy` related, it is a very **good** use of the Tidy library... in this case it uses the STATIC library to build the `Tidy2.DLL` plugin... See also http://www.html-tidy.org/ -> TIDY+

We move slowly forward...

**Comment by geoffmcl** [comment] 2017-05-30 18:42
@bruceburge as you may have noted I have [released](https://github.com/geoffmcl/NppTidy2/releases) a `5.5.24` version of **Tidy2.dll**, in the `Tidy2-5.5.24.zip` there, **and** have tested that I **can** add the option `tidy-mark: no` to config files... no problem...

Then Tidy will **not inject** a meta generator tag...

Have you managed to update your NPP installation?

Can we close this? Thanks...

**Comment by bruceburge** [comment] 2017-05-30 21:20
Hey thanks for the reply, and yes, adding `tidy-mark: no` to any of the tidy configs for the plug removes the injection.  So you can close the issue, and appreciate your time on the matter. But...

I'm not sure if your config file supports comments, but providing one (or all three of the base .config) with all the options available would be helpful in not all the options available. 

Side note: 
my NPP is up to date, 
![image](https://cloud.githubusercontent.com/assets/6773890/26605451/ad7a2ce8-4553-11e7-8cf1-8aec3c94d25e.png)

though it doesn't see whatever changes you have made have been pushed into the plugin manager info listing. 

This is a fresh install of npp with tidy2 added from the plugin manager 
![image](https://cloud.githubusercontent.com/assets/6773890/26604429/fa27fcf4-454f-11e7-9bf0-393e6c9b07d5.png)
![image](https://cloud.githubusercontent.com/assets/6773890/26604832/4407e266-4551-11e7-863d-08e09f163565.png)

The update tab in the plugin manager doesn't list there being any available updates.
![image](https://cloud.githubusercontent.com/assets/6773890/26604453/11c1f374-4550-11e7-8694-1fea16060d7e.png)

**Comment by geoffmcl** [comment] 2017-05-31 12:57
@bruceburge thanks for your reply, and additional information...

Wow, it turns out my NPP is way out-of-date! Shows Build time : Mar 31 2011, v5.9 (UNICODE) - I should probably do something about that ;=))

I know **nothing** about where the `Plugin Manager` gets the **plugins** from, or where it checks for updates... 

I just forked Dave Brotherstone [NppTidy2](https://github.com/bruderstein/NppTidy2), to my [NppTidy2](https://github.com/geoffmcl/NppTidy2), and proceeded to build it...

Since I am a maintainer of [HTML Tidy](https://github.com/htacg/tidy-html5) I used a later version of libTidy, namely 5.5.24, circa 2017.05.13...

And **manually** installed the results into NPP, and took the liberty of adding my name to the NPP `Plugins -> Tidy2 -> About -`
![tidy2-about](https://cloud.githubusercontent.com/assets/1333435/26632573/dad74d70-4610-11e7-8abb-d9bd8c967109.jpg)

Concerning the Tidy **config** options, yes the config file does support `// comment` lines, and yes one idea would be to add **all** to one of the config files, but...

With my Tidy2 [release](https://github.com/geoffmcl/NppTidy2/releases), the zip includes a `quickref.html` which can be copied to NPP install, and viewed with `Plugins -> Tidy2 -> Show Config Help`. This seems a better way to show all the config option, with a description about each...

And of course, we at HTML Tidy publish this through http://api.html-tidy.org/, where you can choose various `quickref` versions...

Thus I do not think it is necessarily a good idea to list them as comments in a config file...

So, like I say, do **not** really know about the NPP `Plugin Manager`, but you could use my above install **manually** if my release is compatible... it is 32-bit, but it is also a **UNICODE** version... so not sure...

And yes, will close this... thanks...

**Closed** 2017-05-31 12:58 UTC
Labels: Technical Support

**Comment by Kristinita** [comment] 2018-05-14 17:33
### 1. Summary

I use `--tidy-mark no`, because I want, that will display real modified data, no data of new HTML Tidy version:

### 2. Environment

I use plugin [**filetime_from_git**](https://github.com/getpelican/pelican-plugins/tree/master/filetime_from_git), that generate data of last HTML file modifying.

### 3. Expected behavior

**If** `--tidy-mark no`:

    data of real changes generate.

### 4. Actual behavior

**Else**:

    data of new HTML Tidy version can be generate, [**example**](https://github.com/Kristinita/Kristinita.github.io/commit/5e9dd01a174c5fec19313f9ff06a29106c5fbef5#diff-8aaf3449fb3fa9d46d1cf07f3a25a4dd)

```diff
 <html lang="en">
 
 <head>
-   <meta name="generator" content="HTML Tidy for HTML5 for Linux version 5.7.9">
+   <meta name="generator" content="HTML Tidy for HTML5 for Linux version 5.7.10">
    <meta charset="utf-8">
    <!--=======================
    =          Meta           =
@@ -126,13 +126,13 @@ <h1 class="SashaTopHeader">4 14 7. 4 корвера, 14 аксаксов, 7 га
                <div class="SashaVersion">
                    <!-- pubdate attribute is obsolete, use itemprop: datePublished
                    https://stackoverflow.com/a/24455070/5951529 -->
                    Last modified —
-                   <time itemprop="datePublished" datetime="2018-04-21 17:25:19+03:00">2018-04-21 17:25:19+03:00</time>
+                   <time itemprop="datePublished" datetime="2018-04-22 18:34:27+03:00">2018-04-22 18:34:27+03:00</time>
                </div>
            </header>
```

Thanks.

**Comment by jcubic** [comment] 2018-10-09 16:40
This works but `--tidy-mark no` give blank line in place where meta tag was injected.

**Comment by loadedsith** [comment] 2020-04-08 19:40
This issue was the #1 search result for me when searching for this issue. 

I assume thats because the documentation for "tidy-mark" doesn't mention what it actually inserts. Someone trying to remove it, wouldn't know to search for "tidy-mark".

Might be time to consider amending the description of "tidy-mark" so that it mentions "meta tag"s, "generator", and "html tidy for html", so that maybe "tidy-mark"'s SEO outranks this issue's SEO Juice.
