### ISSUE TITLE
Linux binaries for latest releases

### ISSUE THREAD

**Issue by Lucas-C** [htacg/tidy-html5#939] opened 2021-04-14 07:56 UTC
Hello.

Looking at the binary release pages:
- https://github.com/htacg/tidy-html5/releases
- http://binaries.html-tidy.org

...there seems to be no Linux binary releases for versions above 5.4.0.

I'm opening this issues to humbly request if binaries could be released for recent versions of Tidy HTML please?

Regards

**Comment by geoffmcl** [comment] 2021-04-25 16:14
@Lucas-C, thanks for the issue... it raises **many** points...

Yes, it does seem we **missed** adding any linux binaries to release `5.6.0`... not sure why... but seems rather late in the day to do this now... even if I do correctly remember the rather tricky process of adding `binaries`...

The other `5.7.28` was only an interim release, and did not feel the need to add binaries for that... hopefully people can build their own latest, from source!

Especialy since I am back onto to considering a `5.8.0, so.6`, release, or maybe `6.0.0 so.6`, and/or, at least, a `5.7.47++` interim release(s)... there are so many good things **fixed** since that last `5.6.0`, Nov 25, 2017 release, now **years** ago...

The **main** holdup at this point is issue #743... I think I have solved the exposed `prvTidyXXXX` functions, in the `issue-743` branch, and would really appreciate others testing and confirming this... or, **better still**, offering an **alternative**, since the solution I have proposed is quite invasive, effecting some 14, or more, sources... read too many lines of change... maybe there is a **simpler** way to achieve the same?

And maybe there are some other issued that should be considered for the rel... again would **appreciate** feedback on this... like some sort of `triage`, `assessment`, of the outstanding issues... like #921 seems important... others???

I recently added `gen-html.bat|sh` to automate parts of the release - the rel HTML, enhanced, and version.log... but more to do, like creating the SHA256 files, semi-auto-modifiying [tidy.yml](https://github.com/htacg/html-tidy.org.binaries/blob/gh-pages/_data/tidy.yml) for the new bin files... etc, etc... **much help needed**!!!

After adding `;ZIP`, to cmake's `CPACK_GENERATOR`, just checked the unix `make package`, and the 3 `DEB/RPM/ZIP` packages built fine, and likewise, after installing `WIX` in my new windows 10 machine, already had `NSIS` installed, `cmake --target PACKAGE ...` built the 3 `EXE/MSI/ZIP` packages there... so another install step tested **ok**...

As sometimes happens, my `tidy` enthusiasm is **flagging**, due to the general lack of feedback, help, testing, reporting, etc, etc, even helpful comments... c'est la vie...

Anyway, @Lucas-C, this is not all directed at you. As stated, thanks for the release reminder...

**Comment by balthisar** [comment] 2021-07-09 16:08
I'll close this a duplicate of a couple of others. After the 5.8 release, I will look at some automated builds for supported platforms.

**Closed by balthisar** 2021-07-09 16:08 UTC
Labels: Build/Install, Distribute, Help Needed

**Comment by Lucas-C** [comment] 2021-07-29 12:37
Thank you for the new release ! 🥳🙌🎈🎉

**Comment by balthisar** [comment] 2021-07-30 13:42
And, automated builds are now available for `next` branch, as well.

These are Github "pre-release", so you have to look at "Releases" to find them.

Currently whenever the version is bumped, one of the maintainers still has to create the pre-release manually, but when this is done, the builds will attach automatically.
