### ISSUE TITLE
Tidy fails with following HTML

### ISSUE THREAD

**Issue by foxinushka** [htacg/tidy-html5#283] opened 2015-10-06 09:35 UTC
Test html:
https://www.dropbox.com/s/d4me1itots9j8sm/test.html?dl=0

If I remove ```<style> ... </style>``` tag and its content, tidy works well.
Otherwise it adds next text:
```
/*]]>*/
</style>
</head>
<body>
</body>
</html>
```

after ```</html>``` tag.

**Comment by geoffmcl** [comment] 2015-10-06 13:20
@foxinushka thanks for reporting, and providing a sample...

This is now a known bug in tidy, see #280, and the cause has also been found, and are considering fixes...

Since this seems a repeat of the same problem, am closing this and transferring your comments to there...

Please follow it there, and again thanks for reporting...

**Closed by geoffmcl** 2015-10-06 13:20 UTC
