### ISSUE TITLE
clean options bug

### ISSUE THREAD

**Issue by chg365** [htacg/tidy-html5#286] opened 2015-10-15 08:34 UTC
tidy -utf8 -clean test.html
out print : 
```
<style type="text/css">
 span.c2 {color: rgb(255, 0, 0); font-family: å®�ä½�; font-size: 20px}
 span.c1 {font-family: æ�¹æ­£ä»¿å®�; font-size: 36px}

font-family: ....   is error
```

test.html

```html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>test</title>
</head>
<body>
    测试
    <span style="font-size:36px;">
        <span style="font-family: 方正仿宋;">测试</span>
    </span>
    <span style="font-size:20px;">
        <span style="color: rgb(255, 0, 0);">
            <span style="font-family: 宋体;">测试</span>
        </span>
    </span>
    <script type="javascript">alert("aaaaaaaaaa");</script>
</body>
</html>
```

**Comment by geoffmcl** [comment] 2015-10-15 14:44
@chg365 you need to add the three back quotes when adding html and output to the comment...

Have adjusted your posts accordingly...

Now to try to look at the problem...

**Comment by geoffmcl** [comment] 2015-10-15 14:59
@chg365 ok, now have a valid utf-8 file to test...

Wow, yes the -clean option really mangles the valid utf-8 when transferring the text from the span to the generated css string...

Now to try to solve the problem...

**Comment by geoffmcl** [comment] 2015-10-15 15:17
@chg365 I noted from the images you posted on #287 that you are using version 5.0.0 of tidy...

The present development is in the `issue-65` branch, at version 5.1.15.EXP3, but confirm this bug is in that version also...

So will first work on a fix in 5.1.15.EXP3. 

Are you able to checkout and build using the `issue-65` branch for testing? Thanks...

**Comment by geoffmcl** [comment] 2015-10-15 17:29
Examining and resolving the problem.

So the `-clean` option sets `TidyMakeClean`, thus an additional service `TY_(CleanDocument)( doc );` is used to replaces presentational markup by style rules.

This service is also used if the TidyDropFontTags `--drop-font-tags yes` is on...

The function `CleanDocument` first calls `CleanTree( doc, &doc->root );` which causes no harm to the character set... but if `TidyMakeClean` is on it next calls `DefineStyleRules( doc, &doc->root );` and then `CreateStyleElement( doc );`. It must be in one of these...

Hmmm, yes, in `CreateStyleElement`, before the 'clean' the font-family name is, in hex is -
E6 96 B9 E6 AD A3 E4 BB BF E5 AE 8B

I use hex because editors and copy/paste can also mangle utf-8...

However after the above 'cleaning', and the font-family name moved to style css text the hex is -
C3 A6 C2 96 C2 B9 C3 A6 C2 AD C2 A3 C3 A4 ...

The damage is done... 

Now to discover WHY????

Ok, there's the problem. When transferring that font-family string to the newly created style css it uses `void TY_(AddStringLiteral)( Lexer* lexer, ctmbstr str )` which does -

```
void TY_(AddStringLiteral)( Lexer* lexer, ctmbstr str )
{
    byte c;
    while(0 != (c = *str++) )
        TY_(AddCharToLexer)( lexer, c );
}
```

Now the str contains the correct utf-8, but when it reaches the first E6, the `AddCharToLexer` will treat this E6 badly, then the 96, and so on...

The `AddCharToLexer` uses `err = TY_(EncodeCharToUTF8Bytes)( c, buf, NULL, &count );`, and if say you pass these to it, as bytes, it will create a 110X XXXX two byte sequence for each... ending up with rubbish...

So, using this `AddCharToLexer` to transfer this aleady valid utf-8 sequence to the lexer will cause this problem...

By the looks of this, this BUG has been in tidy for a long, long time... I do not think it is anything to do with the added html5 support...

So now I have found when, where, why... on towards a fix ;=))

The string has to be transferred to the lexer, since that is where the style tag text is held, stored, but maybe instead of `AddCharToLexer` which involves character translations, maybe the `AddStringLiteral` should just use `AddByte`, which does exactly that...

But this `AddStringLiteral` is called some 20 plus places in clean.c! Is it safe to always just use the `AddByte`? Not sure yet... in most caase looks fine like `TY_(AddCharToLexer)(lexer, '{');`, but what about `TY_(AddStringLiteral)(lexer, bgurl);`? What characters could be in `bgurl`?

Maybe I just need say a new function like say `AddStringAsIs`, which uses `AddByte` and only use that in place of `TY_(AddStringLiteral)(lexer, style->properties);`. 

That is assume all style properties have aleady been translated, and the data just moved byte by byte to the lexer... this seems a safe assumption...

And this certainly seems a minimum code change to deal with a specific case...

Will reflect on this a little... but any feedback, comments VERY welcome...

**Comment by geoffmcl** [comment] 2015-10-16 18:03
@chg365. well thinking again maybe the `AddStringLiteral` should just use `AddByte`!

This is in clean.c, so it is not invloved in reading data from a file stream, where `c = TY_(ReadChar)(doc->docIn);` must correctly handle collecting multi-byte UTF-8 from the stream, range checking it, and storing it internally.

In clean.c this is **always** just transferring already checked, `translated` data from some internal location, or static data, to the lexer buffer. It is like a simple strcpy(), but must take care of expanding the lexer buffer, if required, to hold the string... a simple copy until zero reached...

There is no need to use `AddCharToLexer`, which uses `EncodeCharToUTF8Bytes`, and to do this would in fact be a **fault**!

One that has been hanging around for quite a time to be found, due to the fact that you have to have multi-byte utf-8 data, not just ASCII single bytes, in a style attribute, and you must configure -clean to move that style to some generated css text... quite unique...

So this is the proposed simple patch -

```
diff --git a/src/lexer.c b/src/lexer.c
index 479fcc9..495aa0d 100644
--- a/src/lexer.c
+++ b/src/lexer.c
@@ -1407,8 +1407,16 @@ static Node* NewToken(TidyDocImpl* doc, NodeType type)
 void TY_(AddStringLiteral)( Lexer* lexer, ctmbstr str )
 {
     byte c;
-    while(0 != (c = *str++) )
-        TY_(AddCharToLexer)( lexer, c );
+    while(0 != (c = *str++) ) {
+        /*\
+         *  Issue #286
+         *  Previously this used TY_(AddCharToLexer)( lexer, c );
+         *  which uses err = TY_(EncodeCharToUTF8Bytes)( c, buf, NULL, &count );
+         *  But this is transferring already 'translated' data from an
+         *  internal location to the lexer, so should use AddByte()
+        \*/
+        AddByte( lexer, c );
+    }
 }
 
 /*
```

Hope you or others get a chance to apply this patch, and test... it works for me ;=))

**Comment by chg365** [comment] 2015-10-19 03:08
Thank you. It works for me too.

**Comment by geoffmcl** [comment] 2015-10-20 14:16
@chg365 thanks for testing, and reporting...

It feels like this little bug is squashed...

Have now pushed the patch to the `issue-65` branch, and bumped the version to 5.1.16... 

After a little more testing this branch will eventually be merged into `master`...

Thanks again for helping us improve tidy...

**Comment by geoffmcl** [comment] 2015-10-31 13:08
@chg365 have now merged `issue-65` to `master` and bumped the version to 5.1.17... will eventually get around to deleting the `issue-65` branch...

If you get a chance to pull `master`, build and test, maybe this issue can be closed? Thanks...

**Comment by balthisar** [comment] 2015-11-05 02:11
Confirmed fixed on my machine in current master. Since @chg365 indicates it works for him, I'll close this.

**Closed by balthisar** 2015-11-05 02:11 UTC
Labels: Bug Confirmed
