### ISSUE TITLE
Add warning for unquoted attribute containing `=`

### ISSUE THREAD

**Issue by zanona** [htacg/tidy-html5#412] opened 2016-05-26 09:36 UTC
Apparently tidy does not complain about markup like 

``` html
<meta name=viewport content=width=device-width,initial-scale=1>
```

On W3C validator [this throws an error](https://validator.w3.org/nu/?doc=data%3Atext%2Fhtml%2C%253C%21doctype%2520html%253E%253Cmeta%2520name%3Dviewport%2520content%3Dwidth%3Ddevice-width%2Cinitial-scale%3D1%253E%253Ctitle%253ETitle%253C%2Ftitle%253E):

> Error: = in an unquoted attribute value. Probable causes: Attributes running together or a URL query string in an unquoted attribute value.

Currently tidy's output is already great where it successful wraps the content within quotes properly.
This is just a Warning/Error request issue.

Thanks in advance

**Comment by geoffmcl** [comment] 2016-06-01 14:51
@zanona thanks for the issue...

Sorry for the delay... I thought I had replied, but it was just in my imagination ;=))

First, yes tidy could probably warn about this **silent** fix. But it does quite a lot of `quiet` fixes. Should we warn about these too?

And it follows, should tidy follow the validator type path... make a big noise about everything... 

Or be a relatively quiet, mainly fixing tool... just get on with the job of tidying and pretty printing... leave validation to nu?

Hmmm, will have to think about that? Sometimes I think tidy is already too noisy about somethings...

But what do other think? Add one, or more, warnings? Remember, this also effects the exit value of tidy.

Look forward to more comments on this... thanks...

**Comment by zanona** [comment] 2016-06-01 15:46
Thanks @geoffmcl.
Well, I believe you guys can be very proud nowadays because tidy is the most (if not the only) reliable HTML linter out there. This is my main usage of it actually.

I do really like the pro-activeness of tidy on making things right outputting documents as they should be. It already does a great job on this.

In regards the warnings, I believe this can simply be put behind a flag what do you think? I believe it may be something that would benefit many that want to know about their document status before any processing is done. So if we could add `--verbose` for example, Tidy could simply warn about all the issues _(good for lint in and improving best practices)_. without this flag, things are just done silently as you mentioned.

It would be interesting to know what others think as well.

All the best

**Comment by geoffmcl** [comment] 2016-06-02 00:41
@zanona, thanks for the kind words... tidy does try to be a good `linter` ;=))

Yes I can see a **new** option for this. I think `--verbose` is out, because we already shortcut `-v` to `--version`, but there has to be other choices... maybe `--noisy yes`, `-n`... Zute, there is already a `-n` for `TidyNumEntities`... but I am sure we can find a suitable option name...

Last time I added an option, I wrote an [OPTIONS.md](https://github.com/htacg/tidy-html5/blob/master/README/OPTIONS.md). It is quite straight forward even... once the name is selected...

So if you, or others want to create a fork, and present a PR, or a patch, that would be most appreciated... thanks...

**Comment by geoffmcl** [comment] 2016-06-02 16:52
@zanona picking an option name was a little difficult...

First I extracted, and sorted the tidy.c command line parsing, and got, just as a reminder of the letters already used, the following list -

````
--option_name+value   - tidyOptParseValue(tdoc, argv[1]+2, argv[2]) ) more
-access               - tidyOptSetInt( tdoc, TidyAccessibilityCheckLevel, acclvl );
-ashtml               - tidyOptSetBool( tdoc, TidyHtmlOut, yes );
-asxml -asxhtml       - tidyOptSetBool( tdoc, TidyXhtmlOut, yes );
-bare -b              - tidyOptSetBool( tdoc, TidyMakeBare, yes );
-clean -c             - tidyOptSetBool( tdoc, TidyMakeClean, yes );
-config               - tidyLoadConfig( tdoc, argv[2] ); more
-errors -e            - tidyOptSetBool( tdoc, TidyShowMarkup, no );
-file --file -f       - tidySetErrorFile( tdoc, errfil );
-gdoc -g              - tidyOptSetBool( tdoc, TidyGDocClean, yes );
-help-config          - optionhelp( tdoc ); and exit(0)
-help-option          - optionDescribe( tdoc, argv[2] ); and exit(0)
-help --help -h -?    - help( prog ); and exit(0)
-indent -i            - tidyOptSetInt( tdoc, TidyIndentContent, TidyAutoState ); plus
-language -lang       - tidySetLanguage( argv[2] ) ) more
-modify -m -change(OB) -update(OB) - tidyOptSetBool( tdoc, TidyWriteBack, yes );
-numeric -n           - tidyOptSetBool( tdoc, TidyNumEntities, yes );
-omit                 - tidyOptSetBool( tdoc, TidyOmitOptionalTags, yes );
-output --output-file -o - tidyOptSetValue( tdoc, TidyOutFile, argv[2] );
-quiet -q             - tidyOptSetBool( tdoc, TidyQuiet, yes );
-raw -ascii -latin0 -latin1 -utf8 -iso2022 -utf16le -utf16be -utf16 -shiftjis -big5 -mac -win1252 -ibm858 - tidySetCharEncoding( tdoc, arg );
-show-config          - optionvalues( tdoc ); and exit(0)
-upper -u             - tidyOptSetBool( tdoc, TidyUpperCaseTags, yes );
-version --version -v - version(); and exit(0)
-wrap --wrap -w       - tidyOptSetInt( tdoc, TidyWrapLen, wraplen );
-xml-config           - XMLoptionhelp( tdoc ); and exit(0)
-xml-error-strings    - xml_error_strings( tdoc ); and exit(0)
-xml-help             - xml_help( ); and exit (0)
-xml-options-strings  - xml_options_strings( tdoc ); and exit(0)
-xml-strings          - xml_strings( ); and exit(0)
-xml                  - tidyOptSetBool( tdoc, TidyXmlTags, yes );
````

Then I likewise alpha sorted the internal **`libtidy`** option table - it is quite large -

````
  { TidyAccessibilityCheckLevel, DG, "accessibility-check",         
  { TidyXmlDecl,                 MU, "add-xml-decl",                
  { TidyXmlSpace,                MU, "add-xml-space",               
  { TidyAltText,                 MU, "alt-text",                    
  { TidyAnchorAsName,            MU, "anchor-as-name",              
  { TidyAsciiChars,              CE, "ascii-chars",                 
  { TidyXmlPIs,                  MU, "assume-xml-procins",          
  { TidyMakeBare,                MU, "bare",                        
  { TidyBreakBeforeBR,           PP, "break-before-br",             
  { TidyCharEncoding,            CE, "char-encoding",               
  { TidyMakeClean,               MU, "clean",                       
  { TidyCoerceEndTags,           MU, "coerce-endtags",              
  { TidyCSSPrefix,               MU, "css-prefix",                  
  { TidyDecorateInferredUL,      MU, "decorate-inferred-ul",        
  { TidyDoctypeMode,             MU, "doctype-mode",                
  { TidyDoctype,                 MU, "doctype",                     
  { TidyDropEmptyElems,          MU, "drop-empty-elements",         
  { TidyDropEmptyParas,          MU, "drop-empty-paras",            
  { TidyDropFontTags,            MU, "drop-font-tags",              
  { TidyDropPropAttrs,           MU, "drop-proprietary-attributes", 
  { TidyEncloseBlockText,        MU, "enclose-block-text",          
  { TidyEncloseBodyText,         MU, "enclose-text",                
  { TidyErrFile,                 MS, "error-file",                  
  { TidyEscapeCdata,             MU, "escape-cdata",                
  { TidyEscapeScripts,           PP, "escape-scripts",              
  { TidyFixBackslash,            MU, "fix-backslash",               
  { TidyFixComments,             MU, "fix-bad-comments",            
  { TidyFixUri,                  MU, "fix-uri",                     
  { TidyForceOutput,             MS, "force-output",                
  { TidyGDocClean,               MU, "gdoc",                        
  { TidyEmacsFile,               MS, "gnu-emacs-file",              
  { TidyEmacs,                   MS, "gnu-emacs",                   
  { TidyHideComments,            MU, "hide-comments",               
  { TidyHideEndTags,             MU, "hide-endtags",                
  { TidyIndentAttributes,        PP, "indent-attributes",           
  { TidyIndentCdata,             MU, "indent-cdata",                
  { TidyIndentSpaces,            PP, "indent-spaces",               
  { TidyPPrintTabs,              PP, "indent-with-tabs",            
  { TidyIndentContent,           PP, "indent",                      
  { TidyInCharEncoding,          CE, "input-encoding",              
  { TidyXmlTags,                 MU, "input-xml",                   
  { TidyJoinClasses,             MU, "join-classes",                
  { TidyJoinStyles,              MU, "join-styles",                 
  { TidyKeepFileTimes,           MS, "keep-time",                   
  { TidyLanguage,                CE, "language",                    
  { TidyLiteralAttribs,          MU, "literal-attributes",          
  { TidyLogicalEmphasis,         MU, "logical-emphasis",            
  { TidyLowerLiterals,           MU, "lower-literals",              
  { TidyShowMarkup,              PP, "markup",                      
  { TidyMergeDivs,               MU, "merge-divs",                  
  { TidyMergeEmphasis,           MU, "merge-emphasis",              
  { TidyMergeSpans,              MU, "merge-spans",                 
  { TidyNCR,                     MU, "ncr",                         
  { TidyBlockTags,               MU, "new-blocklevel-tags",         
  { TidyEmptyTags,               MU, "new-empty-tags",              
  { TidyInlineTags,              MU, "new-inline-tags",             
  { TidyPreTags,                 MU, "new-pre-tags",                
  { TidyNewline,                 CE, "newline",                     
  { TidyNumEntities,             MU, "numeric-entities",            
  { TidyOmitOptionalTags,        MU, "omit-optional-tags",          
  { TidyOutputBOM,               CE, "output-bom",                  
  { TidyOutCharEncoding,         CE, "output-encoding",             
  { TidyOutFile,                 MS, "output-file",                 
  { TidyHtmlOut,                 MU, "output-html",                 
  { TidyXhtmlOut,                MU, "output-xhtml",                
  { TidyXmlOut,                  MU, "output-xml",                  
  { TidyPreserveEntities,        MU, "preserve-entities",           
  { TidyPunctWrap,               PP, "punctuation-wrap",            
  { TidyQuiet,                   MS, "quiet",                       
  { TidyQuoteAmpersand,          MU, "quote-ampersand",             
  { TidyQuoteMarks,              MU, "quote-marks",                 
  { TidyQuoteNbsp,               MU, "quote-nbsp",                  
  { TidyDuplicateAttrs,          MU, "repeated-attributes",         
  { TidyReplaceColor,            MU, "replace-color",               
  { TidyBodyOnly,                MU, "show-body-only",              
  { TidyShowErrors,              DG, "show-errors",                 
  { TidyShowInfo,                DG, "show-info",                   
  { TidyShowWarnings,            DG, "show-warnings",               
  { TidySkipNested,              MU, "skip-nested",                 
  { TidySlideStyle,              MS, "slide-style",                 
  { TidySortAttributes,          PP, "sort-attributes",             
  { TidyBurstSlides,             PP, "split",                       
  { TidyStrictTagsAttr,          MU, "strict-tags-attributes",      
  { TidyTabSize,                 PP, "tab-size",                    
  { TidyMark,                    MS, "tidy-mark",                   
  { TidyUnknownOption,           MS, "unknown!",                    
  { TidyUpperCaseAttrs,          MU, "uppercase-attributes",        
  { TidyUpperCaseTags,           MU, "uppercase-tags",              
  { TidyVertSpace,               PP, "vertical-space",              
  { TidyWord2000,                MU, "word-2000",                   
  { TidyWrapAsp,                 PP, "wrap-asp",                    
  { TidyWrapAttVals,             PP, "wrap-attributes",             
  { TidyWrapJste,                PP, "wrap-jste",                   
  { TidyWrapPhp,                 PP, "wrap-php",                    
  { TidyWrapScriptlets,          PP, "wrap-script-literals",        
  { TidyWrapSection,             PP, "wrap-sections",               
  { TidyWrapLen,                 PP, "wrap",                        
  { TidyWriteBack,               MS, "write-back",                  
````

After some thought I came up with `--strict`, or maybe `--strict-warnings` if you like typing. And that would lead to say a **TidyStrictWarnings** define, which seems to `fit` ok in the above internal table...

And using this then we could also have a `-s` shortcut, and/or a `-strict` shortcuts to turn it on...

Anyway, just a suggestion. 

The other thing to decide is which currently `quiet` tidy **fixes** should be a `warning`? Only one has been identified here so far...

Me, going with the idea of `strict`, I would say **ALL**. Anytime tidy adds to the users input, modifies the file text, of course excluding case, spacing, ... it should `educationally` warn about what it had to do to get valid html... But maybe that is **too much noise**... 

Or we could start with this one, and add as the case comes up... comments?

And who is going to implement this **new** feature in code?

**Comment by zanona** [comment] 2016-06-02 17:12
That's a really good @geoffmcl. I was thinking about `-V` instead of `-v` just like `curl` but that could be error prone and besides, `--strict` is much more semantic.

Since the main object of tidy is to tidy up html files, it would look weird that  people should opt-in to format their files like `tidy --strict --format index.html`. This is a case where it's clear that strict will also display warning happened during the formatting process.

But since this is not ideal I believe that by default when implementing `--strict` it should also communicate about the fixes, but with an option to disable formatting  warnings since, as you mentioned, it would become quite verbose.

perhaps something like:  `tidy --strict --noformat index.html` or ` `tidy --strict --lint-only index.html`?

or even setting a level for `--strict` like `tidy index.html --strict 0|1|2`?

Anyway, I believe strict justifies the action pretty well.

Thank you for your help.

**Comment by geoffmcl** [comment] 2016-06-02 17:20
@zanona some more good ideas... thanks...

#### But who is stepping up to choose and implement? ####

**Comment by zanona** [comment] 2016-06-02 17:35
Drum roll!
![benny-plays-the-bucket-drum-o](https://cloud.githubusercontent.com/assets/32017/15754565/8fdd0b18-28f0-11e6-8d73-e334544382f1.gif)

**Comment by geoffmcl** [comment] 2016-06-02 22:22
@zanona absolutely, we wait, until after the endless, repetitive, drum roll... very funny LOL...

I like the feature, as yet not fully spec'ed, and it is on my TODO: list, but a little bit below the `tidy` top...

If we have some other takers, like **you**, who brought this up, or **others**, then that might be quicker...

I hope our `drummer` does not get fed up by the continued silence! But why should [s]he? It is a repeat forever gif... thanks for the fun image...

**So, the question remains, who is there to do this now?**

**Comment by geoffmcl** [comment] 2017-02-28 18:30
As we are about to `release` **5.4**, and no one has stepped up to do this, can only move the milestone out to `next` **5.5**...

Maybe it will happen in the **next**... thanks...

**Comment by balthisar** [comment] 2017-05-21 20:12
I could step up to this, as I've been doing a _lot_ of work with the message system in general lately, and looking to do more work with the message system. Before going willy-nilly and making changes, I wonder if we should re-ground ourselves on the existing messages, their meanings, and what we want Tidy to do.

Have a look at new #561 for a broader scope to this topic.

**Comment by balthisar** [comment] 2017-09-22 23:17
I've added #612 which address this, but I'm questioning whether or not this is correct. According to the [specification](https://www.w3.org/TR/html5/syntax.html#attributes-0):

>Unquoted attribute value syntax
>The attribute name, followed by zero or more space characters, followed by a single U+003D EQUALS SIGN character, followed by zero or more space characters, followed by the attribute value, which, in addition to the requirements given above for attribute values, must not contain any literal space characters, any U+0022 QUOTATION MARK characters ("), U+0027 APOSTROPHE characters ('), "=" (U+003D) characters, "<" (U+003C) characters, ">" (U+003E) characters, or U+0060 GRAVE ACCENT characters (`), and must not be the empty string.

Although nearly everyone agrees that using quotes is a best practice, and Tidy's been adding quotes for @geoffmcl knows how long, isn't this something that we should allow the user to decide?

Perhaps we need a new option, e.g., `quote-attributes` with the default value `double-quote`, which would preserve Tidy's current behavior.

Proposed complete values would be:
double-quote: always ensures all attributes are double quoted, unless single quoted in the original.
single-quote: always ensures all attributes are single quoted, unless double quoted in the original.
none: will fix quote problems, but otherwise won't add quotes that aren't present in the original.

In any case, the current PR generates a lot of diffs, because there are a lot of missing quotes in some of the testbase cases.

If we're happy with the PR for the interim, feel free to merge it; we can add a new option later. I'm also going to float up some of the existing attribute errors so that they can be more descriptive, but I can do that later, too.

**Comment by geoffmcl** [comment] 2017-09-23 14:55
@balthisar the PR #612 covering this is awesome, great... thanks...

But you know me. It breaks some 24 regression tests. Thankfully **only** in the message text output - read **no html output seems changed**!

Like my `TidyShowMetaChange/show-meta-change`, should we also guard against changing the message text output, like say a `show-attribute-change`, which would default to `no`, 100% preserving backward compatibility...

Or more generally adding say an option like `--strict, -strict, -s`, defaulting to `no`, as discussed above, but if put `on` this, and **other**, presently silent fixes done by tidy, would become an `Info:` type message...

### So the question is how concerned should we be about changes in the output message text?

I can see cases where this simple message change could break some post processing, and force the user to effect change. I have several perl scripts, that parse and give me additional analysis, that would **bark** on finding a new `line 5 column 1 - Info: message...`, but could be easily fixed...

At this point I guess I am about `50:50`... still deciding, but not against. As expressed elsewhere I just **wish** this type of change was at the beginning of a new release cycle, giving us time to deal with **feedback**, if any... and not just be dumped in a new release in Nov... maybe I am being over cautious...

And since you accidentally? used the `issue_412` branch as the base for PR #613, branch `issue_434`, which is also a great addition, it presently can not be accepted until we decide, resolve, discuss this... but this could be uncoupled... which I would prefer, since they are **not** really related, except both concern attributes...

I am not sure I understood your question about `Unquoted attribute value syntax`? As you further point out tidy has been double-quoting **forever**, so does not seem a problem. It could be an error if you add the `quote-attributes` option, and the user chose `none`... my [in_412-1.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_412-1.html) passes nu... but maybe I missed your point?

**Comment by balthisar** [comment] 2017-09-23 16:36
> So the question is how concerned should we be about changes in the output message text?

Minimally concerned. One of the goals of Tidy is to warn the user about stuff. This particular item is TidyInfo, so it can be turned off with `show-tidy-info` to no. Unfortunately that turns off some of the dialogue messages, which is why there's a separate proposal to tune them (deferred until 5.7, as 5.6 is really the 5.5 stable release).

> As expressed elsewhere I just wish this type of change was at the beginning of a new release cycle, giving us time to deal with feedback, if any... and not just be dumped in a new release in Nov... maybe I am being over cautious...

This is an outstanding bug report from the year and half ago that we never closed! In any case, this is the `next` branch; when we adopted the quasi-semantic numbering, change is exactly what it's for. Version 5.6 is _different_ than 5.4; stay on 5.4 if something breaks in 5.6. And any changes made to 5.6 will be limited to bug fixes only. All of the version 5.5 changes are meant to be stable in 5.6, but 5.5 is _not_ intended to be 100% compatible with 5.4, and 5.7 offers no guarantees that it will be identical to 5.6.

@geoffmcl, we shouldn't be too concerned about changing the output text, especially in a `next` branch; scripts should be able to deal with them, because scripts never have any idea what the output text is going to be, other than test cases. Broken scripts can turn off show-tidy-info if needed.

API users, of course, can choose to filter against any messages they want, but Tidy CLI can't do that unless we want to support a switch for literally every possibility that exists, and I don't think anyone wants to go there -- that's much too granular.

Longer term thinking, we can certainly consider additional warning categories. Maybe TidyInfo isn't appropriate for this replacement, but TidyWarning is too severe. If users want notice of other "silent fixes" (or decide they don't need to see them), then perhaps a new category is in order.

An additional complication is that current `show-tidy-info` still controls some of the dialogue messages, which is why there's a separate feature request for message granularity. Essentially, an option to affect the error table, and another option to affect all of the other stuff Tidy puts out. Put the user in control instead of Tidy developers.

I don't like the idea of `--strict`; what does that me? Strict _what_? Adding quotes isn't "strict" behavior in cases where quotes aren't needed. Does it mean strict reporting? Why do we want to add another option to control report output when there's already another proposal to make this simple (i.e., show me errors, warnings, info)? This is kind of pointing towards another message category, in that case.

> I am not sure I understood your question about Unquoted attribute value syntax? As you further point out tidy has been double-quoting forever, so does not seem a problem.

It's not a problem per se, as quotes are _always_ allowed. The question is, should we allow users an option that tells Tidy to leave their missing quotes alone? In the scenario I proposed, choosing "none" shouldn't cause new problems; Tidy would still use quotes if they're already in the document; it simply wouldn't add quotes if they're not already present in the input document. In this case, though, Tidy would still do what it does today, e.g., `title=my page` becomes `title=my page=""`.

In any case, I'm willing to leave well enough alone on that last point; quotes never hurt anything, but I wanted to invite conversation because, hey!, missing quotes isn't an error condition.

**Comment by geoffmcl** [comment] 2017-09-23 17:52
@balthisar thanks for the reply... and agree **mostly**...

Ok, I'm for it, at least 51:49 ;=))

And since I also **like** the new option `TidyPriorityAttributes/priority-attributes`, #434, PR #613, maybe we just merge that, since it includes this... or separate? What do you think?

**Comment by balthisar** [comment] 2017-09-23 23:19
Glad you came around! I bet that if we merge the later one, it closes the prior one. Or... maybe not.

**Comment by balthisar** [comment] 2017-09-23 23:26
@zanona, it took a while, but I think that this change addresses your feature request, so I will close this issue. Feel free to work with the latest `next` branch.

**Closed by balthisar** 2017-09-23 23:26 UTC
Labels: Feature Request

**Comment by zanona** [comment] 2017-09-25 11:45
Thanks so much guys.

**Comment by geoffmcl** [comment] 2017-09-28 14:52
@balthisar this is **not** about this issue, but some of the change seems to have occured with PR #612, but may have been others...

A certain number of source file had their permission attribute changed, from 0664, rw-rw-r--, to 0755, -rwxrwxr-x... that is the execute bit has been added...

I changed tidy.c back to 0664, but then thought there may be some reason for this...

I would change all the others back, if there is no problem with this... is the MSVC10 editor, or some other editor accidently doing this?

It is not particularly a problem, except my color coded linux command prompt dir listing shows them as a different color, and I can run them, rather than getting `Permission denied`...

**Comment by balthisar** [comment] 2017-09-28 15:03
Nope, +x would have been a mistake. Probably a result of my recent experience with VSVC 10 and manually copying files. Good catch, and sorry 'bout that.

**Comment by geoffmcl** [comment] 2017-09-28 16:55
@balthisar no problem... have now reverted all perm changes found to 0664, -rw-rw-r--...

I have not tried MSVC 10 in a while, but do not seem to have the same problem with MSVC15, or copying, in Windows... strange, since windows does not have the same file attribute idea...

Anyway, now fixed until next time, if ever... thanks...

**Comment by balthisar** [comment] 2017-09-29 14:19
It wasn't MSVC's fault; it was not having access to git; zipping them in Windows and Unzipping on macOS was what did them in. I'll remember to double check these next time.
