### ISSUE TITLE
meta tag must be allowed in body, with microdata attributes

### ISSUE THREAD

**Issue by thlinard** [htacg/tidy-html5#333] opened 2015-12-04 11:43 UTC
It is valid HTML5 microdata to use a meta tag in the body and does validate on the W3 validator.
See https://html.spec.whatwg.org/multipage/microdata.html

**Comment by geoffmcl** [comment] 2015-12-04 18:27
@thlinard thank you for the report... as you may know RDFa support #209 / #292 is quite new to tidy.

To speed up the testing could you please supply a small input sample, show tidy version, config used, output and expected output... thanks...

**Comment by geoffmcl** [comment] 2015-12-07 23:36
@halindrome we now seem to have our first RDFa issue #333... hope you can help in this...

Am closing this as the first initial cut done... feel free to re-open or add a new issue... thanks...

**Comment by thlinard** [comment] 2015-12-07 23:50
```
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <table>
    <tbody>
      <tr>
        <td><meta itemprop="startDate" content="2015-12-21T15:00" /> <meta itemprop="endDate" content="2015-12-23T17:00" /></td>
      </tr>
    </tbody>
  </table>
</body>
</html>
```

Output:
```
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta itemprop="startDate" content="2015-12-21T15:00">
  <meta itemprop="endDate" content="2015-12-23T17:00">
</head>
<body>
  <table>
    <tbody>
      <tr>
        <td></td>
      </tr>
    </tbody>
  </table>
</body>
</html>

```

**Comment by halindrome** [comment] 2015-12-08 00:06
Are you saying this error was introduced with the addition of RDFa support, or that you would like microdata support to be extended to include this?  Trying to understand.

**Comment by geoffmcl** [comment] 2015-12-10 13:28
@thlinard sorry if I confused the situation. As per #209, @halindrome added our initial RDFa support, and at the moment I see this an extension of that support.

Looking at the code - [tags.c#L232](https://github.com/htacg/tidy-html5/blob/master/src/tags.c#L232) - we can see that the tag `TidyTag_META` is marked with a `CM_HEAD` bit. That tells tidy, in legacy html4-- mode, this can only exist in the head. So it politely moved them...

So perhaps one part of this, if I read the spec correctly, and as per your sample, it seems `meta` can be used anywhere. That means, in the above table entry, it probably should have the `CM_HEAD` bit removed, and then be added to `AdjustTags()`, to set HTML4-- mode, **and** `ResetTags()`, to reset HTML5++ mode, the default... something like -

```
    np = (Dict *)TY_(LookupTagDef)( TidyTag_META );
    // AdjustTags to html4-- mode add `CM_HEAD`
    // ResetTags  to html5++ mode, remove `CM_HEAD`, the default in the table
```

It also looks like, that if these two services continue to grow, the changes could be put in a table, or something... rather than just linear growth as at present... but that is secondary here...

And perhaps you are right, that the `attrdict.c`, `const AttrVersion TY_(W3CAttrsFor_META)[] =` needs to be extended for more attributes for the `HT50|XH50` pages? Like `TidyAttr_ITEMPROP` and maybe others...

I do not have time right now to experiment with these fixes, but will get to it! Maybe it needs more than these adjustments?

But, to be clear, what we want is **to implement full microdata support in tidy**, RDFa! Anything you, @halindrome or others can do towards this would be very much appreciated, like patches, or a PR from a fork, in say an `issue-333` branch... thanks.

**Comment by halindrome** [comment] 2015-12-10 14:21
Understood.  I can look at it.  Personally not a fan of microdata, and it
is not part of W3C HTML5 at all - it was formally dropped by the W3C.  But
I know WHATWG still is hanging onto it and Schema.org has not abandoned it
yet so...

On Thu, Dec 10, 2015 at 7:28 AM, Geoff McLane <notifications@github.com>
wrote:

> @thlinard <https://github.com/thlinard> sorry if I confused the
> situation. As per #209 <https://github.com/htacg/tidy-html5/issues/209>,
> @halindrome <https://github.com/halindrome> added our initial RDFa
> support, and at the moment I see this an extension of that support.
>
> Looking at the code - tags.c#L232
> <https://github.com/htacg/tidy-html5/blob/master/src/tags.c#L232> - we
> can see that the tag TidyTag_META is marked with a CM_HEAD bit. That
> tells tidy, in legacy html4-- mode, this can only exist in the head. So it
> politely moved them...
>
> So perhaps one part of this, if I read the spec correctly, and as per your
> sample, it seems meta can be used anywhere. That means, in the above
> table entry, it probably should have the CM_HEAD bit removed, and then be
> added to AdjustTags(), to set HTML4-- mode, *and* ResetTags(), to reset
> HTML5++ mode, the default... something like -
>
>     np = (Dict *)TY_(LookupTagDef)( TidyTag_META );
>     // AdjustTags to html4-- mode add `CM_HEAD`
>     // ResetTags  to html5++ mode, remove `CM_HEAD`, the default in the table
>
> It also looks like, that if these two services continue to grow, the
> changes could be put in a table, or something... rather than just linear
> growth as at present... but that is secondary here...
>
> And perhaps you are right, that the attrdict.c, const AttrVersion
> TY_(W3CAttrsFor_META)[] = needs to be extended for more attributes for
> the HT50|XH50 pages? Like TidyAttr_ITEMPROP and maybe others...
>
> I do not have time right now to experiment with these fixes, but will get
> to it! Maybe it needs more than these adjustments?
>
> But, to be clear, what we want is *to implement full microdata support in
> tidy*, RDFa! Anything you, @halindrome <https://github.com/halindrome> or
> others can do towards this would be very much appreciated, like patches, or
> a PR from a fork, in say an issue-333 branch... thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/htacg/tidy-html5/issues/333#issuecomment-163615025>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by geoffmcl** [comment] 2015-12-10 14:53
@halindrome your comments are well noted...

It also does not help that the W3C validator passes the following, while tidy barks and mangles dropping the span -

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Issue #333 - RFDa support - 2</title>
</head>
<body>
 <span itemscope><meta itemprop="name" content="The Castle"></span>
 <figure>
  <img src="castle.jpeg" alt="the castle">
  <figcaption>The Castle (1986)</figcaption>
 </figure>
</body>
</html>
```

As stated, any help appreciated... thanks...

**Comment by halindrome** [comment] 2015-12-10 15:04
Yeah - validator.nu supports microdata.  I don't remember if it supports
RDFa.  I sure hope so!

On Thu, Dec 10, 2015 at 8:53 AM, Geoff McLane <notifications@github.com>
wrote:

> @halindrome <https://github.com/halindrome> your comments are well
> noted...
>
> It also does not help that the W3C validator passes the following, while
> tidy barks and mangles dropping the span -
>
> <!DOCTYPE html>
> <html>
> <head>
>   <meta charset="utf-8">
>   <title>Issue #333 - RFDa support - 2</title>
> </head>
> <body>
>  <span itemscope><meta itemprop="name" content="The Castle"></span>
>  <figure>
>   <img src="castle.jpeg" alt="the castle">
>   <figcaption>The Castle (1986)</figcaption>
>  </figure>
> </body>
> </html>
>
> As stated, any help appreciated... thanks...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/htacg/tidy-html5/issues/333#issuecomment-163648655>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by geoffmcl** [comment] 2016-03-24 18:19
@thlinard, @halindrome since no one has come forward to work on this, am moving the milestone to 5.3

We are considering a release 5.2 shortly and it is unlikely to be fixed before then...

**Tidy needs your help!**

**Comment by geoffmcl** [comment] 2017-02-28 01:32
As we are about to release 5.4, and nothing has been done about this, as before moving ti to `next` 5.5... thanks...

**Comment by geoffmcl** [comment] 2017-03-20 16:01
@thlinard, @halindrome - Just reviewing this, especially using the above **sample**, which passes W3C validation, the problem happens in `parser.c`.

We are here with the `meta` node, and the `span` element, so we enter this block - 

```
        /* block level tags end this element */
        if (!(node->tag->model & CM_INLINE) &&
            !(element->tag->model & CM_MIXED))
        {
```

So we could add **CM_INLINE** to `TidyTag_META`, but that would cause lots of `meta` tags in the `head` of the document to not be put on a new line, and that looks awful...

We could add **CM_MIXED** to `TidyTag_SPAN`, but that would cause some `span` tags to be propogated, getting more `span` tags added, which is also a **mess**!

But to **fix** this problem we **must** not enter this block of code, so could create another condition that blocked it...

Could sort of create this **single**, specific exception with -

```diff
diff --git a/src/parser.c b/src/parser.c
index dd9d11e..9023ba6 100644
--- a/src/parser.c
+++ b/src/parser.c
@@ -2149,9 +2149,17 @@ void TY_(ParseInline)( TidyDocImpl* doc, Node *element, GetTokenMode mode )
             }
         }
 
-        /* block level tags end this element */
+        /*\
+         *  block level tags end this element 
+         *  Issue #333 - There seems an exception if the element is a 'span',
+         *  and the node just collected is a 'meta'. The 'meta' can not have
+         *  CM_INLINE added, nor can the 'span' have CM_MIXED added without
+         *  big consequences.
+         *  There may be other exceptions to be added...
+        \*/
         if (!(node->tag->model & CM_INLINE) &&
-            !(element->tag->model & CM_MIXED))
+            !(element->tag->model & CM_MIXED) &&
+            !(nodeIsSPAN(element) && nodeIsMETA(node)) )
         {
             if ( !TY_(nodeIsElement)(node) )
             {
```

Then the output from the above sample becomes -

```html
No warnings or errors were found.

<!DOCTYPE html>
<html>
<head>
  <meta name="generator" content=
  "HTML Tidy for HTML5 for Windows version 5.5.9.I333-1">
  <meta charset="utf-8">
  <title>Issue #333 - RFDa support - 2</title>
</head>
<body>
  <span itemscope>
  <meta itemprop="name" content="The Castle"></span>
  <figure>
    <img src="castle.jpeg" alt="the castle">
    <figcaption>
      The Castle (1986)
    </figcaption>
  </figure>
</body>
</html>
```

This patch causes no regression tests to break, and gets tidy through a document that passes W3C validation...

Have pushed this to the `issue-333` branch, and would ask others to test... thanks...

**Comment by balthisar** [comment] 2017-03-26 20:26
@geoffmcl, confirmed working on Mac OS X and Ubuntu. I didn't run through the regression tests, but this is probably a new case for testbase.

**Comment by balthisar** [comment] 2017-04-28 13:14
Given that this is merged, I will close this issue. Feel free to reopen if we missed something.

**Closed by balthisar** 2017-04-28 13:14 UTC
Labels: Feature Request
