### ISSUE TITLE
UL within UL not being wrapped with LI

### ISSUE THREAD

**Issue by emilycrutcher** [htacg/tidy-html5#572] opened 2017-06-29 19:25 UTC
``` 
   <ol>
   <li>first item</li>
   <ol><li>first sub item</li></ol> 
   <li>second item</li>
   </ol>
```
Should be illegal, and the online version will move the ol into the previous list item, but the current version leaves it unchanged.
```   
  <OL>
    <LI>first item</LI>
    <OL>
      <LI>first sub item</LI>
    </OL>
    <LI>second item</LI>
  </OL>
```

**Comment by geoffmcl** [comment] 2017-06-30 18:53
@emilycrutcher thank you for the issue...

Yes, it looks like somewhere between version 5.3.0, Apr 7, 2016, and 5.3.4, Jun 30, 2016, tidy **lost** the ability to detect and **fix** this case...

The correct output of 5.3.0, using your sample html snippet, with `--show-body-only yes`, is -

```html
F:\Projects\tidy-test\test>tidy5-5.3.0 --show-body-only yes -i input5\in_572.html
line 3 column 4 - Warning: missing <li>
Info: Document content looks like HTML5
Tidy found 1 warning and 0 errors!

<ol>
  <li>first item
    <ol>
      <li>first sub item</li>
    </ol>
  </li>
  <li>second item</li>
</ol>
```

From 5.3.4, up until the present 5.5.31, so that includes release 5.4.0, the output is invalid, as you showed...

Will see what I can do tracking down the commit, or commits, that caused this, and **fixing** it again...

Unless someone beats me to it... thanks...

**Comment by emilycrutcher** [comment] 2017-06-30 19:11
Thanks a million! Your work is very appreciated because if  you pass it to prince.xml, it completely screws up, which makes our customers very sad.
 
I am also very grateful to you for helping support this project. We have been trying to do the HTML cleaning in-house, so I know exactly how tricky these problems can be and how much high quality work it takes to maintain.

**Comment by geoffmcl** [comment] 2017-07-02 19:14
@emilycrutcher thank you for your kind words, but have now tracked down the commit b704a4d0d4587c that caused this problem... and while the commit is by @rtack, through a merge, it was a patch I suggested...

This was an attempt to **fix** issue #396, but now see it as **wrong**, or at least **incomplete**, so while the patch to **fix** this issue is to simply remove that **fix**, that would re-open #396, so now they must be considered together...

Tidy is in a service `TY_(ParseList)(TidyDocImpl* doc, Node *list, ...)`... In this case we have already had one valid `<li>`, ie done in `ParseBlock`... Now we have another start list, `<ol>` in this case...

The issue #396 is that, in html5, a list can have zero `<li>`, but here we have had one, so this should **not** apply... so have some ideas to add...

```diff
diff --git a/src/parser.c b/src/parser.c
index a037280..be07b29 100644
--- a/src/parser.c
+++ b/src/parser.c
@@ -2435,6 +2435,7 @@ void TY_(ParseList)(TidyDocImpl* doc, Node *list, GetTokenMode ARG_UNUSED(mode))
     Lexer* lexer = doc->lexer;
     Node *node, *parent, *lastli;
     Bool wasblock;
+    Bool nodeisOL = nodeIsOL(list);
 
 #if !defined(NDEBUG) && defined(_MSC_VER)
     in_parse_list++;
@@ -2452,6 +2453,7 @@ void TY_(ParseList)(TidyDocImpl* doc, Node *list, GetTokenMode ARG_UNUSED(mode))
 
     while ((node = TY_(GetToken)( doc, IgnoreWhitespace)) != NULL)
     {
+        Bool foundLI = no;
         if (node->tag == list->tag && node->type == EndTag)
         {
             TY_(FreeNode)( doc, node);
@@ -2521,10 +2523,16 @@ void TY_(ParseList)(TidyDocImpl* doc, Node *list, GetTokenMode ARG_UNUSED(mode))
             continue;
         }
 
-        if ( nodeIsLI(node) || TY_(IsHTML5Mode)(doc))
+        if ( !nodeIsLI(node) && nodeisOL )
         {
-            /* node is <LI> 
-               Issue #396 - A <ul> can have Zero or more li elements
+            /* Issue #572 - A <ol><li> can have nested <ol> elements */
+            foundLI = FindLastLI(list, &lastli); /* find last <li> */
+        }
+
+        if ( nodeIsLI(node) || (TY_(IsHTML5Mode)(doc) && !foundLI) )
+        {
+            /* node is <LI> OR
+               Issue #396 - A <ul> can have Zero or more <li> elements
              */
             TY_(InsertNodeAtEnd)(list,node);
         }
```

This seems to fix this issue, but still to re-test #396... have pushed this change to an `Issue-572` **branch**...

And need to think about this some more, and experiment... and hope others get the chance to checkout this branch and test... be back soonest, unless someone beats me to it... thanks...

**Comment by emilycrutcher** [comment] 2017-07-03 03:34
Thank you! :-)

**Comment by geoffmcl** [comment] 2017-07-03 18:50
@emilycrutcher - your `thanks` are a little premature... but `thanks`... ;=))

I have now had a chance to run our [regression tests](https://github.com/htacg/tidy-html5-tests), using the tidy 5.5.31.I572, built from the 'issue-572' branch, and it **fails** on test `case-1773932` - UGH!

This is the ongoing **game** with tidy - to make a **fix** such that it does **not** cause a **regression**... so still more to do on this issue, to get back the previous **good** behavior, and not **break** something else in the process...

Will continue to chip away at it... any help, ideas, feedback, patches, PR, ... very welcome... thanks...

PS: If you email reply to an issue, please scrub **all** the incoming text, since that is already available here... but not a big problem... just repetitive text... thanks...

**Comment by geoffmcl** [comment] 2017-07-08 18:03
@emilycrutcher pushed another patch to the 'issue-572' branch...

Now tidy 5.5.31.I572, built from the 'issue-572' branch, **passes** on tests -

 1. [case-1773932](https://github.com/htacg/tidy-html5-tests/blob/next/cases/testbase/case-1773932.html), as part of the regression tests...

 2. [in_572.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_572.html), and several others added there, **and**

 3. [in_396.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_396.html), and several others...

**BUT** the fix feels like a huge kluge, awkward... will continue to look for a better fix...

But meantime, hope people can `checkout` this **issue-572** and test it to death... thanks...

**Comment by emilycrutcher** [comment] 2017-07-08 18:58
Thank you so much!  I had a couple of questions on the patch...

*Whitespace question*
For your whitespace removal, does HTML Tidy deal with Unicode?  As I think
there are some more whitespace chars, we recently got bit by this one
because CKEditor can start inserting them if you switch the language .

 Also, if you only need to deal with ASCII, for completeness you might ad
'\f' and '\v', even though they don't show up much anymore...

*Test Question*
I see the in for 396, but I don't see the corresponding out for it?   Is
there another mechanism used to associate inputs and outputs?

**Comment by geoffmcl** [comment] 2017-07-19 19:07
@emilycrutcher thank you for the feedback and questions...

 - Whitespace question

The patch only checks the internal `lexer` character buffer, and this string has already been converted from the input charset, what ever that is, utf-8 being the default, into tidy's internal 32-bit character code, so I think it could only ever be a `' '`, `'\n'` or `'\t'`... all other space chars would have been dropped, and not made it to this internal `lexer` buffer...

In fact, it is only due to another change that returned this space only text in the first place... there were times we need to know about a protential space like in -

```html
<p>This<strong>
word</strong></p>
```

Older version of tidy, like 5.0.0, would render that as -

```html
<p>This<strong>word</strong></p>
that is the 'space' is lost, instead of
<p>This <strong>word</strong></p>
```

So I am fairly sure the patch would **not** have to deal with other **space** chars... but thanks for thinking of it...

 - Test Question
 
Well, yes, the formal regression tests, ie as in https://github.com/htacg/tidy-html5-tests, do offer the expected results... But here I was only pointing to my own `informal` test repo, where I do not provide the expected results in many cases...

If any of my informal tests are eventually added to the `official` regression tests, then yes, an expected result would also be offered...

I have now setup a PR #577 to merge this patch... testing and feedback welcome... thanks...

**Comment by balthisar** [comment] 2017-08-28 14:07
Merged. Thanks, @geoffmcl.

**Closed by balthisar** 2017-08-28 14:07 UTC
Labels: Bug

**Comment by emilycrutcher** [comment] 2017-08-28 22:21
Thanks a million!
