### ISSUE TITLE
Bad <canvas> behavior with inline elements

### ISSUE THREAD

**Issue by stevenle** [htacg/tidy-html5#78] opened 2013-01-25 05:02 UTC
Input:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title></title>
</head>
<body>
<canvas id="mycanvas" width="300" height="300">
  <p>Placeholder copy goes here</p>
</canvas>
</body>
</html>
```

Output:

```html
line 8 column 1 - Warning: missing </canvas> before <p>
line 9 column 6 - Warning: inserting implicit <canvas>
line 10 column 1 - Warning: discarding unexpected </canvas>
line 9 column 6 - Warning: <canvas> anchor "mycanvas" already defined
Info: Document content looks like HTML5
4 warnings, 0 errors were found!

<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 (experimental) for Linux https://github.com/w3c/tidy-html5/tree/c63cc39">
<meta charset="utf-8">
<title></title>
</head>
<body>
<canvas id="mycanvas" width="300" height="300"></canvas>
<p><canvas id="mycanvas" width="300" height="300">Placeholder copy
goes here</canvas></p>
</body>
</html>
```

**Comment by balthisar** [comment] 2015-02-01 09:28
Confirmed, although the issue is _block level_ elements and not inline. For example, substituting `<span>` for `<p>` works correctly.

We'll have a look.

**Comment by balthisar** [comment] 2015-02-01 11:31
Fixed in latest (did not bump build number).

Given:
~~~~
<html>
<head>
  <meta name="generator" content="HTML Tidy for HTML5 for Mac OS X version 4.9.3">
  <meta charset="utf-8">

  <title></title>
</head>

<body>
  <canvas id="mycanvas" width="300" height="300">
    <span>Placeholder copy goes here</span>
  </canvas>

  <canvas id="mycanvas2" width="300" height="300">
    <span>Placeholder copy goes here</span>
  </canvas>

  <canvas id="mycanvas3" width="300" height="300">
    <p>Placeholder copy goes here</p>
  </canvas>

  <canvas></canvas>
</body>
</html>
~~~~
Results in:
~~~~
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content="HTML Tidy for HTML5 for Mac OS X version 4.9.3">
<meta charset="utf-8">
<title></title>
</head>
<body>
<canvas id="mycanvas" width="300" height="300"><span>Placeholder copy goes here</span></canvas>
<canvas id="mycanvas2" width="300" height="300"><span>Placeholder copy goes here</span></canvas>
<canvas id="mycanvas3" width="300" height="300">
<p>Placeholder copy goes here</p>
</canvas>
<canvas></canvas>
</body>
</html>
~~~~

Note the different treatment when the canvas contains a block level tag versus an inline tag. Also handles empty canvas content.

I will close this issue. Please feel free to re-open it if it didn't address your concerns.

**Closed by balthisar** 2015-02-01 11:31 UTC
Labels: Bug Confirmed
