### ISSUE TITLE
new-blocklevel-tags doesn't work with XML para tag

### ISSUE THREAD

**Issue by Pajamaman** [htacg/tidy-html5#63] opened 2012-08-16 18:43 UTC
This issue is not specific to this version of HTML Tidy, i.e. it was in previous versions as well. Seems like this is a good place to address it however.

Config:
indent: yes
indent-spaces: 4
input-xml: yes
output-xml: yes
new-blocklevel-tags: para
wrap: 0

XML:
<pre><code>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;document&gt;
&lt;topic&gt;
&lt;para&gt;
&lt;b&gt;Name:&lt;/b&gt;Torgo.
&lt;/para&gt;
&lt;/topic&gt;
&lt;/document&gt;
</code></pre>

Converts to:
<pre><code>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;document&gt;
    &lt;topic&gt;
        &lt;para&gt;
        &lt;b&gt;Name:&lt;/b&gt;Torgo.&lt;/para&gt;
    &lt;/topic&gt;
&lt;/document&gt;
</code></pre>

Should be:
<pre><code>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;document&gt;
    &lt;topic&gt;
        &lt;para&gt;
            &lt;b&gt;Name:&lt;/b&gt;Torgo.
        &lt;/para&gt;
    &lt;/topic&gt;
&lt;/document&gt;
</code></pre>

**Comment by geoffmcl** [comment] 2015-01-26 15:32
As you may know the latest development branch is develop-500
$ git checkout develop-500
We hope you get a chance to check it out ;=))

But using your xml sample and config I can confirm this 'feature' is still in tidy code today ;=((

So technically this should be labelled a feature request, but for now will leave it as a bug, and see what can be done about it... should not be so hard to push the closing para to a new line...

**Comment by geoffmcl** [comment] 2015-02-02 14:15
Sorry, I tried and I tried, but pushing the para to a new line proved very, VERY difficult.

It has nothing to do with the new-blocklevel-tags option.

With or without this option tidy will not indent the text more, and will append the closing tag on the same line as the text, what ever the tag is.

Given that Tidy has been like this probably since the beginning, this is a feature request, and can only push it out to an indefinite future.

**Comment by geoffmcl** [comment] 2015-03-15 11:49
@Pajamaman, given that this has been a 'feature' of tidy for a long LONG time, I am not inclined to continue the search to change this behavior.

Please note it is no longer necessary to checkout the develop-500 branch. All the latest is in the default master branch as we head towards a 5.0.0 release...

I'll close this for now, but feel free to re-open, or open new issues... Thanks for reporting...

**Closed by geoffmcl** 2015-03-15 11:49 UTC
Labels: Feature
