### ISSUE TITLE
Duplicate IDs are not detected if the ID has an uppercase letter

### ISSUE THREAD

**Issue by petdance** [htacg/tidy-html5#726] opened 2018-04-25 21:42 UTC
```
$ cat -n foo.html
     1  <!DOCTYPE html>
     2  <html>
     3      <head>
     4          <title>Tidy does not detect dupe IDs if they have uppercase letters</title>
     5      </head>
     6      <body>
     7          <p    id="foo">1</p>
     8          <div  id="foo">2</div>
     9          <span id="foo">3</span>
    10
    11          <p    id="foo99">1</p>
    12          <div  id="foo99">2</div>
    13          <span id="foo99">3</span>
    14
    15          <p    id="Foo">1</p>
    16          <div  id="Foo">2</div>
    17          <span id="Foo">3</span>
    18
    19          <p    id="FOO">1</p>
    20          <div  id="FOO">2</div>
    21          <span id="FOO">3</span>
    22
    23          <a name="foo">1</a>
    24          <a name="foo">2</a>
    25          <a name="foo">3</a>
    26
    27          <a name="FOO">1</a>
    28          <a name="FOO">2</a>
    29          <a name="FOO">3</a>
    30      </body>
    31  </html>
```

```
$ tidy -q -e foo.html
line 8 column 9 - Warning: <div> anchor "foo" already defined
line 9 column 9 - Warning: <span> anchor "foo" already defined
line 12 column 9 - Warning: <div> anchor "foo99" already defined
line 13 column 9 - Warning: <span> anchor "foo99" already defined
line 23 column 9 - Warning: <a> anchor "foo" already defined
line 24 column 9 - Warning: <a> anchor "foo" already defined
line 25 column 9 - Warning: <a> anchor "foo" already defined
```

If the `id` or `name` values have an uppercase letter, then Tidy will not dupe-check them.  It will do the correct thing with digits.

**Comment by geoffmcl** [comment] 2018-04-26 17:06
@petdance thank for the issue... yes, this is a **bug**...

It turns out an `incomplete` **fix** was applied in #185... 

When creating the `NewAnchor` structure, had left converting the name to lowercase, so the `if ( TY_(tmbstrcmp)(found->name, lname) == 0 )` failed, so **no** show of the uppercased **duplicates**...

Have pushed a **fix** to the `issue-726` branch... 

My new v.5.7.14.I726 now shows 14 warnings, as opposed to the 7 you show...

```
line 8 column 9 - Warning: <div> anchor "foo" already defined
line 9 column 9 - Warning: <span> anchor "foo" already defined
line 12 column 9 - Warning: <div> anchor "foo99" already defined
line 13 column 9 - Warning: <span> anchor "foo99" already defined
line 16 column 9 - Warning: <div> anchor "Foo" already defined - NEW
line 17 column 9 - Warning: <span> anchor "Foo" already defined - NEW
line 20 column 9 - Warning: <div> anchor "FOO" already defined - NEW
line 21 column 9 - Warning: <span> anchor "FOO" already defined - NEW
line 23 column 9 - Warning: <a> anchor "foo" already defined
line 24 column 9 - Warning: <a> anchor "foo" already defined
line 25 column 9 - Warning: <a> anchor "foo" already defined
line 27 column 9 - Warning: <a> anchor "FOO" already defined - NEW
line 28 column 9 - Warning: <a> anchor "FOO" already defined - NEW
line 29 column 9 - Warning: <a> anchor "FOO" already defined - NEW
Tidy found 14 warnings and 0 errors!
```

And using the sample below, this new version will still show no warning, as expected, as would previous versions -

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Is #726-2</title>
    </head>
    <body>
        <p    id="foo">1</p>
        <div  id="Foo">2</div>
        <span id="FOO">3</span>
    </body>
</html>
```

But add a HTML4 doctype will still show 2 warnings, as expected, as did earlier versions... 

In [regression](https://github.com/htacg/tidy-html5-tests) testing, with this new version, case **588061** now shows multiple **additional** warnings, for a duplicated anchor of "MAP details", which previous versions **missed**... looks like the `expects` output needs to be adjusted...

So this looks like there should be simultanious PR's, `here` and in `tests`, not done yet... still testing, checking, etc... 

Appreciated if you, or others, could checkout the `issue-726` branch, test and report... thanks...

**Comment by petdance** [comment] 2018-04-26 18:17
How do I run the test suite?  I can't figure it out.

**Comment by geoffmcl** [comment] 2018-04-26 19:13
@petdance the first step is to clone the [test-suite](https://github.com/htacg/tidy-html5-tests) repo, and it is best if it is cloned in a parallel directory to your `tidy-html5` clone, but this is not essential...

Then `cd tidy-html5-tests`, then `cd tools-sh` or `cd tools-cmd`, depending if unix or windows... run `testall.sh` or `alltest.bat` respectively...

There is a [RUNTESTS.md](https://github.com/htacg/tidy-html5-tests/blob/next/README/RUNTESTS.md) hopefully explaining it all...

And it has been discussed **lots** of time in these issues, the last being https://github.com/htacg/tidy-html5/issues/718#issuecomment-381306111, near bottom...

Advise if you have any trouble... thanks...

**Comment by petdance** [comment] 2018-04-26 19:17
Perhaps we need something in the tidy-html5 repo that explains to go look in the test-suite repo.  I didn't realize it was a second repo.

**Comment by geoffmcl** [comment] 2018-04-27 19:02
@petdance have just pushed some updates to [CONTRIBUTING.md](https://github.com/htacg/tidy-html5/blob/next/README/CONTRIBUTING.md)... commit b952e65... and certainly mentioned the [regression](https://github.com/htacg/tidy-html5-tests) tests, in a separate repo...

Appreciated if you would check it over, and advise any errors, or other suggestions... thanks...

**Comment by petdance** [comment] 2018-04-27 19:04
Looks good.  Thanks.

**Comment by geoffmcl** [comment] 2018-05-14 15:45
Have now created PR #731, but as mentioned, `regression` test case **588061** expects needs to be adjusted at the same time... still to do a PR for that...

**Comment by geoffmcl** [comment] 2018-11-17 17:42
@petdance - Now both PRs merged... bump to version 5.7.17,  both `here`, and in `tests`... **closing** this... thanks...

**Closed by geoffmcl** 2018-11-17 17:42 UTC
Labels: Bug

**Comment by petdance** [comment] 2018-11-19 04:03
Excellent, thank you.  I'll try to work with it tomorrow.

**Comment by petdance** [comment] 2018-11-20 18:09
I don't see a tag or release for 5.7.17.  Am I missing something?

```
