### ISSUE TITLE
Nested a tags should be an error?

### ISSUE THREAD

**Issue by benkasminbullock** [htacg/tidy-html5#307] opened 2015-11-18 01:44 UTC
At the moment a document of this type:

    <!DOCTYPE html>
    <html>
    <head>
    <title>baba</title>
    </head>
    <body>
    <a href='http://example.org'>mini<a href='http://example.org'>monkey</a></a>
    </body>
    </html>

does not produce errors using tidy 5.0.0. However, most online validators give an error with the double a tag above. I cannot decipher the HTML specification as to which is correct.

**Comment by geoffmcl** [comment] 2015-11-18 18:33
@benkasminbullock thanks for reporting... it certainly looks like a **bug** has crept in ;=((

Running very close to your exact sample, my local only `input5\in_307.html`, through tidy 5.1.22+ yields no warning or error! And the output has the same nested anchors...

Running it through tidy-cvs (circa 2009) will yield -

```
line 8 column 1 - Warning: missing </a> before <a>
line 8 column 76 - Warning: discarding unexpected </a>
```

And the output will be corrected to -

```
<a href='http://example1.org'>mini</a> <a href=
'http://example2.org'>monkey</a>
```

Note I added one space between `mini` and `monkey`, which I want preserved...

I too have trouble deciphering W3C documents, fully understanding, so will let others comment on that. But I too note the W3C validator also flags an `Error`! So for now marking it as a bug!

In fact I now note we have an existing regression test for this! 

Test 427827. However this does not flag a problem because someone, probably me!, has put the nested anchor output in `testbase`. This bug was reported way back in [2001](https://sourceforge.net/p/tidy/bugs/28/), and **fixed** in July of that year.

There are some clues in the text of the above bug report, and I hope to use them to again fix 2015 tidy, unless someone else beat me to it with a PR or patch, or cites W3C documentation that specifically allows **nested anchors**.

**Comment by geoffmcl** [comment] 2015-11-21 18:16
@benkasminbullock have found a fix for this... 

Essentially the 23 Aug 00 427827 [bugs/28](https://sourceforge.net/p/tidy/bugs/28/) fix copied from ParseInline(), which used to handle anchors, and still does if the document has a legacy html4-- doctype, to ParseBlock(), which now handles anchors in html5++ mode, but will hold off pushing a few more days in case someone can cite W3C documentation that specifically allows **nested anchors**.

But all my W3C reading so far on anchors indicates they represent a `link` in the document, and thus nested anchors would make no sense. Browsers tend to display it correctly, but the W3C validator spits out an error.

This fix also includes changing the `testbase` files, out_427827.html and msg_427827.txt to match the current output. And actually found a second case 431874, [bugs/53](https://sourceforge.net/p/tidy/bugs/53/), 2001-06-10, marked as a duplicate, with similar nested anchors, files also now fixed.

The current full diff can be found at http://geoffair.org/tmp/issue307.diff if you want to try it meantime...

**Comment by benkasminbullock** [comment] 2015-11-22 05:34
> but will hold off pushing a few more days in case someone can cite W3C documentation that specifically allows nested anchors.

Well it says right at the bottom of the link you've given here:

<blockquote>
Dave Raggett responded on 03 Jan 2001 :
I need to ensure that nested anchors are detected as 
these aren't legal in HTML or XHTML. This involves a 
special check which I suspect is missing. I will add 
this to the list of things to look at for the next 
release.
</blockquote>
Since Dave Raggett actually wrote one of the HTML specifications, I don't think this is really worth worrying about.

**Comment by geoffmcl** [comment] 2015-11-22 17:48
@benkasminbullock hmmm, and assuming the spec has not changed in nearly 15 years since that post ;=))

The reason this bug re-arrived was due to a HTML5 **change** in the content of an anchor. 

Previously it only allowed `inline` or [phrasing](http://www.w3.org/TR/html-markup/terminology.html#phrasing-content) content, but can now have `block` or [flow](http://www.w3.org/TR/html-markup/common-models.html#common.elem.flow) content. See #167 and #169 and the commits for that...

But I have now found in a relatively recent document [a.html](http://www.w3.org/TR/html-markup/a.html) a clear statement **`The interactive element a must not appear as a descendant of the a element`**. As repeated that makes sense.

So have pushed this change to `master`, and bump the version to 5.1.25.

Hope you get a chance to pull, test, and close this if fixed... thanks...

**Comment by geoffmcl** [comment] 2015-12-12 17:21
@benkasminbullock no further comments in nearly 3 weeks, so assume this can be closed?

Please feel free to re-open, or open a new issue... thanks.

**Closed by geoffmcl** 2015-12-12 17:21 UTC
Labels: Bug Confirmed
