### ISSUE TITLE
"missing quote mark for attribute value" error with newlines & tags present

### ISSUE THREAD

**Issue by cjerdonek** [htacg/tidy-html5#542] opened 2017-05-04 02:19 UTC
When I pass the following string to HTML Tidy for Mac OS X or Linux version 5.4.0:

    <div foo="<br><br>

    <br><br>">x</div>

I get the following error:

    line 1 column 1 - Error: missing quote mark for attribute value

Removing just one of the newlines or `<br>` tags makes the error go away. (This is a reduced case from a longer example.)

**Comment by cjerdonek** [comment] 2017-05-04 06:35
Here is a simpler example with no left angle brackets:

    <div foo='




    >>>>>>'></div>

**Comment by cjerdonek** [comment] 2017-05-04 06:38
And an even simpler example: `<div foo='>>>>>>>>>>>'></div>`

**Comment by cjerdonek** [comment] 2017-05-04 06:41
It looks like this issue has been around for 11 years:

http://html-tidy.w3.narkive.com/KGA5IJNw/missing-quote-mark-for-attribute-value

More than 10 characters triggers it. The example in the link above has 12:

`<span id="mySpan" xml="<><><><><><>"></span>`

**Comment by cjerdonek** [comment] 2017-05-04 06:50
Looks like the offending code is [here](https://github.com/htacg/tidy-html5/blob/d8839485a419f02035530867d09866b73fd4fa4a/src/lexer.c#L4079):

    if (quotewarning > 10 && seen_gt && munge)
    {
        /*
           there is almost certainly a missing trailing quote mark
           as we have see too many newlines, < or > characters.

           an exception is made for Javascript attributes and the
           javascript URL scheme which may legitimately include < and >,
           and for attributes starting with "<xml " as generated by
           Microsoft Office.
        */
        if ( !TY_(IsScript)(doc, name) &&
             !(TY_(IsUrl)(doc, name) && TY_(tmbstrncmp)(lexer->lexbuf+start, "javascript:", 11) == 0) &&
             !(TY_(tmbstrncmp)(lexer->lexbuf+start, "<xml ", 5) == 0)
           )
            TY_(ReportFatal)( doc, NULL, NULL, SUSPECTED_MISSING_QUOTE ); 
    }

**Comment by geoffmcl** [comment] 2017-05-04 12:50
@cjerdonek thanks for the report...

This seems quite a **strange** one! And yes, has been around for a **long** time...

As you can see the enumerated value is called `SUSPECTED_MISSING_QUOTE` - just a **suspicion**, not a fact...

Since the parser has seen more than 10 `\n|<|>` chars, seen at least 1 `>`, the user has **not** added the option `--literal-attributes yes`, it is **not** `IsScript`, is **not** `IsUrl`, **not** `javascript:`, **not** `<xml `, yet it chooses this is a **fatal** error! ie no html output unless `--force-output yes` added...

Really, on an seemingly arbitrary count of greater than 10 `\n|<|>` chars Tidy outputs a catagorical statement `Error: missing quote mark for attribute value`, and goes ballistic! Huh?

At the very least I would see a clear warning like `Warning: suspect missing quote mark for attribute value`, but only as a warning, **not** fatal!

While Tidy is always very terse with warnings, and errors, if we ever went for longer descriptive helpful warnings I would suggest something like -

```
Warning: In parsing an attribute value, found %d '\n', '<', or '>', plus at least one '>' 
character, and really **suspect** there is possibly a missing closing quote somewhere. 
Ignore me at your own peril!
```

Or something... but Tidy is very unlikely to go that very verbose way, at least for now...

So, as suggested, what about reducing it to a **warning** and include the idea that this is only a **suspicion**, based on counts...

And maybe increasing the arbitrary hard coded 10 count, to at least say 20, 50... but that is still arbitrary. And in a real case, where the user did miss a closing quote, even 10 could be **too** many...

On the other hand, adding `--literal-attributes yes` to the config also removes this error/warning **and** preserves the `\n` chars, another thing that could be added to a verbose info output... 

Note that without that option tidy will only output -
```
<div foo="&lt;br&gt;&lt;br&gt; &lt;br&gt;&lt;br&gt;">x</div>
```
 even if **forced**... not exactly equivalent to the first sample input...

What do other think? Seek further feedback on this... thanks...

**Comment by cjerdonek** [comment] 2017-05-04 19:54
Thanks, @geoffmcl! Reducing to a warning sounds like a good idea. It might also be good to limit it to being emitted at most once per document. (If it's a warning, I think the number doesn't really matter, btw, so a lower number is fine IMO.)

Thanks also for the tip re: `--literal-attributes`. Are they any down-sides to that option? What is its purpose / what does it do exactly?

**Comment by balthisar** [comment] 2017-09-29 14:45
PR #617 fixes this; no regression test failures, and sample output looks acceptable. Still need to use `literal-attributes` to avoid entity substitution, though.

This is a minor change; I will merge PR if no objections in next day or so.

**Comment by balthisar** [comment] 2017-10-02 17:13
Merged and closed.

**Closed by balthisar** 2017-10-02 17:13 UTC
Labels: Feature Request, Help Needed
