### ISSUE TITLE
output-xml treats inline tags as block tags

### ISSUE THREAD

**Issue by thlinard** [htacg/tidy-html5#332] opened 2015-12-04 11:12 UTC
```
(<span>
```

give 

```
(
<span>
```

adding a space. It wasn't the case with old tidy.

**Comment by geoffmcl** [comment] 2015-12-04 18:37
@thlinard thank you for the report... I tried to construct a sample from your fragments but did not succeed.

As with #333 could you please supply a small input sample, show tidy version, config used, output and expected output... thanks...

**Comment by thlinard** [comment] 2015-12-07 23:42
Option output-xml enabled:
```
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <p>It'<a href="">(<span>s</span>)</a></p>
</body>
</html>
```

Output (2 spaces added in the rendered text):
```
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <p>It'
    <a href="">(
    <span>s</span>)</a></p>
  </body>
</html>
```

**Comment by geoffmcl** [comment] 2015-12-08 00:12
@thlinard thanks for the additional input information...

Using a slightly modified sample, which passes W3C [validation](https://validator.w3.org/#validate_by_upload) -

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Issue #332</title>
</head>
<body>
  <p>It'<a href="">(<span>s</span>)</a></p>
</body>
</html>
```

When I run tidy on this, using the default configuration, I see -

```
$ tidy input5\in_332.html
line 8 column 9 - Warning: <a> attribute "href" lacks value
Info: Document content looks like HTML5
1 warning, 0 errors were found!
```

```html
<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Windows version 5.1.32">
<meta charset="utf-8">
<title>Issue #332</title>
</head>
<body>
<p>It'<a href="">(<span>s</span>)</a></p>
</body>
</html>
```

I do not see the extra spaces...

As requested, what is the configuration used? What is the tidy library version? thanks...

**Comment by thlinard** [comment] 2015-12-08 00:23
Output-xml: yes
Tidy version: v5.1.25

**Comment by balthisar** [comment] 2015-12-08 01:25
>This option specifies if Tidy should pretty print output, writing it
as well-formed XML.                                                 

Why are you using `output-xml` for HTML content? That's not meant to be a flippant question, but trying to understand your use case.

**Comment by thlinard** [comment] 2015-12-08 09:08
In fact, I don't remember why I use this particular option, but it has never caused any problem with former Tidy. I realized the issue using an old set of options with the new Tidy.
But if this is the true intended behavior, you can close this issue.

**Comment by geoffmcl** [comment] 2015-12-09 15:03
@thlinard that ouput-xml option causes the `PPrintXMLTree` service to be used, which has **not** always received the same attention as the main HTML Pretty Print service, `PPrintTree`, but they do shares many of same `PPrintxxxxx` services, but can have differences... See the code -

```
    if ( xmlOut && !xhtmlOut )
       TY_(PPrintXMLTree)( doc, NORMAL, 0, &doc->root );
```

I do not understand what you mean by `former Tidy`, `old set`...? Testing your sample using the last SF cvs release circa 2009, it outputs the same as tidy 5.1.32 (2015) when the `--output-xml yes` option is used. This is certainly the intended behaviour, but that can change...

We could leave this open as a **Feature Request**? If anyone has an idea, patch, or PR on improving this xml output, then they would certainly be considered...

**Comment by thlinard** [comment] 2015-12-10 17:00
It outputs the same? Strange... not in my memory, but I could be wrong.

**Comment by geoffmcl** [comment] 2015-12-12 17:17
Moving this to indefinite until someone comes up with a patch or a PR to the `xmlOut`, `PPrintXMLTree1` handler...

**Comment by spookyahell** [comment] 2016-02-02 16:51
All I can say,  is that I experience the same problem. And I can give you a good reason for using output-xml. I use tidy to convert HTML to XML , so it can be properly processed by MSXML / an XML parser.

**Comment by spookyahell** [comment] 2016-02-02 16:52
I would also think that  "--markup no" option would solve that, but tidy won't accept it.

**Comment by geoffmcl** [comment] 2016-02-03 01:09
@spookyahell all I can say is I am losing track of the real problem here...

I would repeat the option `--ouput-xml yes` has **not** received that attention it deserves... but it does its current best, and does not seem to produce the addtional `added space` first reported here... So I do **not** see the extra newline shown in the original post!

If you are experiencing the **same problem** please add a sample input used, and the configuration used, what current tidy, 5.1.36 plus, `master` branch, outputs, and what you expect... then maybe something can be looked at, and done...

And I am not sure why you say "--markup no" is not accepted by tidy? In my testing that does exactly what is says - no markup generated! What else do you expect from this option?

Very confused... please explain... thanks...

**Comment by geoffmcl** [comment] 2016-02-03 01:21
@spookyahell correction... yes there is a newline added in the output, but that has **always** been there... What exactly shoud be changed?

Comments, ideas, PR always welcome...

**Comment by spookyahell** [comment] 2016-02-03 15:57
Okay, here's what I do as an example:

I take a source code like this one
[HTML-Source on Pastebin](http://pastebin.com/QpJPp6Zj)
Then call `tidy -asxml UptoboxFolder.html > UptoboxFolder.xml`, which basicly is `tidy -asxml UptoboxFolder.html` printet to a file.
As a result I get this: [XML-Source on Pastebin](http://pastebin.com/cqH734cE)
What particularly bothers me is:
`<td><a href="http://uptobox.com/1u5lawwjiai1" class="grey_link">The
Big Bang Theory - The Platonic Permutation (Clips).zip</a></td>` (Lines 448 and 449). The Text 
"The
Big Bang Theory - The Platonic Permutation (Clips).zip" is on multiple lines.
If that wouldn't happen, I wouldn't be complaining.

I can't devote all my time into this, so it could be that I am misunderstanding the way tidy works somewhere and just haven't found out jet.
I use the latest tidy (5.1.25).

**Comment by geoffmcl** [comment] 2016-02-03 17:44
@spookyahell, thanks, yes now understand! If you do not want tidy to wrap those lines 448/449, then add `-wrap 0`, or some other big number, to your config and it wont...

With `-w 0` you will get, now around output line 226, as lots of other lines are also wrapped at the default 68 chars... see [wrap](http://api.html-tidy.org/tidy/quickref_5.1.25.html#wrap) documentation...

```
<td><a href="http://uptobox.com/1u5lawwjiai1" class="grey_link">The Big Bang Theory - The Platonic Permutation (Clips).zip</a></td>
```

BTW, I used version 5.1.36 for this test of my in_332-1.html from your dropbox, but I do not think there has been any change in this since 5.1.25...

HTH! Can this be closed?

**Closed** 2017-01-31 23:22 UTC
Labels: Feature Request, Pretty Print, Technical Support
