### ISSUE TITLE
Keep the following line

### ISSUE THREAD

**Issue by kissferenc** [htacg/tidy-html5#128] opened 2014-08-17 10:30 UTC
There is a line, which appeared more alert. However, I want to leave so this line.
Example:
```
<!--Silent following line-->
Üzenet: <input id="messagefield"></input><br><br>
```
or
```
<!--Silent following lines:2-->
Üzenet: <input id="messagefield"></input><br><br>
Beállítások: <input id="messageopt"></input><br><br>
```

**Comment by geoffmcl** [comment] 2015-01-28 11:56
The latest development version of Tidy is in the develop-500 branch -
$ git checkout develop-500

But I do not understand what the problem is exactly!

Can you provide a full html sample, show the output from develop-500, and then the output you expect... Then maybe I can help...

**Comment by balthisar** [comment] 2015-02-23 05:15
@kissferenc , I'm going to close this because we don't understand the issue. If you ever come back, you can certainly re-open this issue and we'll take a look at it.

**Closed by balthisar** 2015-02-23 05:15 UTC
Labels: Bug Report
