### ISSUE TITLE
Allow div around `dt` and `dd`s 

### ISSUE THREAD

**Issue by marcoscaceres** [htacg/tidy-html5#464] opened 2016-11-03 06:54 UTC
HTML now allows:

```HTML
<dl>
   <div>
    <dt>term<dt>
    <dd>def</dd>
   </div>
</dl>
```

Relevant spec change: 
https://github.com/whatwg/html/commit/5454d702e0262749aba55576dda32c48e0e498f0

**Comment by geoffmcl** [comment] 2016-11-20 01:04
@marcoscaceres, thanks for your issue transfer...

And on the sample given, current libtidy does go into freefall...

This seems part of the ongoing effort to bump libtidy parsing 
into this century ;=)), so the FR label...

As @sideshowbarker merge sort of points out, we all 
need to change with the times... it would be even greater if 
one change mirrored others... he is a htacg dev, like you...

Look forward to some code suggestions to fix this... thanks...

**Comment by geoffmcl** [comment] 2017-03-01 13:30
As we are about to `release` **5.4**, moving this to `next` **5.5**.

Have added a sample [in_468-2.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_464-2.html) which passes validation! Tidy should do likewise...

**As usual comments, patches or PR very welcome**... thanks...

**Closed** 2021-08-17 15:52 UTC
Labels: Feature Request

**Comment by balthisar** [comment] 2021-08-17 15:55
Four and half years later, finally fixed.

**Comment by marcoscaceres** [comment] 2021-08-17 20:15
Awesome! thanks for keeping the project going.

**Comment by uandco** [comment] 2023-08-31 11:12
Is it really fixed or is there a regression?
I'm passing this:

```
<dl
>
    <div>
        <dt>
            General Enquiries
            <span>(Mon-Fri, 8am-5pm)</span>        </dt>
        <dd>
            <div class="uu-font-xxl">
                13 26 57
            </div>
        </dd>
    </div>
    <div>
        <dt>
            Price
                    </dt>
        <dd>
            <div class="uu-font-xxl">
                <strong>$300</strong>
            </div>
        </dd>
    </div>
    <div>
        <dt>
            Example term
                    </dt>
        <dd>
            <div>
                Definition example
            </div>
        </dd>
    </div>
</dl>
```

and the result is:

```
<dl>
  <dd>
    <div>
      <dl>
        <dt>
          General Enquiries <span>(Mon-Fri, 8am-5pm)</span>
        </dt>
        <dd>
          <div class="uu-font-xxl">
            13 26 57
          </div>
        </dd>
      </dl>
    </div>
    <div>
      <dl>
        <dt>
          Price
        </dt>
        <dd>
          <div class="uu-font-xxl">
            <strong>$300</strong>
          </div>
        </dd>
      </dl>
    </div>
    <div>
      <dl>
        <dt>
          Example term
        </dt>
        <dd>
          <div>
            Definition example
          </div>
        </dd>
      </dl>
    </div>
  </dd>
</dl>
```

Options:
```
[
            'indent' => true,
            'wrap' => 80,
            'custom-tags' => true,
            'show-body-only' => true,
            'drop-proprietary-attributes' => false,
        ]
```

Errors:

```
line 3 column 5 - Warning: missing <dd>
line 3 column 5 - Warning: missing </div> before <dt>
line 4 column 9 - Warning: inserting implicit <dl>
line 4 column 9 - Warning: missing </dl> before </div>
line 13 column 5 - Warning: missing </div> before <dt>
line 14 column 9 - Warning: inserting implicit <dl>
line 14 column 9 - Warning: missing </dl> before </div>
line 23 column 5 - Warning: missing </div> before <dt>
line 24 column 9 - Warning: inserting implicit <dl>
line 24 column 9 - Warning: missing </dl> before </div>
```

**Comment by Moth-Tolias** [comment] 2026-08-29 15:35
just ran into this. it's a bummer, because it means that tidy isn't suitable for my usecase.

**Comment by marcoscaceres** [comment] 2026-08-29 16:41
@Moth-Tolias you can’t send a PR? Would probably take copilot like 2 minutes to fix it and fully test it.
