### ISSUE TITLE
boolean attributes in self closing void tags are not correctly parsed if there is no space between attribute and self closing tag.

### ISSUE THREAD

**Issue by rtack** [htacg/tidy-html5#395] opened 2016-04-04 11:37 UTC
Currently a warning is given
ine 1 column 36 - Warning: <input> attribute "disabled/" lacks value

even though boolean attributes as defined in https://www.w3.org/TR/html5/infrastructure.html#boolean-attribute
should not have values. 

A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

**Comment by geoffmcl** [comment] 2016-04-05 13:18
@rtack thank you for the report...

To make testing and fixing easier I wonder if you would be kind enough to -

 - Advise the tidy version `$ tidy -v`
 - Supply a (minimal) html sample
 - Advise any non-default config used
 - Current output
 - Expected output
 
Yes, we can **guess** at some of these, but it makes it quicker if given **all** the above... thanks...

I did some searching but seem unable to find a neat list of `boolean attributes`! Yes, I saw **checked** and **disabled**, but maybe need a complete list, if there is one, and each of the elements they can be used on...

However, before that, using the following simple input sample I can **not** reproduce this problem!

````
<label><input type=checkbox checked name=cheese disabled> Cheese</label>
````

And a config of `--show-body-only yes --show-info no -w 0`, I get the output of -

````
No warnings or errors were found.
Info: Document content looks like HTML5
<label><input type="checkbox" checked name="cheese" disabled> Cheese</label>
````

I was using a very recent tidy `HTML Tidy for Windows version 5.1.51`...

So the questions become what version?, on what sample?, with what config?

**Comment by rtack** [comment] 2016-04-05 18:12
After some more digging found out what the difference is

The following will validate fine..
```
<label><input type=checkbox checked name=cheese disabled> Cheese</label>
```
If the input tag is self closing and there is NO space before '/' the attribute is wrongly parsed as "disabled/" instead of "disabled" which leads to the warning.
```
<label><input type=checkbox checked name=cheese disabled/> Cheese</label>
```
Warning: attribute "disabled/" lacks value

If the input tag is self closing and there IS a space before '/' the attribute is correctly parsed as "disabled" and no warning is given.
```
<label><input type=checkbox checked name=cheese disabled/> Cheese</label>
```

https://www.w3.org/TR/html5/syntax.html#void-elements
says that void elements are allowed to be self closing and 
```
<label><input type=checkbox checked name=cheese disabled/> Cheese</label>
```
validates fine in the w3c validator.

**Comment by rtack** [comment] 2016-04-05 18:53
http://stackoverflow.com/a/707702/1275767 has a list of boolean attributes and the tags they can be used.

**Comment by geoffmcl** [comment] 2016-04-05 23:22
@rtack, wow, thank you for the feedback, further testing, and the **time consuming research**...

First fixing the title - 3 times - was not really necessary, once the issue is clarified, the original title would have been ok... but no problem... thanks...

If simple terms this looks like a **simple** fix - watch out for a `/` when parsing an attribute - it could mean it is a self closing tag, provided of course tidy already has `input` flagged as a possible self closer, which I think it does...

But even if it does **not**, a `/` should be a clear signal to check the next character in the stream, and if it is a `>`, get out of here quick... 

So this gives a very clear path for getting a **fix** for this...

As to using [stackoverflow](http://stackoverflow.com/a/707702/1275767) as a **valid** W3C reference... well that is possible... but we need to check the code to see exactly why it passes over say `checked` as **not** a problem... does tidy have some list, table, etc... it uses for such decisions... Maybe need some enhancement here, but that is really a separate issue...

And also thank you for checking the W3C validator... While that is **not** always definitive, we are `HTACG`, ie part of the `W3C` community... so it does have an influence...

So like I say, there seems a clear code path to check, if you, or someone else, do not beat me to it ;=))

Again thank you. **Tidy needs your support!**. Patches or a [PR](https://github.com/htacg/tidy-html5/pulls) are **very** welcome...

**Comment by geoffmcl** [comment] 2017-02-28 17:54
As we are about to release **5.4**, and no further work has been done on this issue to date, moving it to `next` **5.5**.

I have already indicated there is a clear path to **fixing** this. Patches or PR **very** welcome... thanks...

**Comment by geoffmcl** [comment] 2017-05-20 23:56
@rtack after several months, cycled back to looking at this **again**... as stated it seems the `code path` is there...

In general see nothing wrong with `disable\>` versus `disable \>`... **both** should be acceptable by tidy...

So created an `issue-395` branch to look at this... 

Made a simple patch to specifically solve this...

```diff
diff --git a/src/lexer.c b/src/lexer.c
index 238fbfa..77af713 100644
--- a/src/lexer.c
+++ b/src/lexer.c
@@ -3723,6 +3723,22 @@ static tmbstr  ParseAttribute( TidyDocImpl* doc, Bool *isempty,
         if (TY_(IsWhite)(c))
             break;
 
+        if (c == '/') /* Issue #395 - potential self closing tag */
+        {
+            c = TY_(ReadChar)(doc->docIn);  /* read next */
+            if (c == '>')
+            {
+                /* got a self closing tag - put is back and continue... */
+                TY_(UngetChar)(c, doc->docIn);
+                break;
+            }
+            else
+            {
+                /* Not '/>' - put it back */
+                TY_(UngetChar)(c, doc->docIn);
+            }
+        }
+
         /* what should be done about non-namechar characters? */
         /* currently these are incorporated into the attr name */
```

This seems to **fix** this issue...
 
Appreciate others checking out the `issue-395` branch, and testing... specifically with sample [in_395-2.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_395-2.html)...  thanks...

**Comment by balthisar** [comment] 2017-05-21 18:52
The `issue-395` branch is working just fine for me, @geoffmcl, so feel free to merge this fix.

**Closed** 2017-05-27 16:27 UTC
Labels: Bug, Technical Support
