### ISSUE TITLE
Accents in URIs cause incorrect warning "escaping malformed URI reference"

### ISSUE THREAD

**Issue by a3nm** [htacg/tidy-html5#378] opened 2016-02-20 21:47 UTC
Consider the following document (in UTF-8):

```
<!DOCTYPE html>
<html dir="ltr" xml:lang="en" lang="en">
<head>
  <title>a</title>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
</head>
<body>
  <p><a href="http://example.com/é">foo</a></p>
</body>
</html>
```

When running `/usr/local/bin/tidy -utf8 -errors -quiet` on this document, I get the following warning:

```
line 8 column 6 - Warning: <a> escaping malformed URI reference
```

The warning only shows up when the href contains an accented character. This seems bogus to me, I don't think non-ASCII characters in href are disallowed. Further, validator.w3.org accepts the document. I think the warning shouldn't be emitted.

This may be related to #352, but maybe not.

**Comment by geoffmcl** [comment] 2016-02-21 17:10
@a3nm I think this is **very** related to #352 - sort of `what are valid characters in a URL`?

As then, I again searched **hard** for answers here. All I can read according to [rfc 1738](http://www.rfc-editor.org/rfc/rfc1738.txt), and many other references, all characters out of the US-ASCII range must be escaped, and even quite a few within that range!

Even trying an example in the [W3CSchools](http://www.w3schools.com/tags/ref_urlencode.asp), admittedly not to be taken as W3C approved, escapes such `accented` characters...

As indicated in #352, the existing internal tidy service [CheckUrl](https://github.com/htacg/tidy-html5/blob/master/src/attrs.c#L1469) has a simple test of what characters tidy will escape, namely `if ((c > 0x7e) || (c <= 0x20) || (strchr("<>", c)))`, and even this range check should maybe be extended to more invalid characters...

I would ask you, and others, to provide further W3C references on this issue... and the fact that the W3C validator does not flag a problem is definitely **not** the sole criteria to be considered... thanks...

**Comment by a3nm** [comment] 2016-02-21 22:00
For HTML 4 and earlier, I don't know. For HTML 5, however, the current draft defines the contents of the href attribute as a "valid URL potentially surrounded by spaces." https://www.w3.org/TR/html5/links.html#attr-hyperlink-href which is defined from "valid URL" https://www.w3.org/TR/html5/infrastructure.html#valid-url defined as "[conforming] to the authoring conformance requirements in the URL standard", which points to https://www.w3.org/TR/html5/references.html#refsURL. Discarding the note I get to the URL standard https://www.w3.org/TR/url/ whose latest version is https://url.spec.whatwg.org/.

It is hard to see but I think the intent of this spec is to allow Unicode URLs. Specifically, it defines the https://url.spec.whatwg.org/#url-code-points as including large Unicode ranges and the note afterwards clarifies the intended meaning: the URL parser https://url.spec.whatwg.org/#concept-url-parser indeed runs on UTF-8 encoded data (see step 4 of the basic URL parser). It percent-encodes any extended characters it finds, which is why in the definition of URLs https://url.spec.whatwg.org/#urls it only allows ASCII strings (those are the result of applying the parser).

So my understanding is that, in HTML 5, URLs may include Unicode characters pursuant to the URL standard, and should not raise an error with tidy. (Of course it's still perfectly fine to percent-encode them.)

Does this sound reasonable to you?

**Comment by geoffmcl** [comment] 2016-02-23 00:45
@a3nm, thank you for the continued the research into this... this is what we need... help to understand...

I have tried to carefully read, and understand, to the best of my ability, each link you provided... but this still remains complex...

> Does this sound reasonable to you?

I think you ask here, should full UTF-8 character encoding be allowed in a `href` URL? Like the W3C validator seems to allow!

You provided an interesting [link](https://url.spec.whatwg.org/#url-code-points), but ask us to **ignore** the `NOTE` there, which I repeat -

```
Code points higher than U+009F will be converted to percent-encoded bytes by the URL parse
```

That is what tidy does, and issues a warning about its change, as it should about document change.

Should tidy have another option, like if instructed this a utf-8 encoded document, then accept utf-8 in a `href`, like the W3C validator does?

Not so sure. The validator, and browsers, readily also accept the tidy percent encoded url, and browsers seem to display the accented character as the link... so browsers 'understand' percentage encoding, and correctly display the result...

And **note** tidy already has a **`--fix-uri no`** otpions, and it will **not** escape the uri, but will still issue the warning.

Now, maybe there is a small case here for, if the user adds the option `--fix-uri no`, then maybe tidy should not emit the warning, since it has been instructed to **not** change the document. This is a possibility...

But as it stands, I am sorry, I am not yet convinced to change tidy's current behaviour...

But as always, seek more comments on this... thanks...

**Comment by a3nm** [comment] 2016-02-23 00:52
Thanks for your explanations!

I should be clear that, in my use case, I am using tidy only to validate HTML documents, not to rewrite them to anything. In light of this:

> Code points higher than U+009F will be converted to percent-encoded bytes by the URL parse

This is what the spec says that software reading URLs (for example in href) should be doing when processing the documents. It means tidy should be parsing URLs by accepting UTF-8 input, converting it to percent-encoding internally, and then do whatever it wants to do with it. (In this light it may or may not be reasonable to output URLs in a percent-encoded form in the processed document; I don't really know for this.)

So I'm not arguing against tidy rewriting these URLs (and I think the ideal is to be able to do one or the other depending on user preference, which is what your flag permits). My only concern is about the warning. My understanding of the WhatWG URL spec is that UTF-8 characters in URLs are perfectly fine and anything reading URLs in HTML 5 documents should be able to process them (doing as if they had read the percent-encoding). So I don't thing that tidy should be emitting a warning against them. :)

Does this clarify what I had in mind? :-)

**Comment by geoffmcl** [comment] 2016-03-24 19:49
@a3nm ok, I think I understand your only concern is about the warning, and as suggested I do see a small case for omitting the warning with the option `--fix-uri no`, since tidy is then doing nothing except outputting exactly what it was given... but otherwise, if left to escape the uri, then the warning of change should stay...

But we are considering a release 5.2 shortly, and it seems unlikely that I or others will be able to agreed, implemented, and tested a solution before then am moving this to milestone 5.3.

**Comment by zmwangx** [comment] 2017-01-02 18:08
I realize this issue is kind of stale and hasn't generated a lot interest, but I do want to contribute a new perspective. While it is true and unfortunate that the currently published version (October 2014) of the HTML5 standard waves its hands when it comes to the definition of URLs, the current working spec gives a very clear definition. To quote https://dev.w3.org/html5/spec-LC/urls.html:

> A URL is a string used to identify a resource.
> 
> A URL is a valid URL if at least one of the following conditions holds:
> 
> - The URL is a valid URI reference [RFC3986].
> 
> - The URL is a valid IRI reference and it has no query component. [RFC3987]
> 
> - The URL is a valid IRI reference and its query component contains no unescaped non-ASCII characters. [RFC3987]
> 
> - The URL is a valid IRI reference and the character encoding of the URL's Document is UTF-8 or UTF-16. [RFC3987]

The message and trend here is very clear: IRIs as defined by RFC3987 are being promoted to first class citizens, especially in UTF-8/UTF-16 encoded documents.

@geoffmcl Omitting the warning when `--fix-uri no` is definitely a welcome change in the short term. (FYI, I also only use tidy-html5 to validate my documents, and I'm currently developing a website with non-ASCII paths.)

In the long term, I think there will come a day when `--fix-uri` should no longer default to `yes`, and I don't think it will be too far into the future.

**Comment by geoffmcl** [comment] 2017-02-28 17:49
As we are about to release **5.4**, and no further progress has been made on this issue, and there is the option `--fix-uri no` exists, **and** this issue is also covered by #352, am closing this for now.

Another option would be moving it to `next` **5.5**, but as indicated it does seem a duplicate of #352, so...

As always, feel free to re-open or file a new issue... thanks...

**Comment by zmwangx** [comment] 2017-03-09 19:03
Sorry for the late reply on a closed issue. But I don't think this is a duplicate of #352.

#352 is about truly invalid characters in hrefs, e.g. `|`, which isn't a valid URI character per either RFC 3986 or RFC 3987. The problem in the case is that tidy isn't spotting the invalid character, and isn't doing anything, not even emitting an error.

The issue here is different. `http://example.com/é` is a valid IRI per RFC 3987, and tidy is (arguably wrongly) flagging it as malformed.

**Comment by balthisar** [comment] 2017-03-09 19:12
I'll reopen this pending further investigation.

**Comment by deathbaba** [comment] 2017-04-21 06:55
What about using ```--fix-uri no``` for any valid UTF-8/16 HTML5 document by default?

**Comment by balthisar** [comment] 2017-05-07 01:38
> Now, maybe there is a small case here for, if the user adds the option --fix-uri no, then maybe tidy should not emit the warning, since it has been instructed to not change the document. This is a possibility...

I don't really see the issue with warnings; they're not errors. Perhaps we can classify them as info instead of warnings when --fix-uri is no. Otherwise, I'm not against simply eliminating the warning when `no`; after all, the default is `yes`, and so it takes knowledge of the consequences to set this option, so there's a case for suppressing them when `no`.

Let me know, as this is an easy fix.

**Comment by a3nm** [comment] 2017-05-07 11:25
@balthisar: My use case is that I use tidy to validate HTML documents that I produce. In this context, I try to fix warnings when they are relevant. Given that the warning about UTF-8 characters in URLs appears to be bogus based on my understanding of the HTML5 spec, I'd like to be able to suppress it with `--fix-uri no` (or some other command-line parameter), rather than having to write my own custom logic around tidy to silence that specific warning.

**Comment by zmwangx** [comment] 2017-05-07 15:01
>  I'm not against simply eliminating the warning when no; after all, the default is yes, and so it takes knowledge of the consequences to set this option, so there's a case for suppressing them when no.

+1 to no warnings at all when `--fix-uri no`. They only add to noises when I know what I'm doing.

**Comment by balthisar** [comment] 2017-05-07 22:04
@geoffmcl, this would be super simple to roll into #352. Either squelch them when `--fix-uri no`, or assign them to the underused `TidyInfo`, which the user can choose to squelch with `show-info`. Of course the default would remain a proper warning along with escaping them.

**Comment by balthisar** [comment] 2017-05-14 00:51
@a3nm, @zmwangx, @deathbaba, have a look at #556, which simply squelches the warning for HTML5 documents, and preserves existing behavior for legacy documents. If it satisfies everyone, there should be no issue rolling it in.

**Comment by balthisar** [comment] 2017-05-16 16:23
Oops. This should have auto closed.

**Closed by balthisar** 2017-05-16 16:23 UTC
Labels: Help Needed
